-- Transport Control Retail v1
-- Applied to Supabase project ccmwhtojyofefyzespty on 2026-08-31.

create table if not exists public.tc_retail_stores (
  id bigint generated by default as identity primary key,
  name text not null unique,
  direction text,
  default_warehouse text,
  default_temperature text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.tc_retail_vehicles (
  id bigint generated by default as identity primary key,
  plate text not null unique,
  carrier text,
  pallet_capacity numeric,
  max_weight_kg numeric,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.tc_retail_routes (
  id bigint generated by default as identity primary key,
  route_date date not null default current_date,
  warehouse text not null,
  temperature text,
  vehicle_id bigint references public.tc_retail_vehicles(id),
  driver_name text,
  carrier text,
  route_no text,
  tariff numeric(12,2),
  comment text,
  status text not null default 'draft' check (status in ('draft','filled','departed','in_progress','completed','closed','needs_attention','cancelled')),
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tc_retail_route_points (
  id bigint generated by default as identity primary key,
  route_id bigint not null references public.tc_retail_routes(id) on delete cascade,
  store_id bigint references public.tc_retail_stores(id),
  pallets numeric not null default 0,
  weight_kg numeric not null default 0,
  sort_order integer not null default 0,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists tc_retail_routes_date_idx on public.tc_retail_routes(route_date desc);
create index if not exists tc_retail_route_points_route_idx on public.tc_retail_route_points(route_id);