-- Additive finance layer for the Cloudflare migration. Existing zone/rate ledgers are preserved.
set lock_timeout = '5s';
create table public.transport_delivery_coverage (
 id uuid primary key default gen_random_uuid(), carrier text not null check (carrier in ('STV','SAV')),
 region text not null check (length(trim(region))>0), district text not null check (length(trim(district))>0),
 branch text not null check (length(trim(branch))>0), zone integer not null check (zone between 1 and 5), active boolean not null default true,
 unique(carrier,region,district)
);
create table public.transport_monthly_rates (
 carrier text not null check (carrier in ('STV','SAV')), month date not null check (extract(day from month)=1),
 tt_fixed numeric not null check(tt_fixed>=0), zone1 numeric not null check(zone1>=0), zone2 numeric not null check(zone2>=0),
 zone3 numeric not null check(zone3>=0), zone4 numeric not null check(zone4>=0), zone5 numeric not null check(zone5>=0),
 primary key(carrier,month)
);
create table public.fleet_cost_entries (
 id uuid primary key default gen_random_uuid(), month date not null check(extract(day from month)=1),
 block text not null check(block in ('fop','bakery')), expeditor_names text[] not null check(cardinality(expeditor_names)>0 and array_position(expeditor_names,null) is null),
 salary numeric(16,2) not null default 0 check(salary>=0), fuel numeric(16,2) not null default 0 check(fuel>=0),
 depreciation numeric(16,2) not null default 0 check(depreciation>=0), repair numeric(16,2) not null default 0 check(repair>=0), insurance numeric(16,2) not null default 0 check(insurance>=0),
 total numeric(16,2) generated always as (salary+fuel+depreciation+repair+insurance) stored,
 created_by uuid default auth.uid(), created_at timestamptz not null default now()
);
create index fleet_cost_month_block on public.fleet_cost_entries(month,block);
create table public.transport_carrier_blocks (block text not null check(block in ('fop','bakery')),name text not null references public.transport_carriers(name),primary key(block,name));
alter table public.fop_manual_routes add column block text not null default 'fop' check(block in ('fop','bakery'));
alter table public.fop_manual_routes add column expeditor_name text;
alter table public.fop_manual_routes add column wave text;
create table public.stv_branch_directory(name text primary key check(length(trim(name))>0),active boolean not null default true);
create function public.transport_interbranch_total(items jsonb) returns numeric language plpgsql immutable security invoker set search_path='' as $$
declare r jsonb; result numeric=0; names text[]='{}'; nm text; pal numeric; rate numeric;
begin
 if jsonb_typeof(items)<>'array' or jsonb_array_length(items)=0 then return null; end if;
 for r in select value from jsonb_array_elements(items) loop
  if jsonb_typeof(r->'pallets')<>'number' or jsonb_typeof(r->'rate')<>'number' then return null; end if;
  nm=trim(r->>'name');pal=(r->>'pallets')::numeric;rate=(r->>'rate')::numeric;
  if nm is null or nm='' or nm=any(names) or pal is null or pal<=0 or rate is null or rate<0 then return null;end if;
  names=array_append(names,nm);result=result+round(pal*rate,2);
 end loop;
 return result;
end $$;
revoke all on function public.transport_interbranch_total(jsonb) from public,anon;
grant execute on function public.transport_interbranch_total(jsonb) to authenticated;
create table public.stv_interbranch_months (
 id uuid primary key default gen_random_uuid(),month date not null check(extract(day from month)=1),sender text not null references public.stv_branch_directory(name),
 receivers jsonb not null,
 total numeric generated always as (public.transport_interbranch_total(receivers)) stored,
 check(total is not null and total>=0),unique(month,sender)
);
do $$ declare t text; roles_sql text; begin
 foreach t in array array['transport_delivery_coverage','transport_monthly_rates','fleet_cost_entries','transport_carrier_blocks','stv_branch_directory','stv_interbranch_months'] loop
  execute format('alter table public.%I enable row level security',t);
  execute format('revoke all on public.%I from anon',t);
  execute format('grant select,insert,update on public.%I to authenticated',t);
  execute format('create policy app_read on public.%I for select to authenticated using ((select public.current_app_role()) is not null)',t);
  roles_sql=case when t in ('transport_carrier_blocks','stv_branch_directory','stv_interbranch_months') then '(''admin'',''manager'',''logistician'')' else '(''admin'',''manager'')' end;
  execute format('create policy app_insert on public.%I for insert to authenticated with check ((select public.current_app_role()) in %s)',t,roles_sql);
  execute format('create policy app_update on public.%I for update to authenticated using ((select public.current_app_role()) in %s) with check ((select public.current_app_role()) in %s)',t,roles_sql,roles_sql);
 end loop;
end $$;
-- No tariff month is inferred from the workbook; users explicitly save the month in the UI.
insert into public.transport_delivery_coverage(carrier,region,district,branch,zone) values
('STV','Вінницька','Жмеринський','Вінниця',1),
('STV','Вінницька','Вінницький','Вінниця',1),
('STV','Вінницька','Липовецький','Вінниця',2),
('STV','Вінницька','Козятинський','Вінниця',2),
('STV','Вінницька','Могилів-Подільський','Вінниця',3),
('STV','Вінницька','Літинський','Вінниця',1),
('STV','Вінницька','Барський','Вінниця',2),
('STV','Вінницька','Ямпільський','Вінниця',4),
('STV','Вінницька','Томашпільський','Вінниця',3),
('STV','Вінницька','Калинівський','Вінниця',1),
('STV','Вінницька','Тульчинський','Вінниця',2),
('STV','Вінницька','Шаргородський','Вінниця',2),
('STV','Вінницька','Хмільницький','Вінниця',2),
('STV','Вінницька','Гайсинський','Вінниця',3),
('STV','Вінницька','Немирівський','Вінниця',1),
('STV','Вінницька','Бершадський','Вінниця',4),
('STV','Вінницька','Тростянецький','Вінниця',3),
('STV','Вінницька','Тиврівський','Вінниця',1),
('STV','Вінницька','Піщанський','Вінниця',3),
('STV','Волинська','Луцький','Луцьк',1),
('STV','Волинська','Володимирський','Луцьк',2),
('STV','Волинська','Горохівський','Луцьк',1),
('STV','Волинська','Ковельський','Луцьк',2),
('STV','Волинська','Ківерцівський','Луцьк',1),
('STV','Волинська','Ратнівський','Луцьк',3),
('STV','Волинська','Камінь-Каширський','Луцьк',3),
('STV','Волинська','Локачинський','Луцьк',1),
('STV','Волинська','Рожищенський','Луцьк',1),
('STV','Волинська','Любомльський','Луцьк',3),
('STV','Волинська','Іваничівський','Луцьк',2),
('STV','Дніпропетровська','Кривий Ріг','Дніпро',1),
('STV','Дніпропетровська','Дніпровський','Дніпро',1),
('STV','Дніпропетровська','Самарівський','Дніпро',1),
('STV','Дніпропетровська','Криворізький','Дніпро',1),
('STV','Житомирська','Житомирський','Житомир',1),
('STV','Житомирська','Бердичівський','Житомир',1),
('STV','Житомирська','Звягельський','Житомир',2),
('STV','Житомирська','Коростенський','Житомир',2),
('STV','Житомирська','Пулинський','Житомир',1),
('STV','Житомирська','Брусилівський','Житомир',2),
('STV','Житомирська','Олевський','Житомир',4),
('STV','Житомирська','Радомишльський','Житомир',2),
('STV','Житомирська','Хорошівський','Житомир',2),
('STV','Житомирська','Коростишівський','Житомир',1),
('STV','Закарпатська','Мукачівський','Львів',1),
('STV','Закарпатська','Ужгородський','Львів',1),
('STV','Закарпатська','Виноградівський','Львів',3),
('STV','Закарпатська','Берегівський','Львів',1),
('STV','Закарпатська','Тячівський','Львів',3),
('STV','Закарпатська','Хустський','Львів',3),
('STV','Закарпатська','Рахівський','Львів',5),
('STV','Запорізька','Запорізький','Дніпро',1),
('STV','Івано-Франківська','Івано-Франківський','Ів.-Франківськ',1),
('STV','Івано-Франківська','Косівський','Ів.-Франківськ',2),
('STV','Івано-Франківська','Богородчанський','Ів.-Франківськ',1),
('STV','Івано-Франківська','Верховинський','Ів.-Франківськ',3),
('STV','Івано-Франківська','Коломийський','Ів.-Франківськ',2),
('STV','Івано-Франківська','Тисменицький','Ів.-Франківськ',1),
('STV','Івано-Франківська','Калуський','Ів.-Франківськ',1),
('STV','Івано-Франківська','Надвірнянський','Ів.-Франківськ',1),
('STV','Івано-Франківська','Долинський','Ів.-Франківськ',2),
('STV','Івано-Франківська','Яремче','Ів.-Франківськ',2),
('STV','Івано-Франківська','Галицький','Ів.-Франківськ',1),
('STV','Івано-Франківська','Снятинський','Ів.-Франківськ',2),
('STV','Івано-Франківська','Тлумацький','Ів.-Франківськ',1),
('STV','Івано-Франківська','Городенківський','Ів.-Франківськ',2),
('STV','Івано-Франківська','Рожнятівський','Ів.-Франківськ',2),
('STV','Львівська','Миколаївський','Львів',2),
('STV','Львівська','Борислав','Львів',2),
('STV','Львівська','Пустомитівський','Львів',1),
('STV','Львівська','Буський','Львів',2),
('STV','Львівська','Трускавець','Львів',3),
('STV','Львівська','Стрийський','Львів',2),
('STV','Львівська','Жидачівський','Львів',2),
('STV','Львівська','Дрогобицький','Львів',2),
('STV','Львівська','Радехівський','Львів',2),
('STV','Львівська','Львівський','Львів',1),
('STV','Львівська','Яворівський','Львів',1),
('STV','Львівська','Жовківський','Львів',1),
('STV','Львівська','Бродівський','Львів',2),
('STV','Львівська','Сколівський','Львів',3),
('STV','Львівська','Перемишлянський','Львів',1),
('STV','Львівська','Шептицький','Львів',2),
('STV','Львівська','Сокальський','Львів',2),
('STV','Львівська','Кам''янка-Бузький','Львів',1),
('STV','Львівська','Самбірський','Львів',2),
('STV','Львівська','Городоцький','Львів',1),
('STV','Львівська','Золочівський','Львів',2),
('STV','Львівська','Мостиський','Львів',2),
('STV','Львівська','Турківський','Львів',4),
('STV','Львівська','Старосамбірський','Львів',3),
('STV','Миколаївська','Миколаївський','Одеса',1),
('STV','Одеська','Одеський','Одеса',1),
('STV','Одеська','Овідіопольський','Одеса',2),
('STV','Одеська','Біляївський','Одеса',2),
('STV','Одеська','Лиманський','Одеса',1),
('STV','Одеська','Чорноморськ','Одеса',1),
('STV','Полтавська','Полтавський','Полтава',1),
('STV','Полтавська','Кременчук','Полтава',1),
('STV','Полтавська','Хорольський','Полтава',3),
('STV','Полтавська','Кобеляцький','Полтава',2),
('STV','Полтавська','Лубенський','Полтава',4),
('STV','Полтавська','Зіньківський','Полтава',2),
('STV','Полтавська','Комсомольськ','Полтава',3),
('STV','Полтавська','Гадяцький','Полтава',4),
('STV','Полтавська','Карлівський','Полтава',2),
('STV','Полтавська','Решетилівський','Полтава',1),
('STV','Полтавська','Новосанжарський','Полтава',1),
('STV','Полтавська','Машівський','Полтава',1),
('STV','Полтавська','Кременчуцький','Полтава',1),
('STV','Полтавська','Миргородський','Полтава',3),
('STV','Полтавська','Великобагачанський','Полтава',3),
('STV','Полтавська','Глобинський','Полтава',1),
('STV','Полтавська','Чутівський','Полтава',1),
('STV','Рівненська','Рівненський','Рівне',1),
('STV','Рівненська','Дубенський','Рівне',1),
('STV','Рівненська','Вараський','Рівне',3),
('STV','Рівненська','Костопільський','Рівне',1),
('STV','Рівненська','Сарненський','Рівне',3),
('STV','Рівненська','Гощанський','Рівне',1),
('STV','Рівненська','Радивилівський','Рівне',3),
('STV','Рівненська','Острозький','Рівне',1),
('STV','Рівненська','Рокитнівський','Рівне',4),
('STV','Рівненська','Корецький','Рівне',2),
('STV','Рівненська','Млинівський','Рівне',1),
('STV','Рівненська','Дубровицький','Рівне',3),
('STV','Тернопільська','Тернопільський','Тернопіль',1),
('STV','Тернопільська','Заліщицький','Тернопіль',3),
('STV','Тернопільська','Бучацький','Тернопіль',2),
('STV','Тернопільська','Кременецький','Тернопіль',2),
('STV','Тернопільська','Чортківський','Тернопіль',2),
('STV','Тернопільська','Гусятинський','Тернопіль',3),
('STV','Тернопільська','Теребовлянський','Тернопіль',1),
('STV','Тернопільська','Монастириський','Тернопіль',2),
('STV','Тернопільська','Борщівський','Тернопіль',3),
('STV','Тернопільська','Збаразький','Тернопіль',1),
('STV','Тернопільська','Зборівський','Тернопіль',1),
('STV','Тернопільська','Бережанський','Тернопіль',2),
('STV','Тернопільська','Підгаєцький','Тернопіль',2),
('STV','Тернопільська','Лановецький','Тернопіль',2),
('STV','Тернопільська','Підволочиський','Тернопіль',1),
('STV','Тернопільська','Козівський','Тернопіль',1),
('STV','Харківська','Харківський','Харків',1),
('STV','Харківська','Зміївський','Харків',1),
('STV','Харківська','Лозівський','Харків',3),
('STV','Харківська','Дергачівський','Харків',1),
('STV','Харківська','Нововодолазький','Харків',2),
('STV','Харківська','Богодухівський','Харків',2),
('STV','Харківська','Чугуївський','Харків',1),
('STV','Харківська','Берестинський','Харків',3),
('STV','Хмельницька','Хмельницький','Хмельницький',1),
('STV','Хмельницька','Кам''янець-Подільський','Хмельницький',3),
('STV','Хмельницька','Полонський','Хмельницький',3),
('STV','Хмельницька','Старокостянтинівський','Хмельницький',2),
('STV','Хмельницька','Красилівський','Хмельницький',1),
('STV','Хмельницька','Летичівський','Хмельницький',1),
('STV','Хмельницька','Волочиський','Хмельницький',2),
('STV','Хмельницька','Славутський','Хмельницький',3),
('STV','Хмельницька','Шепетівський','Хмельницький',2),
('STV','Хмельницька','Віньковецький','Хмельницький',2),
('STV','Хмельницька','Нетішин','Хмельницький',3),
('STV','Хмельницька','Деражнянський','Хмельницький',1),
('STV','Хмельницька','Теофіпольський','Хмельницький',2),
('STV','Хмельницька','Старосинявський','Хмельницький',2),
('STV','Хмельницька','Ярмолинецький','Хмельницький',1),
('STV','Хмельницька','Городоцький','Хмельницький',2),
('STV','Хмельницька','Дунаєвецький','Хмельницький',2),
('STV','Черкаська','Черкаський','Черкаси',1),
('STV','Черкаська','Корсунь-Шевченківський','Черкаси',2),
('STV','Черкаська','Уманський','Черкаси',1),
('STV','Черкаська','Звенигородський','Черкаси',2),
('STV','Черкаська','Золотоніський','Черкаси',1),
('STV','Черкаська','Чигиринський','Черкаси',2),
('STV','Черкаська','Христинівський','Черкаси',2),
('STV','Черкаська','Канівський','Черкаси',2),
('STV','Черкаська','Смілянський','Черкаси',1),
('STV','Черкаська','Городищенський','Черкаси',2),
('STV','Чернівецька','Чернівецький','Чернівці',1),
('STV','Чернівецька','Сторожинецький','Чернівці',1),
('STV','Чернівецька','Дністровський','Чернівці',3),
('STV','Чернівецька','Кіцманський','Чернівці',1),
('STV','Чернівецька','Герцаївський','Чернівці',1),
('STV','Чернівецька','Путильський','Чернівці',3),
('STV','Чернівецька','Новоселицький','Чернівці',1),
('STV','Чернівецька','Кельменецький','Чернівці',2),
('STV','Чернівецька','Вижницький','Чернівці',2),
('STV','Чернівецька','Хотинський','Чернівці',2),
('STV','Чернівецька','Сокирянський','Чернівці',3),
('STV','Чернівецька','Глибоцький','Чернівці',1),
('STV','Чернівецька','Заставнівський','Чернівці',1),
('SAV','Київська','Білоцерківський','Біла Церква',1),
('SAV','Київська','Обухівський','Біла Церква',3),
('SAV','Київська','Васильківський','Біла Церква',2),
('SAV','Київська','Тетіївський','Біла Церква',3),
('SAV','Київська','Ставищенський','Біла Церква',2),
('SAV','Київська','Володарський','Біла Церква',2),
('SAV','Київська','Фастівський','Біла Церква',2);
insert into public.stv_branch_directory(name) values ('Львів STV'),('Мукачево STV'),('Ів.-Франківськ STV'),('Рівне STV'),('Луцьк STV'),('Хмельницький STV'),('Вінниця STV'),('Тернопіль STV'),('Чернівці STV'),('Полтава STV'),('Кременчук STV'),('Харків STV'),('Дніпро STV'),('Запоріжжя STV'),('Кривий Ріг STV'),('Черкаси STV'),('Умань STV'),('Одеса STV'),('Миколаїв STV');
