(()=>{
const P=n=>new Intl.NumberFormat('uk-UA',{minimumFractionDigits:0,maximumFractionDigits:3}).format(Number(n)||0);
const css=`
.tt-business{display:inline-flex;margin-top:8px;padding:5px 8px;border-radius:999px;background:var(--soft);color:var(--accent);font-size:11px;font-weight:900}
.tt-metrics{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:11px}
.tt-metric{background:#f7f8fa;border-radius:11px;padding:9px;min-width:0}.tt-metric.full{grid-column:1/-1}.tt-metric span{display:block;color:var(--muted);font-size:10px;font-weight:700;margin-bottom:3px}.tt-metric b{font-size:13px;line-height:1.25;word-break:break-word}
.doc-card-v17{background:#fff;border:1px solid var(--line);border-radius:15px;padding:13px}.doc-card-v17+.doc-card-v17{margin-top:8px}.doc-number{font-size:15px;font-weight:900}.doc-row{display:flex;justify-content:space-between;gap:12px;padding-top:8px;margin-top:8px;border-top:1px solid #eef0f2}.doc-row span{font-size:11px;color:var(--muted)}.doc-row b{font-size:12px;text-align:right;word-break:break-word}
.cost-tt-card{background:#fff;border:1px solid var(--line);border-radius:14px;padding:12px}.cost-tt-card+.cost-tt-card{margin-top:8px}
@media(max-width:650px){.tt-route-head{display:block}.tt-route-head .tag{display:inline-block;margin-top:7px}.tt-card{padding:13px}.tt-grid{display:none!important}.head{align-items:flex-start;flex-wrap:wrap}.route-top{align-items:flex-start}.route-id{font-size:16px}}
`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);

function monday(d){const x=new Date(d+'T12:00:00'),day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);return x.toISOString().slice(0,10)}
function plusDays(d,n){const x=new Date(d+'T12:00:00');x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)}
function dmy(d){const [y,m,dd]=String(d).split('-');return dd&&m?dd+'.'+m:String(d||'')}
function carrierForRoute(r){const a=(D.autoCarriers||[]).find(x=>x.expeditor_name===r.expeditor_name);if(a)return a.auto_carrier;return D.facts.find(x=>x.route_id===r.id)?.carrier_name||''}
function routeCostRows(routeId,carrier=''){return (D.costPoints||[]).filter(x=>x.route_id===routeId&&(!carrier||x.carrier===carrier))}
function isMissingCost(x){return x.effective_cost==null||!x.zone||x.tt_fixed==null||x.pallet_tariff==null}
function knownCost(rows){return rows.reduce((s,x)=>s+(x.effective_cost==null?0:(+x.effective_cost||0)),0)}
function carrierStats(carrier){const rows=(D.costPoints||[]).filter(x=>x.carrier===carrier),routeIds=[...new Set(rows.map(x=>x.route_id))];return{cost:knownCost(rows),tt:rows.length,pal:rows.reduce((s,x)=>s+(+x.pallets||0),0),routes:routeIds.length,missing:rows.filter(isMissingCost).length}}
function fopStats(){const rr=D.routes.filter(r=>/фоп|діден|різун|скіби|скіб/i.test(carrierForRoute(r))),ids=new Set(rr.map(x=>x.id)),pp=D.points.filter(x=>ids.has(x.route_id)),ff=D.facts.filter(x=>ids.has(x.route_id));return{routes:rr.length,tt:pp.length,pal:pp.reduce((s,x)=>s+(+x.pallets||0),0),cost:ff.reduce((s,x)=>s+(+x.tariff||0),0)}}
function costBox(title,s,type,cls=''){return `<div class="cost-card ${cls}" onclick="costDetail('${type}')"><h3>${title}</h3><div class="cost-main">${M(s.cost||0)}</div><div class="cost-meta">${s.routes||0} маршрутів · ${s.tt||0} ТТ<br>${P(s.pal||0)} палет${s.missing?`<br><span class="err">${s.missing} ТТ · Без зони/тарифу</span>`:''}</div></div>`}
function pointDocs(x){
 const r=D.routes.find(z=>z.id===x.route_id);if(!r)return[];
 let raw=D.docs.filter(d=>String(d.route_delivery_id)===String(r.route_delivery_id));
 if(x.customer_id)raw=raw.filter(d=>String(d.customer_id)===String(x.customer_id));
 if(x.location_id){const exact=raw.filter(d=>d.address_id!=null&&String(d.address_id)===String(x.location_id));if(exact.length)raw=exact}
 const map=new Map();
 for(const d of raw){const key=String(d.sale_code||d.operation_code||d.id)+'|'+String(d.customer_id||'')+'|'+String(d.address_id||'');if(!map.has(key))map.set(key,d)}
 return [...map.values()];
}
function pointMeta(x){const a=D.alloc.filter(z=>z.route_point_id===x.id);return{bu:[...new Set(a.map(z=>business(z.business_unit)).filter(Boolean))].join(', '),em:[...new Set(a.map(z=>z.employee_id).filter(Boolean))].join(', ')}}
function pointAddress(x){return pointDocs(x).find(d=>d.delivery_address)?.delivery_address||'Адреса не вказана'}
function metric(label,value,full=false){return `<div class="tt-metric${full?' full':''}"><span>${label}</span><b>${value}</b></div>`}

home=function(){
 const s=sums(),stv=carrierStats('STV'),sav=carrierStats('SAV'),fop=fopStats();
 const courRows=D.manual.filter(x=>x.entry_type==='courier'),repRows=D.manual.filter(x=>x.entry_type==='branch_replenishment');
 const cour={cost:courRows.reduce((a,x)=>a+(+x.expense_amount||0),0),routes:courRows.length,tt:courRows.reduce((a,x)=>a+(+x.points_count||0),0),pal:courRows.reduce((a,x)=>a+(+x.pallets||0),0)};
 const rep={cost:repRows.reduce((a,x)=>a+(+x.expense_amount||0),0),routes:repRows.length,tt:repRows.reduce((a,x)=>a+(+x.points_count||0),0),pal:repRows.reduce((a,x)=>a+(+x.pallets||0),0)};
 const calcCost=fop.cost+stv.cost+sav.cost+cour.cost+rep.cost,byDay={};
 (D.weekRoutes||[]).forEach(r=>{const z=byDay[r.route_date]||(byDay[r.route_date]={routes:0,tt:0,pal:0});z.routes++;z.tt+=+r.total_points||0;z.pal+=+r.total_pallets||0});
 const days=Object.entries(byDay).map(([d,x])=>`<div class="day-card"><span>${dmy(d)}</span><b>${x.tt} ТТ</b><strong class="pal-main">${P(x.pal)} пал.</strong><span>${x.routes} маршрутів</span></div>`).join('');
 view.innerHTML=`<div class="head"><div><h2>Україна · ${dmy(date.value)}</h2><div class="note">Факт ТТ, об’єми та транспортні витрати</div></div><span class="tag">${D.routes.length} маршрутів</span></div>
 <div class="kpis">${K('ТТ',s.tt,'showTT()')}${K('Палети',P(s.pal))}${K('Продажі',M(s.sales))}${K('Витрати',M(calcCost),'showCosts()')}${K('Логістика',s.sales?(calcCost/s.sales*100).toFixed(2)+'%':'—')}${K('1 ТТ',s.tt?M(calcCost/s.tt):'—')}</div>
 <div class="section"><h3>Транспортні витрати</h3><div class="cost-blocks">${costBox('ФОП',fop,'fop')}${costBox('SAV',sav,'sav','sav')}${costBox('STV',stv,'stv','stv')}${costBox('Кур’єрка',cour,'courier')}${costBox('Поповнення філій',rep,'branch')}</div></div>
 <div class="section"><div class="card box"><div class="head"><div><h3 style="margin:0">Поточний тиждень</h3><div class="note">Дані, які вже є в базі</div></div><b>${dmy(monday(date.value))}–${dmy(plusDays(monday(date.value),6))}</b></div><div class="week-strip">${days||'<span class="note">Немає даних</span>'}</div></div></div>`;
};

logistics=function(){
 const cards=D.routes.map(r=>{const f=D.facts.find(x=>x.route_id===r.id)||{},pp=D.points.filter(x=>x.route_id===r.id),c=carrierForRoute(r),zone=/^(STV|SAV)$/.test(c),rows=zone?routeCostRows(r.id,c):[],missing=rows.filter(isMissingCost).length,cost=zone?knownCost(rows):(+f.tariff||0),costText=zone&&missing?'Без зони/тарифу':M(cost);
 return `<div class="route-card click" onclick="routeCard(${r.id})"><div class="route-top"><div><div class="route-id">Маршрут ${E(r.route_delivery_id||r.id)}</div><div class="note">${E(r.expeditor_name||'—')}</div></div><span class="tag">${E(c||'Не визначено')}</span></div><div class="note" style="margin-top:8px">${E(r.warehouse||'—')}</div><div class="route-grid"><div class="route-stat"><span>ТТ</span><b>${pp.length}</b></div><div class="route-stat"><span>Палети</span><b>${P(pp.reduce((s,x)=>s+(+x.pallets||0),0))}</b></div><div class="route-stat"><span>Хвиля</span><b>${E(f.wave||'—')}</b></div><div class="route-stat"><span>Виїзд</span><b>${E(f.departure_time||'—')}</b></div><div class="route-stat"><span>Тариф / вартість</span><b class="${missing?'err':''}">${E(costText)}</b></div><div class="route-stat"><span>Статус тарифу</span><b class="${missing?'err':'good'}">${missing?missing+' ТТ · Без зони/тарифу':'OK'}</b></div></div>${zone&&missing?`<div class="note" style="margin-top:8px">Відома частина: ${M(cost)}</div>`:''}</div>`}).join('');
 view.innerHTML=`<div class="head"><div><h2>Маршрути</h2><div class="note">Натисни маршрут → його ТТ → конкретна ТТ → документи</div></div><span class="tag">${D.routes.length}</span></div><div class="route-list">${cards||'<div class="card box">Немає маршрутів</div>'}</div>`;
};

showTT=function(filterIds=null){
 const points=filterIds?D.points.filter(x=>filterIds.includes(x.route_id)):D.points,routeIds=[...new Set(points.map(x=>x.route_id))];
 const groups=routeIds.map(rid=>{const r=D.routes.find(z=>z.id===rid),pp=points.filter(x=>x.route_id===rid),pal=pp.reduce((s,x)=>s+(+x.pallets||0),0),cards=pp.map(x=>{const m=pointMeta(x),docs=pointDocs(x);return `<div class="tt-card" onclick="pointCard(${x.id})"><div class="tt-name">${E(x.customer_name||'—')}</div><div class="tt-address">${E(pointAddress(x))}</div><div class="tt-business">${E(m.bu||'Бізнес не вказано')}</div><div class="tt-metrics">${metric('Продажі',String(docs.length))}${metric('Палети',P(x.pallets))}${metric('Вага',P(x.weight)+' кг')}${metric('Сума',M(x.order_amount))}${metric('ТП / EmployeeID',E(m.em||'—'),true)}</div></div>`}).join('');return `<div class="tt-route"><div class="tt-route-head"><div><div class="route-id">Маршрут ${E(r?.route_delivery_id||rid)}</div><div class="note">${E(r?.expeditor_name||'—')} · ${E(r?.warehouse||'—')}</div></div><span class="tag">${pp.length} ТТ · ${P(pal)} пал.</span></div><div class="tt-list">${cards}</div></div>`}).join('');
 view.innerHTML=`<button class="btn back" onclick="go('home')">← Назад</button><div class="head"><div><h2>Торгові точки · ${points.length}</h2><div class="note">Дата → Маршрут → ТТ → Документи</div></div></div>${groups||'<div class="card box">Немає ТТ</div>'}`;
};

pointCard=function(id){
 const x=D.points.find(z=>z.id===id);if(!x)return;const r=D.routes.find(z=>z.id===x.route_id),docs=pointDocs(x),m=pointMeta(x);
 const docsHtml=docs.map(d=>`<div class="doc-card-v17"><div class="doc-number">№ ${E(d.sale_code||d.operation_code||'—')}</div><div class="doc-row"><span>Дата</span><b>${E(d.document_date||'—')}</b></div><div class="doc-row"><span>Сума</span><b>${M(d.order_amount)}</b></div><div class="doc-row"><span>Бізнес</span><b>${E(business(d.business_unit)||'—')}</b></div><div class="doc-row"><span>EmployeeID</span><b>${E(d.employee_id||'—')}</b></div></div>`).join('');
 view.innerHTML=`<button class="btn back" onclick="showTT([${x.route_id}])">← ТТ маршруту</button><div class="route-card section"><div class="label">Торгова точка</div><h2 style="margin:5px 0 6px">${E(x.customer_name||'—')}</h2><div class="tt-address">${E(pointAddress(x))}</div><div class="tt-business">${E(m.bu||'Бізнес не вказано')}</div><div class="tt-metrics">${metric('Маршрут',E(r?.route_delivery_id||'—'))}${metric('Склад',E(r?.warehouse||'—'))}${metric('Палети',P(x.pallets))}${metric('Вага',P(x.weight)+' кг')}${metric('Продажі',String(docs.length))}${metric('Сума',M(x.order_amount))}${metric('ТП / EmployeeID',E(m.em||'—'),true)}</div></div><h3>Документи · ${docs.length}</h3><div>${docsHtml||'<div class="card box">Документів не знайдено</div>'}</div>`;
};

routeCard=function(id){
 const r=D.routes.find(x=>x.id===id);if(!r)return;const f=D.facts.find(x=>x.route_id===id)||{},pp=D.points.filter(x=>x.route_id===id),c=carrierForRoute(r),rows=/^(STV|SAV)$/.test(c)?routeCostRows(id,c):[],missing=rows.filter(isMissingCost).length,cost=rows.length?knownCost(rows):(+f.tariff||0);
 view.innerHTML=`<button class="btn back" onclick="logistics()">← Маршрути</button><div class="route-card section"><div class="label">Маршрут</div><h2>${E(r.route_delivery_id||r.id)}</h2><div class="note">${E(r.expeditor_name||'—')} · ${E(r.warehouse||'—')}</div><div class="route-grid"><div class="route-stat"><span>ТТ</span><b>${pp.length}</b></div><div class="route-stat"><span>Палети</span><b>${P(pp.reduce((s,x)=>s+(+x.pallets||0),0))}</b></div><div class="route-stat"><span>Перевізник</span><b>${E(c||'—')}</b></div><div class="route-stat"><span>Хвиля</span><b>${E(f.wave||'—')}</b></div><div class="route-stat"><span>Виїзд</span><b>${E(f.departure_time||'не внесено')}</b></div><div class="route-stat"><span>Вартість</span><b class="${missing?'err':''}">${missing?'Без зони/тарифу':M(cost)}</b></div></div>${missing?`<div class="note" style="margin-top:8px">${missing} ТТ без зони/тарифу · відома частина ${M(cost)}</div>`:''}<button class="btn" style="margin-top:12px" onclick="showTT([${id}])">Відкрити ${pp.length} ТТ</button>${rows.length?` <button class="btn back" style="margin-top:12px" onclick="costRouteDetail(${id},'${E(c)}')">Розрахунок ${E(c)}</button>`:''}</div>`;
};

costDetail=function(type){
 if(type==='stv'||type==='sav'){const carrier=type.toUpperCase(),rows=(D.costPoints||[]).filter(x=>x.carrier===carrier),by={};rows.forEach(x=>{const z=by[x.route_id]||(by[x.route_id]={tt:0,pal:0,cost:0,missing:0});z.tt++;z.pal+=+x.pallets||0;if(isMissingCost(x))z.missing++;if(x.effective_cost!=null)z.cost+=+x.effective_cost||0});const html=Object.entries(by).map(([rid,x])=>{const r=D.routes.find(q=>q.id==rid),price=x.missing?'Без зони/тарифу':M(x.cost);return `<div class="route-card" onclick="costRouteDetail(${rid},'${carrier}')"><div class="route-top"><b>${E(r?.route_delivery_id||rid)}</b><b class="${x.missing?'err':''}">${E(price)}</b></div><div class="cost-meta">${x.tt} ТТ · ${P(x.pal)} палет${x.missing?` · <span class="err">${x.missing} без зони/тарифу</span><br>Відома частина: ${M(x.cost)}`:''}</div></div>`}).join('');view.innerHTML=`<div class="head"><div><h2>${carrier}</h2><div class="note">Кожна ТТ: фіксована ставка + палети × тариф зони. Потім сума до маршруту.</div></div><button class="btn back" onclick="home()">Назад</button></div><div class="route-list">${html||'<div class="card box">Немає даних</div>'}</div>`;return}
 if(type==='fop'){const rr=D.routes.filter(r=>/фоп|діден|різун|скіби|скіб/i.test(carrierForRoute(r)));view.innerHTML=`<div class="head"><h2>ФОП</h2><button class="btn back" onclick="home()">Назад</button></div><div class="route-list">${rr.map(r=>`<div class="route-card" onclick="routeCard(${r.id})"><b>${E(r.route_delivery_id||r.id)}</b><div class="note">${E(carrierForRoute(r)||'—')} · ${E(r.expeditor_name||'—')}</div></div>`).join('')||'<div class="card box">Немає внесених тарифів ФОП за дату</div>'}</div>`;return}
 const rows=D.manual.filter(x=>type==='courier'?x.entry_type==='courier':x.entry_type==='branch_replenishment');view.innerHTML=`<div class="head"><h2>${type==='courier'?'Кур’єрка':'Поповнення філій'}</h2><button class="btn back" onclick="home()">Назад</button></div><div class="route-list">${rows.map(x=>`<div class="route-card"><div class="route-top"><b>${E(x.carrier_name||x.receiver_branch||'Запис')}</b><b>${M(x.expense_amount||0)}</b></div><div class="cost-meta">${P(x.pallets||0)} палет · ${E(x.comment||'')}</div></div>`).join('')||'<div class="card box">Немає записів за дату</div>'}</div>`;
};

costRouteDetail=function(routeId,carrier){
 const r=D.routes.find(x=>x.id==routeId),rows=routeCostRows(+routeId,carrier),html=rows.map((x,i)=>{const miss=isMissingCost(x),formula=miss?'Без зони/тарифу':`${M(x.tt_fixed)} + ${P(x.pallets)} × ${M(x.pallet_tariff)} = ${M(x.effective_cost)}`;return `<div class="cost-tt-card"><div class="route-top"><b>ТТ ${i+1}</b><b class="${miss?'err':'good'}">${miss?'Без зони/тарифу':M(x.effective_cost)}</b></div><div class="cost-meta">Зона: ${E(x.zone||'—')} · Палети: ${P(x.pallets)}<br>${formula}</div></div>`}).join('');view.innerHTML=`<button class="btn back" onclick="costDetail('${String(carrier).toLowerCase()}')">← ${E(carrier)}</button><h2>Маршрут ${E(r?.route_delivery_id||routeId)}</h2><div class="note">Розрахунок по кожній фізичній ТТ з transport_point_costs_v1</div><div class="section">${html||'<div class="card box">Немає розрахунку</div>'}</div>`;
};

branchTiles=function(){const m={};D.routes.forEach(r=>{const k=branch(r.warehouse),pts=D.points.filter(x=>x.route_id===r.id);m[k]??={tt:0,p:0,s:0};m[k].tt+=pts.length;m[k].p+=pts.reduce((a,x)=>a+(+x.pallets||0),0);m[k].s+=pts.reduce((a,x)=>a+(+x.order_amount||0),0)});return'<h3>Філії</h3><div class="tiles">'+Object.entries(m).sort((a,b)=>b[1].s-a[1].s).map(([n,x])=>'<div class="card tile" onclick="showBranch(\''+E(n)+'\')"><div class="label">'+E(n)+'</div><b>'+x.tt+' ТТ</b><div>'+P(x.p)+' пал · '+M(x.s)+'</div></div>').join('')+'</div>'};
businessTiles=function(){const m={};D.alloc.forEach(x=>{const k=business(x.business_unit);m[k]??={tt:new Set(),p:0,s:0,c:0};m[k].tt.add(x.route_point_id);m[k].p+=+x.pallets||0;m[k].s+=+x.order_amount||0;m[k].c+=+x.allocated_delivery_cost||0});return'<h3>Бізнеси</h3><div class="tiles">'+Object.entries(m).sort((a,b)=>b[1].s-a[1].s).map(([n,x])=>'<div class="card tile"><div class="label">'+E(n)+'</div><b>'+x.tt.size+' ТТ</b><div>'+P(x.p)+' пал · '+M(x.s)+'</div><div class="note">Витрати: '+M(x.c)+'</div></div>').join('')+'</div>'};
manualRows=function(type){const a=type?D.manual.filter(x=>x.entry_type===type):D.manual;if(!a.length)return'<p class="note">Записів за дату немає.</p>';return'<div class="card tablecard"><table class="table"><thead><tr><th>Тип</th><th>Відправник</th><th>Отримувач</th><th>Перевізник</th><th>Палети</th><th>ТТ</th><th>Витрати</th></tr></thead><tbody>'+a.map(x=>'<tr><td>'+E(x.entry_type==='courier'?'Кур’єрка':'Поповнення')+'</td><td>'+E(x.sender_warehouse||'—')+'</td><td>'+E(x.receiver_branch||'—')+'</td><td>'+E(x.carrier_name||'—')+'</td><td>'+P(x.pallets)+'</td><td>'+N(x.points_count)+'</td><td>'+M(x.expense_amount)+'</td></tr>').join('')+'</tbody></table></div>'};
})();
