-- Transport Report TS v4 business logic foundation
-- Run after existing v3 schema.

create table if not exists public.transport_carriers (
  id bigint generated by default as identity primary key,
  name text not null unique,
  carrier_type text not null default 'route' check (carrier_type in ('route','stv','sav','ts_plus')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.transport_carriers(name, carrier_type) values
 ('ФОП Діденко','route'),('ФОП Різун','route'),('ПП Лозицький','route'),('ФОП Скібіцька','route'),
 ('ТОВ Рабен','route'),('ТОВ ФМ Лоджистік','route'),('ТОВ Корпоратура','route'),('ТОВ ТС ПЛЮС','ts_plus'),
 ('STV','stv'),('SAV','sav') on conflict (name) do nothing;

create table if not exists public.transport_drivers (
 id bigint generated by default as identity primary key,
 full_name text not null unique,
 active boolean not null default true,
 created_at timestamptz not null default now()
);

create table if not exists public.transport_vehicles (
 id bigint generated by default as identity primary key,
 brand text not null,
 plate_number text not null unique,
 active boolean not null default true,
 created_at timestamptz not null default now()
);

create table if not exists public.expeditor_defaults (
 expeditor_name text primary key,
 driver_id bigint references public.transport_drivers(id),
 vehicle_id bigint references public.transport_vehicles(id),
 updated_at timestamptz not null default now()
);

create table if not exists public.transport_waves (
 id bigint generated by default as identity primary key,
 name text not null unique,
 uses_vt boolean not null default false,
 active boolean not null default true
);
insert into public.transport_waves(name,uses_vt) values
 ('24',false),('48',false),('Мережа',false),('Пекарня',true),('Пекарня Заморозка',true),('Фреш',true),('ОЗ',false),('Повернення',false)
on conflict(name) do update set uses_vt=excluded.uses_vt;

create table if not exists public.extra_point_catalog (
 id bigint generated by default as identity primary key,
 point_type text not null check(point_type in ('vt','extra_tt')),
 name text not null,
 active boolean not null default true,
 unique(point_type,name)
);
insert into public.extra_point_catalog(point_type,name) values
 ('vt','Стоянка'),('vt','Палладіна'),('vt','Дмитрівська'),('vt','Філатова'),('vt','Здановської'),('vt','Верхогляда'),('vt','Мокра'),('vt','Голосіївська'),('vt','Бажана'),('vt','Маккейна'),
 ('extra_tt','ТТ з Бару'),('extra_tt','Переміщення на офіс') on conflict do nothing;

create table if not exists public.route_extra_points (
 id bigint generated by default as identity primary key,
 route_id bigint not null references public.routes(id) on delete cascade,
 point_type text not null check(point_type in ('vt','extra_tt')),
 name text not null,
 created_by uuid references auth.users(id),
 created_at timestamptz not null default now(),
 unique(route_id,point_type,name)
);

alter table public.route_facts add column if not exists delivered_points integer;
alter table public.route_facts add column if not exists departure_time time;
alter table public.route_facts add column if not exists tariff_group_id uuid;
alter table public.route_facts add column if not exists original_tariff numeric(14,2);
alter table public.route_facts add column if not exists corrected_tariff numeric(14,2);
alter table public.route_facts add column if not exists correction_reason text;

create table if not exists public.expeditor_auto_carrier (
 expeditor_name text primary key,
 auto_carrier text not null check(auto_carrier in ('STV','SAV')),
 active boolean not null default true,
 updated_at timestamptz not null default now()
);

create table if not exists public.delivery_zones (
 id bigint generated by default as identity primary key,
 carrier text not null check(carrier in ('STV','SAV')),
 region text,
 district text not null,
 distance_km numeric(10,2),
 zone integer not null check(zone between 1 and 5),
 active boolean not null default true,
 unique(carrier,district)
);

create table if not exists public.monthly_zone_tariffs (
 id bigint generated by default as identity primary key,
 carrier text not null check(carrier in ('STV','SAV')),
 month date not null,
 tt_fixed numeric(14,2) not null,
 zone1 numeric(14,2) not null,
 zone2 numeric(14,2) not null,
 zone3 numeric(14,2) not null,
 zone4 numeric(14,2) not null,
 zone5 numeric(14,2) not null,
 fuel_avg numeric(14,2),
 created_by uuid references auth.users(id),
 updated_at timestamptz not null default now(),
 unique(carrier,month)
);

-- Current reference tariffs supplied for August 2026.
insert into public.monthly_zone_tariffs(carrier,month,tt_fixed,zone1,zone2,zone3,zone4,zone5) values
 ('SAV','2026-08-01',82.20,510.00,1130.00,1620.00,1940.00,2140.00),
 ('STV','2026-08-01',105.65,572.76,1320.51,1893.26,2275.10,2641.01)
on conflict(carrier,month) do nothing;

create table if not exists public.point_tariff_overrides (
 id bigint generated by default as identity primary key,
 route_point_id bigint not null references public.route_points(id) on delete cascade,
 carrier text not null check(carrier in ('STV','SAV')),
 original_zone integer,
 corrected_zone integer check(corrected_zone between 1 and 5),
 calculated_cost numeric(14,2),
 corrected_cost numeric(14,2),
 reason text,
 corrected_by uuid references auth.users(id),
 corrected_at timestamptz not null default now(),
 unique(route_point_id,carrier)
);

create table if not exists public.ts_plus_monthly_costs (
 id bigint generated by default as identity primary key,
 month date not null,
 business text not null,
 amount numeric(14,2) not null,
 created_by uuid references auth.users(id),
 updated_at timestamptz not null default now(),
 unique(month,business)
);

-- Access: authenticated app users can read directories; route editing remains controlled by existing route RLS.
grant select on public.transport_carriers, public.transport_drivers, public.transport_vehicles, public.expeditor_defaults, public.transport_waves, public.extra_point_catalog, public.expeditor_auto_carrier, public.delivery_zones, public.monthly_zone_tariffs to authenticated;
grant select,insert,update on public.route_extra_points to authenticated;
grant select,insert,update on public.point_tariff_overrides, public.ts_plus_monthly_costs to authenticated;
grant usage,select on all sequences in schema public to authenticated;

-- STV/SAV point cost formula used by the app/backend:
-- cost = tt_fixed + (zone_rate * SUM(material_pallets of all documents belonging to one physical TT)).
-- Multiple invoices at one physical TT remain one TT.
