(()=>{
let docs=JSON.parse(localStorage.getItem('tc_retail_docs_v2')||'[]');const selected=new Set();
const money=n=>new Intl.NumberFormat('uk-UA',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(n)||0);const rnd=(n,p=3)=>Math.round((Number(n)||0)*10**p)/10**p;
function save(){localStorage.setItem('tc_retail_docs_v2',JSON.stringify(docs))}
function modal(html){let m=document.getElementById('ops-modal');if(!m){m=document.createElement('div');m.id='ops-modal';document.body.append(m)}m.innerHTML=`<div class="ops-backdrop"></div><div class="ops-dialog">${html}<button class="ops-close">Закрити</button></div>`;m.className='open';m.querySelector('.ops-backdrop').onclick=m.querySelector('.ops-close').onclick=()=>m.className='';return m}
function loadXLSX(cb){if(window.XLSX)return cb();const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js';s.onload=cb;s.onerror=()=>alert('Не вдалося завантажити модуль Excel. Перевірте інтернет.');document.head.append(s)}
function parseDate(link){const m=String(link||'').match(/від\s+(\d{2}\.\d{2}\.\d{4})/i);return m?m[1]:''}
function normStore(s){return String(s||'').replace(/^Склад\s*№?\d*\s*магазин\s*/i,'').trim()||String(s||'').trim()}
function parseRows(rows){let warehouse='';const out=[];let cur=null;for(let i=0;i<rows.length;i++){const r=rows[i]||[];if(!r.some(v=>v!==null&&v!==undefined&&v!==''))continue;
 if(typeof r[6]==='string'&&/^Склад\s/i.test(r[6])&&!/^Лист відбору/i.test(r[6])){warehouse=r[6];continue}
 const isDoc=(typeof r[6]==='string'&&/^Лист відбору/i.test(r[6]))||((typeof r[1]==='number'||/^\d+$/.test(String(r[1]||'')))&&typeof r[2]==='string'&&/^Склад/i.test(r[2]));
 if(isDoc){cur={id:String(r[1]),date:parseDate(r[6]),store:normStore(r[2]),storeRaw:String(r[2]||''),warehouse,sourcePallets:Number(r[3])||0,sourceWeight:Number(r[4])||0,qty:Number(r[8])||0,amount:Number(r[9])||0,fact:'',route:'',status:'Новий',lines:[]};out.push(cur);continue}
 if(cur&&(typeof r[1]==='number'||/^\d{6,}$/.test(String(r[1]||'')))&&typeof r[6]==='string'){
  const casesPal=Number(r[3])||0, unitsCase=Number(r[4])||0, unitWeight=Number(r[5])||0, qty=Number(r[8])||0, amount=Number(r[9])||0;
  const pallets=casesPal>0&&unitsCase>0?qty/unitsCase/casesPal:0;
  cur.lines.push({sku:String(r[1]),barcode:String(r[2]||''),casesPal,unitsCase,unitWeight,name:r[6],volume:String(r[7]||''),qty,amount,pallets:rnd(pallets,6),weight:rnd(qty*unitWeight,3)});
 }}
 out.forEach(d=>{d.calc=rnd(d.lines.reduce((a,x)=>a+x.pallets,0),3);d.calcWeight=rnd(d.lines.reduce((a,x)=>a+x.weight,0),3);d.key=[d.id,d.date,d.storeRaw].join('|');d.hash=JSON.stringify([d.amount,d.qty,d.calc,d.calcWeight,d.lines.map(x=>[x.sku,x.qty,x.amount])])});return out}
function preview(incoming,fileName){const old=new Map(docs.map(d=>[d.key,d]));let n=0,same=0,changed=0;const rows=incoming.map(d=>{const e=old.get(d.key);let state='Новий';if(!e){n++}else if(e.hash===d.hash){same++;state='Без змін'}else{changed++;state='Змінено'}return {d,e,state}});const m=modal(`<h2>Перевірка імпорту</h2><p><b>${fileName}</b> · ${incoming.length} документів</p><div class="ops-import"><span class="new">${n} нових</span><span>${same} без змін</span><span class="chg">${changed} змінених</span></div><p class="ops-hint">Палети з файлу системи не використовуються як розрахункові. Сайт перераховує їх: кількість ÷ шт./кейс ÷ кейсів/палету по кожній позиції.</p><table><thead><tr><th>Документ</th><th>Магазин</th><th>Палети системи</th><th>Наш розрахунок</th><th>Вага системи</th><th>Розрах. вага</th><th>Стан</th></tr></thead><tbody>${rows.map(x=>`<tr><td>№ ${x.d.id}</td><td>${x.d.store}</td><td>${rnd(x.d.sourcePallets)}</td><td><b>${x.d.calc}</b></td><td>${rnd(x.d.sourceWeight)} кг</td><td>${x.d.calcWeight} кг</td><td>${x.state}</td></tr>`).join('')}</tbody></table><div class="ops-actions"><button class="ops-choice" data-import="skip">Імпортувати нові, існуючі пропустити</button><button class="ops-choice" data-import="update">Імпортувати нові та оновити змінені</button><button class="ops-choice secondary" data-import="cancel">Не завантажувати файл</button></div>`);
 m.querySelector('[data-import="cancel"]').onclick=()=>m.className='';m.querySelector('[data-import="skip"]').onclick=()=>commit(rows,false,m);m.querySelector('[data-import="update"]').onclick=()=>commit(rows,true,m)}
function commit(rows,update,m){const map=new Map(docs.map(d=>[d.key,d]));rows.forEach(({d,state})=>{if(state==='Новий')map.set(d.key,d);else if(state==='Змінено'&&update){const prev=map.get(d.key);if(!prev||!['routed','ttn_created','dispatched','delivered'].includes(prev.workflowStatus||''))map.set(d.key,{...d,fact:prev?.fact||'',route:prev?.route||''})}});docs=[...map.values()];save();m.className='';render()}
function chooseFile(){loadXLSX(()=>{const input=document.createElement('input');input.type='file';input.accept='.xlsx,.xls';input.onchange=async()=>{const f=input.files[0];if(!f)return;try{const wb=XLSX.read(await f.arrayBuffer(),{type:'array',cellDates:false});const name=wb.SheetNames.includes('TDSheet')?'TDSheet':wb.SheetNames[0];const rows=XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,raw:true,defval:null});const incoming=parseRows(rows);if(!incoming.length)return alert('Документи у файлі не знайдені. Очікується первинний системний формат TDSheet.');preview(incoming,f.name)}catch(e){console.error(e);alert('Помилка читання Excel: '+e.message)}};input.click()})}
function detail(d){const vat=d.amount/6,ex=d.amount-vat;modal(`<h2>Документ № ${d.id}</h2><div class="ops-meta"><b>${d.store}</b><span>Дата: ${d.date||'—'}</span><span>Склад: ${d.warehouse||'—'}</span><span>Вага системи: ${d.sourceWeight} кг</span><span>Розрах. вага: ${d.calcWeight} кг</span><span>Палети системи: ${d.sourcePallets}</span><span><b>Палети розрах.: ${d.calc}</b></span><span>Палети факт: ${d.fact||'—'}</span><span>Без ПДВ: ${money(ex)} грн</span><span>ПДВ: ${money(vat)} грн</span><span>З ПДВ: ${money(d.amount)} грн</span></div><table><thead><tr><th>Артикул</th><th>ШК</th><th>Номенклатура</th><th>К-ть</th><th>Шт/кейс</th><th>Кейс/пал</th><th>Палети</th><th>Вага</th><th>Сума</th></tr></thead><tbody>${d.lines.map(x=>`<tr><td>${x.sku}</td><td>${x.barcode}</td><td>${x.name}<small>${x.volume}</small></td><td>${x.qty}</td><td>${x.unitsCase}</td><td>${x.casesPal}</td><td><b>${rnd(x.pallets,3)}</b></td><td>${x.weight} кг</td><td>${money(x.amount)}</td></tr>`).join('')}</tbody></table>`)}
function action(type){const a=docs.filter(d=>selected.has(d.key));if(!a.length)return alert('Оберіть хоча б один документ');if(type==='ticket')modal(`<h2>Талон комплектації</h2><p>Вибрано ${a.length} документів для ${new Set(a.map(x=>x.store)).size} магазинів.</p><p>${a.map(x=>'№ '+x.id+' — '+x.store+' — '+x.calc+' пал.').join('<br>')}</p>`);else modal(`<h2>Побудова маршруту</h2><p>Вибрано ${a.length} документів, ${rnd(a.reduce((s,x)=>s+x.calc,0),3)} розрахункових палет.</p><button class="ops-choice">Додати до існуючого маршруту</button><button class="ops-choice">Створити новий маршрут</button>`)}
function render(){let host=document.getElementById('ops-documents');if(!host){host=document.createElement('section');host.id='ops-documents';host.className='card ops-card';document.querySelector('.content').prepend(host)}host.innerHTML=`<div class="ops-head"><div><b>Документи / замовлення</b><small>${docs.length?docs.length+' документів із первинних системних файлів':'Завантажте первинний Excel із системи (TDSheet)'}</small></div><div><button data-act="ticket">Талон комплектації</button><button data-act="route">Побудувати маршрут</button><button data-act="import">Завантажити Excel</button></div></div>${docs.length?`<table><thead><tr><th></th><th>Документ</th><th>Магазин</th><th>Сума з ПДВ</th><th>Вага</th><th>Палети системи</th><th>Палети розр.</th><th>Палети факт</th><th>Маршрут</th><th>Статус</th></tr></thead><tbody>${docs.map(d=>`<tr><td><input type="checkbox" data-id="${d.key}" ${selected.has(d.key)?'checked':''}></td><td><button class="ops-link" data-doc="${d.key}">№ ${d.id}</button><small>${d.date}</small></td><td><b>${d.store}</b><small>${d.warehouse}</small></td><td>${money(d.amount)}</td><td>${d.calcWeight} кг</td><td class="ops-source">${rnd(d.sourcePallets)}</td><td><b>${d.calc}</b></td><td><input class="ops-fact" data-fact="${d.key}" type="number" min="0" step="0.01" value="${d.fact||''}"></td><td>${d.route||'Не призначено'}</td><td><span class="tag gray">${d.status}</span></td></tr>`).join('')}</tbody></table>`:`<div class="ops-empty"><b>Реєстр порожній</b><span>Натисніть «Завантажити Excel» та оберіть первинний файл, який вивантажено із системи.</span><button data-empty-import>Завантажити первинний Excel</button></div>`}`;
host.querySelectorAll('[data-id]').forEach(x=>x.onchange=()=>x.checked?selected.add(x.dataset.id):selected.delete(x.dataset.id));host.querySelectorAll('[data-doc]').forEach(x=>x.onclick=()=>detail(docs.find(d=>d.key===x.dataset.doc)));host.querySelectorAll('[data-fact]').forEach(x=>x.onchange=()=>{docs.find(d=>d.key===x.dataset.fact).fact=x.value;save()});host.querySelector('[data-act="ticket"]').onclick=()=>action('ticket');host.querySelector('[data-act="route"]').onclick=()=>action('route');host.querySelector('[data-act="import"]').onclick=chooseFile;host.querySelector('[data-empty-import]')?.addEventListener('click',chooseFile)}
function css(){const s=document.createElement('style');s.textContent=`.ops-card{margin-bottom:14px;overflow:auto}.ops-head{display:flex;justify-content:space-between;align-items:center;padding:14px 16px;min-width:900px}.ops-head>div:first-child{display:flex;flex-direction:column;gap:3px}.ops-head small,.ops-dialog small{display:block;opacity:.55}.ops-head button,.ops-choice,.ops-empty button{background:#6f1730;color:#fff;border:1px solid #9c3450;border-radius:8px;padding:8px 11px;margin-left:7px;cursor:pointer}.ops-link{background:none;border:0;color:#e6a0b1;font-weight:700;cursor:pointer}.ops-fact{width:65px;background:#17191e;border:1px solid #3b3d44;color:#fff;border-radius:6px;padding:5px}.ops-source{opacity:.55}#ops-modal{display:none}#ops-modal.open{display:block;position:fixed;inset:0;z-index:9999}.ops-backdrop{position:absolute;inset:0;background:#000c}.ops-dialog{position:relative;margin:5vh auto;background:#17191e;border:1px solid #49323a;border-radius:14px;width:min(1180px,94vw);max-height:88vh;overflow:auto;padding:22px;color:#eee}.ops-meta{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;background:#111318;padding:12px;border-radius:10px;margin-bottom:15px}.ops-dialog table{width:100%;border-collapse:collapse;margin-bottom:15px}.ops-dialog th,.ops-dialog td{padding:8px;border-bottom:1px solid #303238;text-align:left}.ops-close{background:#333740;color:#fff;border:0;border-radius:7px;padding:8px 14px}.ops-choice{display:block;margin:10px 0;width:330px}.ops-choice.secondary{background:#292c33;border-color:#41444c}.ops-hint{opacity:.7}.ops-import{display:flex;gap:12px;flex-wrap:wrap;margin:15px 0}.ops-import span{padding:8px 10px;border:1px solid #3b3d44;border-radius:7px}.ops-import .new{border-color:#2e7d58}.ops-import .chg{border-color:#a06b2d}.ops-empty{padding:35px;text-align:center;display:flex;flex-direction:column;gap:10px;align-items:center}.ops-empty span{opacity:.6}.ops-empty button{margin:5px 0 0}.ops-actions{margin:16px 0}@media(max-width:1000px){.ops-meta{grid-template-columns:1fr 1fr}}`;document.head.append(s)}
css();render();
})();