(()=>{
const docs=[
 {id:'7469',date:'15.09.2026',store:'WT Палладіна',address:'просп. Академіка Палладіна',warehouse:'Розумовського 27',ex:42180,weight:386.4,calc:1.12,fact:'',status:'Новий',route:'',lines:[['AL-1001','Вино позиція 1',48,6,10,72.50,3480],['AL-1002','Вино позиція 2',120,6,10,84.20,10104],['AL-1003','Напій позиція 3',96,12,8,64.10,6153.6]]},
 {id:'7470',date:'15.09.2026',store:'WT Бажана',address:'просп. Миколи Бажана',warehouse:'Розумовського 27',ex:36750,weight:324.8,calc:.94,fact:'',status:'Новий',route:'',lines:[['AL-1101','Вино позиція 4',72,6,10,91.00,6552],['AL-1102','Напій позиція 5',144,12,8,55.00,7920]]},
 {id:'7471',date:'15.09.2026',store:'WT Соборності',address:'просп. Соборності',warehouse:'Розумовського 27',ex:58420,weight:512.2,calc:1.46,fact:'',status:'Новий',route:'',lines:[['AL-1201','Вино позиція 6',180,6,10,76.00,13680],['AL-1202','Напій позиція 7',96,12,8,69.00,6624]]}
];
const money=n=>new Intl.NumberFormat('uk-UA',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n);
const selected=new Set();
function modal(html){let m=document.getElementById('ops-modal');if(!m){m=document.createElement('div');m.id='ops-modal';document.body.append(m)}m.innerHTML=`<div class="ops-backdrop"></div><div class="ops-dialog">${html}<button class="ops-close">Закрити</button></div>`;m.className='open';m.querySelector('.ops-backdrop').onclick=m.querySelector('.ops-close').onclick=()=>m.className=''}
function detail(d){const vat=d.ex*.2,inc=d.ex+vat;modal(`<h2>Документ № ${d.id}</h2><div class="ops-meta"><b>${d.store}</b><span>${d.address}</span><span>Склад: ${d.warehouse}</span><span>Вага: ${d.weight} кг</span><span>Палети: ${d.calc} розр. / ${d.fact||'—'} факт</span><span>Без ПДВ: ${money(d.ex)} грн</span><span>ПДВ: ${money(vat)} грн</span><span>З ПДВ: ${money(inc)} грн</span></div><table><thead><tr><th>Код</th><th>Номенклатура</th><th>К-ть</th><th>Шт/кейс</th><th>Кейс/пал</th><th>Палети</th><th>Ціна</th><th>Сума</th></tr></thead><tbody>${d.lines.map(x=>`<tr><td>${x[0]}</td><td>${x[1]}</td><td>${x[2]}</td><td>${x[3]}</td><td>${x[4]}</td><td>${(x[2]/x[3]/x[4]).toFixed(2)}</td><td>${money(x[5])}</td><td>${money(x[6])}</td></tr>`).join('')}</tbody></table>`)}
function action(type){const a=docs.filter(d=>selected.has(d.id));if(!a.length)return alert('Оберіть хоча б один документ');if(type==='ticket')modal(`<h2>Талон комплектації</h2><p>Буде сформовано з ${a.length} документів для ${new Set(a.map(x=>x.store)).size} магазинів.</p><p>${a.map(x=>'№ '+x.id+' — '+x.store).join('<br>')}</p>`);if(type==='route')modal(`<h2>Побудова маршруту</h2><p>Вибрано ${a.length} документів.</p><button class="ops-choice">Додати до поточного маршруту</button><button class="ops-choice">Створити новий маршрут</button><p class="ops-hint">Система запропонує маршрут за магазинами-отримувачами. Новий маршрут можна створити і без документів.</p>`)}
function render(){let host=document.getElementById('ops-documents');if(!host){host=document.createElement('section');host.id='ops-documents';host.className='card ops-card';document.querySelector('.content').prepend(host)}host.innerHTML=`<div class="ops-head"><div><b>Документи / замовлення</b><small>Тестовий робочий реєстр</small></div><div><button data-act="ticket">Талон комплектації</button><button data-act="route">Побудувати маршрут</button><button data-act="import">Завантажити Excel</button></div></div><table><thead><tr><th></th><th>Документ</th><th>Магазин</th><th>Без ПДВ</th><th>ПДВ</th><th>Вага</th><th>Палети розр.</th><th>Палети факт</th><th>Маршрут</th><th>Статус</th></tr></thead><tbody>${docs.map(d=>`<tr><td><input type="checkbox" data-id="${d.id}" ${selected.has(d.id)?'checked':''}></td><td><button class="ops-link" data-doc="${d.id}">№ ${d.id}</button></td><td><b>${d.store}</b><small>${d.address}</small></td><td>${money(d.ex)}</td><td>${money(d.ex*.2)}</td><td>${d.weight} кг</td><td>${d.calc}</td><td><input class="ops-fact" data-fact="${d.id}" type="number" min="0" step="0.01" value="${d.fact}"></td><td>${d.route||'Не призначено'}</td><td><span class="tag gray">${d.status}</span></td></tr>`).join('')}</tbody></table>`;
host.querySelectorAll('[data-id]').forEach(x=>x.onchange=()=>x.checked?selected.add(x.dataset.id):selected.delete(x.dataset.id));host.querySelectorAll('[data-doc]').forEach(x=>x.onclick=()=>detail(docs.find(d=>d.id===x.dataset.doc)));host.querySelectorAll('[data-fact]').forEach(x=>x.onchange=()=>docs.find(d=>d.id===x.dataset.fact).fact=x.value);host.querySelector('[data-act="ticket"]').onclick=()=>action('ticket');host.querySelector('[data-act="route"]').onclick=()=>action('route');host.querySelector('[data-act="import"]').onclick=()=>modal('<h2>Імпорт Excel</h2><p>Етап перевірки перед імпортом: нові / без змін / змінені документи.</p><div class="ops-import"><b>Приклад перевірки</b><span>171 нових</span><span>12 вже існують — пропустити</span><span>3 змінені — перевірити перед оновленням</span></div><button class="ops-choice">Обрати Excel файл</button>')}
function css(){const s=document.createElement('style');s.textContent=`.ops-card{margin-bottom:14px;overflow:hidden}.ops-head{display:flex;justify-content:space-between;align-items:center;padding:14px 16px}.ops-head>div:first-child{display:flex;flex-direction:column;gap:3px}.ops-head small{opacity:.55}.ops-head button,.ops-choice{background:#6f1730;color:#fff;border:1px solid #9c3450;border-radius:8px;padding:8px 11px;margin-left:7px;cursor:pointer}.ops-link{background:none;border:0;color:#e6a0b1;font-weight:700;cursor:pointer}.ops-card td small{display:block;opacity:.55;margin-top:3px}.ops-fact{width:65px;background:#17191e;border:1px solid #3b3d44;color:#fff;border-radius:6px;padding:5px}#ops-modal{display:none}#ops-modal.open{display:block;position:fixed;inset:0;z-index:9999}.ops-backdrop{position:absolute;inset:0;background:#000b}.ops-dialog{position:relative;margin:7vh auto;background:#17191e;border:1px solid #49323a;border-radius:14px;width:min(1000px,90vw);max-height:84vh;overflow:auto;padding:22px;color:#eee}.ops-dialog h2{margin-top:0}.ops-meta{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;background:#111318;padding:12px;border-radius:10px;margin-bottom:15px}.ops-meta span,.ops-meta b{display:block}.ops-dialog table{width:100%;border-collapse:collapse;margin-bottom:15px}.ops-dialog th,.ops-dialog td{padding:8px;border-bottom:1px solid #303238;text-align:left}.ops-close{background:#333740;color:#fff;border:0;border-radius:7px;padding:8px 14px}.ops-choice{display:block;margin:10px 0;width:280px}.ops-hint{opacity:.6}.ops-import{display:flex;gap:12px;flex-wrap:wrap;margin:15px 0}.ops-import span{padding:8px 10px;border:1px solid #3b3d44;border-radius:7px}@media(max-width:1000px){.ops-meta{grid-template-columns:1fr 1fr}.ops-card{overflow:auto}}`;document.head.append(s)}
css();render();
})();