(()=>{
const DOCS='tc_retail_docs_v2',IMPORTS='tc_retail_imports_v1',TICKETS='tc_retail_tickets_v1';
const get=(k,d=[])=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return d}};
const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const txt=v=>String(v??'').trim(),num=v=>Number(String(v??'').replace(',','.'))||0,rnd=(n,p=3)=>Math.round((Number(n)||0)*10**p)/10**p;
const esc=s=>txt(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dateFrom=s=>(txt(s).match(/(?:від|от)\s*(\d{2}\.\d{2}\.\d{4})/i)||[])[1]||'';
const STORES=[
[['рівне №2','рівне 2'], 'WT Рівне №2','Рівне','вул. Щаслива, буд. 1'],[['рівне №1','рівне 1'],'WT Рівне №1','Рівне','вул. Міцкевича, буд. 32'],
[['шалімова'],'WT Софіївська Борщагівка (Шалімова)','Софіївська Борщагівка','вул. Академіка Шалімова, буд. 69, прим. 95'],[['молодіжна'],'WT Софіївська Борщагівка (Молодіжна)','Софіївська Борщагівка','вул. Молодіжна, буд. 3, прим. 128'],
[['верхогляда'],'WT Верхогляда','Київ','вул. Андрія Верхогляда, буд. 9А'],[['маккейна'],'WT Маккейна','Київ','вул. Джона Маккейна, буд. 1'],[['філатова'],'WT Філатова','Київ','вул. Академіка Філатова, буд. 2/1'],[['голосіївська'],'WT Голосіївська','Київ','вул. Голосіївська, буд. 13'],[['ярославів вал'],'WT Ярославів Вал','Київ','вул. Ярославів Вал, буд. 37'],[['здановської'],'WT Здановської','Київ','вул. Юлії Здановської, буд. 48А'],[['вишгородська'],'WT Вишгородська','Київ','вул. Вишгородська, буд. 45'],[['велика васильківська'],'WT Велика Васильківська','Київ','вул. Велика Васильківська, буд. 100'],[['верхній вал'],'WT Верхній Вал','Київ','вул. Верхній Вал, буд. 16/4'],[['мокра'],'WT Мокра','Київ','вул. Мокра, буд. 18А'],[['дмитрівська'],'WT Дмитрівська','Київ','вул. Дмитрівська, буд. 62/20'],[['палладіна'],'WT Палладіна','Київ','просп. Академіка Палладіна, буд. 59Б'],[['бажана'],'WT Бажана','Київ','просп. Миколи Бажана, буд. 1Е'],[['соборності'],'WT Соборний','Київ','просп. Соборності, буд. 7Б'],
[['кременчук'],'WT Кременчук','Кременчук','вул. Соборна, буд. 34/32'],[['черкаси'],'WT Черкаси','Черкаси','вул. Михайла Грушевського, буд. 110'],[['крихівці'],'WT Крихівці','Крихівці','вул. Слобідська, буд. 2, прим. 266'],[['ужгород'],'WT Ужгород','Ужгород','вул. Собранецька, буд. 26'],[['тернопіль'],'WT Тернопіль','Тернопіль','вул. Соломії Крушельницької, буд. 51'],[['луцьк'],'WT Луцьк','Луцьк','вул. Градний Узвіз, буд. 2'],[['хмельницьк'],'WT Хмельницький','Хмельницький','вул. Проскурівська, буд. 16'],[['чернігів'],'WT Чернігів','Чернігів','вул. Київська, буд. 11'],[['івано-франків','франківськ'],'WT Івано-Франківськ','Івано-Франківськ','бульв. Південний, буд. 27Б'],[['княгині ольги'],'WT Львів (Княгині Ольги)','Львів','вул. Княгині Ольги, буд. 100К'],[['чорновола'],'WT Львів','Львів',"просп. В'ячеслава Чорновола, буд. 45"],[['зодчих'],'WT Вінниця №1','Вінниця','вул. Зодчих, буд. 5'],[['космонавтів'],'WT Вінниця №2','Вінниця','просп. Космонавтів, буд. 40'],[['грушевського,110','грушевського, 110'],'WT Черкаси','Черкаси','вул. Михайла Грушевського, буд. 110'],[['соборна, 34','соборна,34'],'WT Кременчук','Кременчук','вул. Соборна, буд. 34/32'],[['оля, 59','поля,59'],'WT Дніпро №3','Дніпро','просп. Олександра Поля, буд. 59'],[['яворницького'],'WT Дніпро №1','Дніпро','просп. Дмитра Яворницького, буд. 77'],[['головна, 37','головна,37'],'WT Чернівці №2','Чернівці','вул. Головна, буд. 37'],[['стоя нка','стоянка'],'WT Стоянка','Стоянка','вул. Меліораторів, буд. 1/3']];
function storeInfo(raw){const q=txt(raw).toLowerCase().replace(/ё/g,'е');for(const [keys,name,city,address] of STORES)if(keys.some(k=>q.includes(k)))return{name,city,address,full:`${city}, ${address}`};const cleaned=txt(raw).replace(/^Склад\s*№?\d*\s*магазин\s*/i,'').trim();return{name:cleaned||'Не зіставлено',city:'',address:'',full:cleaned||'Не зіставлено'}}
function parse(rows){let sender='',cur=null;const out=[];
 for(const row0 of rows){const r=row0||[],cells=r.map(txt);if(!cells.some(Boolean))continue;const li=cells.findIndex(x=>/^Лист\s*відбору/i.test(x));
  if(li<0){const g=txt(r[6]);if(/^Склад\s/i.test(g)&&!/получатель/i.test(g)){sender=g;cur=null;continue}}
  if(li>=0){const label=cells[li],labelNo=(label.match(/Лист\s*відбору\s*0*(\d+)/i)||[])[1]||'';let id=labelNo||txt(r[1]);
   let ri=cells.findIndex((x,i)=>i<li&&(/магазин/i.test(x)||/^Склад\s*№/i.test(x)));if(ri<0)ri=Math.max(0,li-4);const receiver=txt(r[ri]);
   const info=storeInfo(receiver);cur={id,date:dateFrom(label),store:info.name,storeAddress:info.full,receiverWarehouse:receiver||'—',senderWarehouse:sender||'—',sourcePallets:num(r[ri+1]),sourceWeight:num(r[ri+2]),qty:num(r[li+2]),amount:num(r[li+3]),fact:'',route:'',status:'Новий',workflowStatus:'new',lines:[]};out.push(cur);continue}
  if(cur){const li2=6;let nameIndex=cells.findIndex((x,i)=>i>=4&&i<=8&&x&&!/^Склад/i.test(x)&&!/^Лист/i.test(x)&&/[А-ЯІЇЄа-яіїє]/.test(x));if(nameIndex<0)nameIndex=li2;const skuIndex=nameIndex-5,sku=txt(r[skuIndex]);if(/^\d{6,}$/.test(sku)){const casesPal=num(r[nameIndex-3]),unitsCase=num(r[nameIndex-2]),unitWeight=num(r[nameIndex-1]),qty=num(r[nameIndex+2]),amount=num(r[nameIndex+3]);cur.lines.push({sku,barcode:txt(r[skuIndex+1]),casesPal,unitsCase,unitWeight,name:txt(r[nameIndex]),volume:txt(r[nameIndex+1]),qty,amount,pallets:casesPal&&unitsCase?rnd(qty/unitsCase/casesPal,6):0,weight:rnd(qty*unitWeight,3)})}}
 }
 out.forEach(d=>{d.calc=rnd(d.lines.reduce((s,x)=>s+x.pallets,0),3);d.calcWeight=rnd(d.lines.reduce((s,x)=>s+x.weight,0),3);d.key=[d.id,d.date,d.senderWarehouse,d.receiverWarehouse].join('|');d.hash=JSON.stringify([d.amount,d.qty,d.calc,d.calcWeight,d.lines.map(x=>[x.sku,x.qty,x.amount])])});return out.filter(d=>d.id&&d.receiverWarehouse&&d.receiverWarehouse!=='—')}
function modal(html){let m=document.getElementById('ops-fix-modal');if(!m){m=document.createElement('div');m.id='ops-fix-modal';document.body.append(m)}m.innerHTML=`<div class="ops-backdrop"></div><div class="ops-dialog">${html}<button class="ops-close">Закрити</button></div>`;m.className='open';m.querySelector('.ops-backdrop').onclick=m.querySelector('.ops-close').onclick=()=>m.className='';}
function openDoc(id){const d=get(DOCS).find(x=>String(x.id)===String(id));if(!d)return;modal(`<h2>Документ № ${esc(d.id)}</h2><div class="ops-grid"><div><small>Магазин</small><b>${esc(d.store)}</b></div><div><small>Адреса з довідника</small><b>${esc(d.storeAddress||storeInfo(d.receiverWarehouse).full)}</b></div><div><small>Склад відправника</small><b>${esc(d.senderWarehouse)}</b></div><div><small>Склад отримувача</small><b>${esc(d.receiverWarehouse)}</b></div><div><small>Вага</small><b>${rnd(d.calcWeight||d.sourceWeight)} кг</b></div><div><small>Палети розрах.</small><b>${rnd(d.calc)}</b></div></div><h3>Товарні позиції · ${d.lines?.length||0}</h3><table class="ops-register"><thead><tr><th>Артикул</th><th>Номенклатура</th><th>К-ть</th><th>Шт/кейс</th><th>Кейс/пал</th><th>Палети</th><th>Вага</th></tr></thead><tbody>${(d.lines||[]).map(x=>`<tr><td>${esc(x.sku)}</td><td>${esc(x.name)}</td><td>${x.qty}</td><td>${x.unitsCase}</td><td>${x.casesPal}</td><td>${rnd(x.pallets,4)}</td><td>${rnd(x.weight)} кг</td></tr>`).join('')}</tbody></table>`)}
function sendTicket(ids){if(!ids.length)return alert('Оберіть хоча б один документ.');let docs=get(DOCS),tickets=get(TICKETS);const no=`TK-${String(tickets.length+1).padStart(4,'0')}`;docs=docs.map(d=>ids.includes(String(d.id))?{...d,status:'На комплектації',workflowStatus:'picking'}:d);tickets.unshift({number:no,createdAt:new Date().toISOString(),documentIds:ids,status:'На комплектації'});set(DOCS,docs);set(TICKETS,tickets);alert(`Створено талон ${no}\nДокументів: ${ids.length}`);details(true)}
function details(force=false){const h=document.getElementById('ops-documents');if(!h)return;let box=h.querySelector('#base-doc-details');if(box&&!force){box.remove();return}if(box)box.remove();const docs=get(DOCS).map(d=>{const info=storeInfo(d.receiverWarehouse);return{...d,store:info.name,storeAddress:info.full}});box=document.createElement('div');box.id='base-doc-details';box.className='ops-section';box.innerHTML=`<div class="ops-page-title"><div><h3>Документи в базі · ${docs.length}</h3><p>Оберіть документи для передачі на комплектацію або відкрийте номер документа для перегляду позицій.</p></div><div class="ops-toolbar"><button class="ops-primary" data-ticket>Передати на комплектацію</button></div></div>${docs.length?`<table class="ops-register"><thead><tr><th><input type="checkbox" data-all></th><th>Документ</th><th>Дата</th><th>Магазин</th><th>Адреса магазину</th><th>Склад відправника</th><th>Склад отримувача</th><th>Вага</th><th>Палети системи</th><th>Палети розр.</th><th>Статус</th></tr></thead><tbody>${docs.map(d=>`<tr><td><input type="checkbox" data-doc="${esc(d.id)}"></td><td><button class="ops-link" data-open="${esc(d.id)}">№ ${esc(d.id)}</button></td><td>${esc(d.date||'—')}</td><td><b>${esc(d.store)}</b></td><td>${esc(d.storeAddress)}</td><td>${esc(d.senderWarehouse||'—')}</td><td>${esc(d.receiverWarehouse||'—')}</td><td>${rnd(d.calcWeight||d.sourceWeight)} кг</td><td class="ops-source">${rnd(d.sourcePallets)}</td><td><b>${rnd(d.calc)}</b></td><td>${esc(d.status||'Новий')}</td></tr>`).join('')}</tbody></table>`:'<div class="ops-empty">Документів ще немає.</div>'}`;h.append(box);box.querySelector('[data-all]')?.addEventListener('change',e=>box.querySelectorAll('[data-doc]').forEach(c=>c.checked=e.target.checked));box.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openDoc(b.dataset.open));box.querySelector('[data-ticket]')?.addEventListener('click',()=>sendTicket([...box.querySelectorAll('[data-doc]:checked')].map(c=>c.dataset.doc)));box.scrollIntoView({block:'start'})}
function loadXLSX(cb){if(window.XLSX)return cb();const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js';s.onload=cb;s.onerror=()=>alert('Не вдалося завантажити модуль Excel.');document.head.append(s)}
function upload(){loadXLSX(()=>{const input=document.createElement('input');input.type='file';input.accept='.xlsx,.xls';input.onchange=async()=>{const f=input.files?.[0];if(!f)return;try{const wb=XLSX.read(await f.arrayBuffer(),{type:'array'}),sheet=wb.Sheets.TDSheet||wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(sheet,{header:1,raw:true,defval:null,blankrows:false}),incoming=parse(rows);if(!incoming.length)return alert(`Документи не знайдені. Аркуш: ${wb.SheetNames.join(', ')}; рядків: ${rows.length}`);const old=get(DOCS),map=new Map(old.map(d=>[d.key,d]));let n=0,same=0,changed=0;for(const d of incoming){const e=map.get(d.key);if(!e){n++;map.set(d.key,d)}else if(e.hash===d.hash)same++;else{changed++;if(!['routed','ttn_created','dispatched','delivered'].includes(e.workflowStatus||''))map.set(d.key,{...d,fact:e.fact||'',route:e.route||'',status:e.status||'Новий',workflowStatus:e.workflowStatus||'new'})}}const imports=get(IMPORTS);imports.unshift({fileName:f.name,at:new Date().toISOString(),total:incoming.length,n,same,changed});set(DOCS,[...map.values()]);set(IMPORTS,imports.slice(0,20));alert(`Файл опрацьовано.\nДокументів: ${incoming.length}\nНових: ${n}\nБез змін: ${same}\nЗмінених: ${changed}`);location.hash='#base-excel';location.reload()}catch(e){console.error(e);alert('Помилка читання Excel: '+e.message)}};input.click()})}
function enhance(){if(location.hash!=='#base-excel')return;const h=document.getElementById('ops-documents');if(!h||h.style.display==='none')return;const up=h.querySelector('[data-upload]');if(up&&!up.dataset.fixed2){const c=up.cloneNode(true);c.dataset.fixed2='1';c.onclick=upload;up.replaceWith(c)}const title=h.querySelector('.ops-page-title');if(title&&!title.querySelector('[data-details2]')){const b=document.createElement('button');b.className='ops-primary';b.dataset.details2='1';b.textContent='Переглянути документи';b.onclick=()=>details();const a=document.createElement('div');a.className='ops-toolbar';const u=title.querySelector('[data-upload]');if(u){u.replaceWith(a);a.append(b,u)}else a.append(b);title.append(a)}}
const style=document.createElement('style');style.textContent='.ops-link{background:none;border:0;color:#ff6b83;font-weight:800;cursor:pointer;padding:0}.ops-link:hover{text-decoration:underline}#ops-fix-modal{display:none}#ops-fix-modal.open{display:block;position:fixed;inset:0;z-index:99999}#ops-fix-modal .ops-backdrop{position:absolute;inset:0;background:#000b}#ops-fix-modal .ops-dialog{position:absolute;left:5%;right:5%;top:5%;max-height:88vh;overflow:auto;background:#101821;border:1px solid #34404d;border-radius:14px;padding:22px;color:#fff}.ops-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:14px 0}.ops-grid>div{background:#17212c;padding:10px;border-radius:8px}.ops-grid small,.ops-grid b{display:block}.ops-close{margin-top:14px}.ops-register input[type=checkbox]{width:16px;height:16px;accent-color:#9d1235}';document.head.append(style);
const mo=new MutationObserver(()=>setTimeout(enhance,0));mo.observe(document.body,{childList:true,subtree:true});addEventListener('hashchange',()=>setTimeout(enhance,30));setTimeout(enhance,100);
})();