(()=>{
const DOCS='tc_retail_docs_v2', IMPORTS='tc_retail_imports_v1';
const getDocs=()=>{try{return JSON.parse(localStorage.getItem(DOCS)||'[]')}catch{return[]}};
const getImports=()=>{try{return JSON.parse(localStorage.getItem(IMPORTS)||'[]')}catch{return[]}};
const save=(docs,imports)=>{localStorage.setItem(DOCS,JSON.stringify(docs));localStorage.setItem(IMPORTS,JSON.stringify(imports))};
const txt=v=>String(v??'').trim(); const num=v=>Number(String(v??'').replace(',','.'))||0; const rnd=(n,p=3)=>Math.round(n*10**p)/10**p;
const dateFrom=s=>(txt(s).match(/(?:від|от)\s*(\d{2}\.\d{2}\.\d{4})/i)||[])[1]||'';
const normStore=s=>txt(s).replace(/^Склад\s*№?\d*\s*магазин\s*/i,'').trim()||txt(s);
function parse(rows){let sender='',cur=null;const out=[];
 for(const row0 of rows){const r=row0||[];const cells=r.map(txt);if(!cells.some(Boolean))continue;
  const labelIndex=cells.findIndex(x=>/^Лист\s*відбору/i.test(x));
  const warehouseIndex=cells.findIndex(x=>/^Склад\s/i.test(x)&&!/^Склад\s*получатель/i.test(x));
  if(labelIndex<0 && warehouseIndex>=0 && !cells.some(x=>/^\d{5,}$/.test(x))){sender=cells[warehouseIndex];continue}
  if(labelIndex>=0){const label=cells[labelIndex];const labelNo=(label.match(/Лист\s*відбору\s*0*(\d+)/i)||[])[1]||'';
   let id=txt(r[1])||labelNo; if(!/^\d+$/.test(id))id=labelNo;
   const receiver=txt(r[2])||cells.find(x=>/^Склад\s*№?/i.test(x)&&x!==sender)||'';
   cur={id,date:dateFrom(label),store:normStore(receiver),receiverWarehouse:receiver,senderWarehouse:sender,sourcePallets:num(r[3]),sourceWeight:num(r[4]),qty:num(r[8]),amount:num(r[9]),fact:'',route:'',status:'Новий',workflowStatus:'new',lines:[]};out.push(cur);continue}
  if(cur){const sku=txt(r[1]);const name=txt(r[6]);if(/^\d{6,}$/.test(sku)&&name&&!/^Лист\s*відбору/i.test(name)){const casesPal=num(r[3]),unitsCase=num(r[4]),unitWeight=num(r[5]),qty=num(r[8]),amount=num(r[9]);cur.lines.push({sku,barcode:txt(r[2]),casesPal,unitsCase,unitWeight,name,volume:txt(r[7]),qty,amount,pallets:casesPal&&unitsCase?rnd(qty/unitsCase/casesPal,6):0,weight:rnd(qty*unitWeight,3)})}}
 }
 out.forEach(d=>{d.calc=rnd(d.lines.reduce((s,x)=>s+x.pallets,0),3);d.calcWeight=rnd(d.lines.reduce((s,x)=>s+x.weight,0),3);d.key=[d.id,d.date,d.senderWarehouse,d.receiverWarehouse].join('|');d.hash=JSON.stringify([d.amount,d.qty,d.calc,d.calcWeight,d.lines.map(x=>[x.sku,x.qty,x.amount])])});return out.filter(d=>d.id&&d.receiverWarehouse)}
function loadXLSX(cb){if(window.XLSX)return cb();const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js';s.onload=cb;s.onerror=()=>alert('Не вдалося завантажити модуль Excel.');document.head.append(s)}
function upload(){loadXLSX(()=>{const input=document.createElement('input');input.type='file';input.accept='.xlsx,.xls';input.onchange=async()=>{const f=input.files?.[0];if(!f)return;try{const wb=XLSX.read(await f.arrayBuffer(),{type:'array',cellDates:false});const sheet=wb.Sheets.TDSheet||wb.Sheets[wb.SheetNames[0]];const rows=XLSX.utils.sheet_to_json(sheet,{header:1,raw:true,defval:null,blankrows:false});const incoming=parse(rows);if(!incoming.length){alert(`Документи не знайдені.\nАркуш: ${wb.SheetNames.join(', ')}\nРядків прочитано: ${rows.length}.\nОчікується первинний звіт з рядками «Лист відбору».`);return}const old=getDocs(),map=new Map(old.map(d=>[d.key,d]));let n=0,same=0,changed=0;for(const d of incoming){const e=map.get(d.key);if(!e){n++;map.set(d.key,d)}else if(e.hash===d.hash)same++;else{changed++;if(!['routed','ttn_created','dispatched','delivered'].includes(e.workflowStatus||''))map.set(d.key,{...d,fact:e.fact||'',route:e.route||'',status:e.status||'Новий',workflowStatus:e.workflowStatus||'new'})}}const imports=getImports();imports.unshift({fileName:f.name,at:new Date().toISOString(),total:incoming.length,n,same,changed});save([...map.values()],imports.slice(0,20));alert(`Файл опрацьовано.\nДокументів: ${incoming.length}\nНових: ${n}\nБез змін: ${same}\nЗмінених: ${changed}`);location.hash='#base-excel';location.reload()}catch(e){console.error(e);alert('Помилка читання Excel: '+e.message)}};input.click()})}
function details(){const docs=getDocs(),h=document.getElementById('ops-documents');if(!h)return;let box=h.querySelector('#base-doc-details');if(box){box.remove();return}box=document.createElement('div');box.id='base-doc-details';box.className='ops-section';box.innerHTML=`<h3>Документи в базі · ${docs.length}</h3>${docs.length?`<table class="ops-register"><thead><tr><th>Документ</th><th>Дата</th><th>Магазин</th><th>Склад відправника</th><th>Склад отримувача</th><th>Вага</th><th>Палети системи</th><th>Палети розр.</th><th>Позицій</th></tr></thead><tbody>${docs.map(d=>`<tr><td><b>№ ${d.id}</b></td><td>${d.date||'—'}</td><td>${d.store||'—'}</td><td>${d.senderWarehouse||'—'}</td><td>${d.receiverWarehouse||'—'}</td><td>${rnd(d.calcWeight||d.sourceWeight||0)} кг</td><td class="ops-source">${rnd(d.sourcePallets||0)}</td><td><b>${rnd(d.calc||0)}</b></td><td>${d.lines?.length||0}</td></tr>`).join('')}</tbody></table>`:'<div class="ops-empty">Документів ще немає.</div>'}`;h.append(box);box.scrollIntoView({block:'start'})}
function enhance(){if(location.hash!=='#base-excel')return;const h=document.getElementById('ops-documents');if(!h||h.style.display==='none')return;const up=h.querySelector('[data-upload]');if(up&&!up.dataset.fixed){const clone=up.cloneNode(true);clone.dataset.fixed='1';clone.onclick=upload;up.replaceWith(clone)}const title=h.querySelector('.ops-page-title');if(title&&!title.querySelector('[data-details]')){const b=document.createElement('button');b.className='ops-primary';b.dataset.details='1';b.textContent='Переглянути документи';b.onclick=details;const actions=document.createElement('div');actions.className='ops-toolbar';const current=title.querySelector('[data-upload]');if(current){current.replaceWith(actions);actions.append(b,current)}else actions.append(b);title.append(actions)}}
const mo=new MutationObserver(()=>setTimeout(enhance,0));mo.observe(document.body,{childList:true,subtree:true});window.addEventListener('hashchange',()=>setTimeout(enhance,30));setTimeout(enhance,100);
})();