import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const sql=readFileSync(new URL("../../migrations/20260904090000_source_identity_safe_sync_v2.sql",import.meta.url),"utf8");
const chunkSql=readFileSync(new URL("../../migrations/20260904150000_chunked_safe_sync_v2.sql",import.meta.url),"utf8");
test("migration uses text source IDs and payload idempotency key",()=>{assert.match(sql,/source_sale_id text not null/);assert.match(sql,/source_move_id text not null/);assert.match(sql,/unique\(source_namespace,source_json_sha256\)/)});
test("validation is mandatory before current snapshot mutation",()=>{const validate=sql.indexOf("status='validated'");const requireValidated=sql.indexOf("validated sync run required");const mutate=sql.indexOf("delete from public.cube_documents_current_v2");assert.ok(validate>=0&&requireValidated>validate&&mutate>requireValidated)});
test("promotion is serialized and implemented by one database function",()=>{assert.match(sql,/pg_advisory_xact_lock/);assert.match(sql,/create function public\.promote_cube_sync_run_v2/);assert.match(sql,/atomic promotion verification failed/)});
test("RLS and restricted function execution are present",()=>{assert.equal((sql.match(/enable row level security/g)??[]).length,9);assert.match(sql,/revoke all on function public\.validate_cube_sync_run_v2\(uuid,jsonb\),public\.promote_cube_sync_run_v2\(uuid\)/);assert.match(sql,/grant execute on function public\.validate_cube_sync_run_v2\(uuid,jsonb\),public\.promote_cube_sync_run_v2\(uuid\) to service_role/);assert.match(sql,/from public,anon,authenticated/)});
test("migration does not mutate legacy production tables",()=>{const mutations=[...sql.matchAll(/\b(?:insert into|update|delete from|truncate table)\s+public\.([a-z0-9_]+)/gi)].map(x=>x[1]);assert.ok(mutations.length>0);assert.ok(mutations.every(name=>name.endsWith("_v2")),mutations.join(", "))});
test("chunk migration is v2-only and secures transport RPCs",()=>{const names=[...chunkSql.matchAll(/\b(?:alter table|create table|insert into|update|delete from|truncate table)\s+public\.([a-z0-9_]+)/gi)].map(x=>x[1]);assert.ok(names.length>0);assert.ok(names.every(name=>name.endsWith("_v2")),names.join(", "));assert.match(chunkSql,/revoke all on function public\.ingest_cube_sync_chunk_v2/);assert.match(chunkSql,/to service_role/)});
test("finalize requires every contiguous chunk before validation",()=>{assert.match(chunkSql,/actual_chunks<>expected_chunks/);assert.match(chunkSql,/min_chunk<>0/);assert.match(chunkSql,/max_chunk<>expected_chunks-1/);assert.ok(chunkSql.indexOf("missing or non-contiguous chunks")<chunkSql.indexOf("validate_cube_sync_run_v2"))});
test("chunk receipts make exact retries idempotent and reject changed content",()=>{assert.match(chunkSql,/primary key\(run_id,entity_type,chunk_index\)/);assert.match(chunkSql,/chunk retry checksum mismatch/);assert.match(chunkSql,/jsonb_build_object\('idempotent',true/)});
test("raw audit payload columns are nullable and transport carries compact fields",()=>{assert.equal((chunkSql.match(/alter column raw_[a-z_]+ drop not null/g)??[]).length,8)});
