import assert from "node:assert/strict";
import test from "node:test";
import { executeSafeSync, type SafeSyncStore } from "./workflow.ts";

const build:any={run:{source_namespace:"ts-plus-cube"},documents:[],baseLinks:[],movements:[],businessLinks:[],report:{validationPassed:true,promoted:false}};
test("repeated identical promoted import is idempotent",async()=>{let stages=0,promotions=0;const store:SafeSyncStore={find:async()=>({id:"run-1",status:"promoted",validation_report:{financialFacts:1}}),stage:async()=>{stages++;return"x"},validate:async()=>{},promote:async()=>{promotions++;return{}}};const result=await executeSafeSync(store,build,"same-hash");assert.equal(result.idempotent,true);assert.equal(stages,0);assert.equal(promotions,0)});
test("failed validation leaves current snapshot unchanged",async()=>{const current=["old-current"];let promotions=0;const store:SafeSyncStore={find:async()=>null,stage:async()=>"run-2",validate:async()=>{throw new Error("control totals mismatch")},promote:async()=>{promotions++;current.splice(0,current.length,"new-current");return{}}};await assert.rejects(executeSafeSync(store,build,"bad-hash"),/control totals/);assert.deepEqual(current,["old-current"]);assert.equal(promotions,0)});
test("first run never promotes by default",async()=>{const calls:string[]=[];const store:SafeSyncStore={find:async()=>null,stage:async()=>{calls.push("stage");return"run-first"},validate:async()=>{calls.push("validate")},promote:async()=>{calls.push("promote");return{}}};const result=await executeSafeSync(store,build,"first-hash");assert.deepEqual(calls,["stage","validate"]);assert.equal(result.status,"validated");assert.equal(result.promoted,false)});
test("identical validated payload remains validated",async()=>{let promotions=0;const store:SafeSyncStore={find:async()=>({id:"run-validated",status:"validated",validation_report:{financialFacts:1}}),stage:async()=>"unused",validate:async()=>{},promote:async()=>{promotions++;return{}}};const result=await executeSafeSync(store,build,"same-validated-hash");assert.equal(promotions,0);assert.equal(result.status,"validated");assert.equal(result.promoted,false);assert.equal(result.idempotent,true)});
test("successful validation invokes one atomic promotion when explicitly requested",async()=>{const calls:string[]=[];const store:SafeSyncStore={find:async()=>null,stage:async()=>{calls.push("stage");return"run-3"},validate:async()=>{calls.push("validate")},promote:async()=>{calls.push("atomic-promote");return{financialFacts:1}}};const result=await executeSafeSync(store,build,"good-hash",{promote:true});assert.deepEqual(calls,["stage","validate","atomic-promote"]);assert.equal(result.promoted,true)});
test("explicit promotion of a validated run does not re-stage or re-validate",async()=>{const calls:string[]=[];const store:SafeSyncStore={find:async()=>({id:"run-ready",status:"validated",validation_report:{validationPassed:true}}),stage:async()=>{calls.push("stage");return"unused"},validate:async()=>{calls.push("validate")},promote:async()=>{calls.push("atomic-promote");return{}}};const result=await executeSafeSync(store,build,"ready-hash",{promote:true});assert.deepEqual(calls,["atomic-promote"]);assert.equal(result.promoted,true)});
