import 'dart:async';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'retail_dashboard_v3.dart' as legacy;

const u = String.fromEnvironment('SUPABASE_URL');
const k = String.fromEnvironment('SUPABASE_ANON_KEY');
const bg=Color(0xFF080C11), panel=Color(0xFF101720), panel2=Color(0xFF151C25), border=Color(0xFF29313C);
const wine=Color(0xFF8E1937), red=Color(0xFFEF3158), orange=Color(0xFFFF7A35), green=Color(0xFF31D47A), blue=Color(0xFF2E82D5), muted=Color(0xFF9AA3B1);
const heroUrl='https://pikwizard.com/pw/medium/a306e242656281d1c6a72df19bb788f4.jpg';

Future<void> main() async { WidgetsFlutterBinding.ensureInitialized(); await Supabase.initialize(url:u,anonKey:k); runApp(const App()); }
class App extends StatelessWidget { const App({super.key}); @override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Retail ТОВ «ТС ПЛЮС»',theme:ThemeData(brightness:Brightness.dark,useMaterial3:true,scaffoldBackgroundColor:bg,colorScheme:ColorScheme.fromSeed(seedColor:wine,brightness:Brightness.dark),fontFamily:'Arial'),home:const Gate());}
class Gate extends StatefulWidget{const Gate({super.key});@override State<Gate> createState()=>_Gate();}
class _Gate extends State<Gate>{Session? s;StreamSubscription<AuthState>? sub;@override void initState(){super.initState();s=Supabase.instance.client.auth.currentSession;sub=Supabase.instance.client.auth.onAuthStateChange.listen((e){if(mounted)setState(()=>s=e.session);});}@override void dispose(){sub?.cancel();super.dispose();}@override Widget build(BuildContext c)=>s==null?const Login():const Home();}
class Login extends StatefulWidget{const Login({super.key});@override State<Login> createState()=>_Login();}
class _Login extends State<Login>{final e=TextEditingController(),p=TextEditingController();bool b=false;String? err;Future<void> go()async{if(e.text.trim().isEmpty||p.text.isEmpty)return;setState((){b=true;err=null;});try{await Supabase.instance.client.auth.signInWithPassword(email:e.text.trim(),password:p.text);}on AuthException catch(x){if(mounted)setState(()=>err=x.message);}finally{if(mounted)setState(()=>b=false);}}@override Widget build(BuildContext c)=>Scaffold(body:Center(child:Container(width:420,padding:const EdgeInsets.all(28),decoration:BoxDecoration(color:panel,borderRadius:BorderRadius.circular(18),border:Border.all(color:border)),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.stretch,children:[Center(child:ClipRRect(borderRadius:BorderRadius.circular(16),child:Image.memory(base64Decode(legacy.logoBase64),width:120,height:120,fit:BoxFit.cover))),const SizedBox(height:18),const Text('Retail ТОВ «ТС ПЛЮС»',textAlign:TextAlign.center,style:TextStyle(fontSize:26,fontWeight:FontWeight.w800)),const SizedBox(height:20),TextField(controller:e,decoration:const InputDecoration(labelText:'Email')),const SizedBox(height:12),TextField(controller:p,obscureText:true,onSubmitted:(_)=>go(),decoration:const InputDecoration(labelText:'Пароль')),if(err!=null)...[const SizedBox(height:8),Text(err!,style:const TextStyle(color:Colors.redAccent))],const SizedBox(height:16),FilledButton(onPressed:b?null:go,child:Text(b?'Вхід…':'Увійти'))]))));}

class Home extends StatelessWidget{const Home({super.key});@override Widget build(BuildContext c)=>Scaffold(body:Center(child:FittedBox(fit:BoxFit.contain,alignment:Alignment.topCenter,child:const SizedBox(width:1536,height:1024,child:Row(children:[SizedBox(width:250,child:Side()),Expanded(child:Column(children:[Top(),Expanded(child:Board())]))])))));}
class Side extends StatelessWidget{const Side({super.key});static const items=[('Головна',Icons.home_rounded),('Вхідні вантажі',Icons.local_shipping_rounded),('Консолідація',Icons.inventory_2_rounded),('Маршрути',Icons.location_on_rounded),('Талони комплектації',Icons.assignment_rounded),('ТТН',Icons.description_rounded),('Магазини WT',Icons.storefront_rounded),('Склади',Icons.home_work_rounded),('Перевізники',Icons.local_shipping_outlined),('Тарифи',Icons.stacked_bar_chart_rounded),('Аналітика',Icons.bar_chart_rounded),('Довідники',Icons.menu_book_rounded),('Користувачі',Icons.group_rounded),('Налаштування',Icons.settings_rounded)];@override Widget build(BuildContext c)=>Container(decoration:const BoxDecoration(gradient:LinearGradient(begin:Alignment.topCenter,end:Alignment.bottomCenter,colors:[Color(0xFF30111E),Color(0xFF170E14),Color(0xFF1D1018)]),border:Border(right:BorderSide(color:Color(0xFF30242B)))),child:Stack(children:[const Positioned(left:0,right:0,bottom:0,height:290,child:Road()),Column(children:[const SizedBox(height:14),ClipRRect(borderRadius:BorderRadius.circular(13),child:Image.memory(base64Decode(legacy.logoBase64),width:172,height:132,fit:BoxFit.cover)),const SizedBox(height:12),Expanded(child:ListView.builder(padding:const EdgeInsets.symmetric(horizontal:12),itemCount:items.length,itemBuilder:(c,i)=>Container(height:44,margin:const EdgeInsets.only(bottom:4),padding:const EdgeInsets.symmetric(horizontal:14),decoration:BoxDecoration(color:i==0?wine:Colors.transparent,borderRadius:BorderRadius.circular(10)),child:Row(children:[Icon(items[i].$2,size:20,color:Colors.white.withValues(alpha:.9)),const SizedBox(width:13),Text(items[i].$1,style:const TextStyle(fontSize:15,fontWeight:FontWeight.w500))])))),const Padding(padding:EdgeInsets.fromLTRB(20,0,18,22),child:Align(alignment:Alignment.centerLeft,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Retail ТОВ «ТС ПЛЮС»',style:TextStyle(fontSize:14,fontWeight:FontWeight.w700)),SizedBox(height:5),Text('Логістика, що рухає бізнес',style:TextStyle(fontSize:11,color:muted)),SizedBox(height:12),Text('v1.0.0   |   2026',style:TextStyle(fontSize:10,color:muted))])))]),]));}
class Road extends StatelessWidget{const Road({super.key});@override Widget build(BuildContext c)=>CustomPaint(painter:RoadP());}
class RoadP extends CustomPainter{@override void paint(Canvas c,Size s){final p=Paint()..style=PaintingStyle.stroke..strokeWidth=4..color=const Color(0xFF65203A);final a=Path()..moveTo(115,s.height)..cubicTo(120,s.height-65,195,s.height-95,205,s.height-175)..cubicTo(215,s.height-235,190,s.height-265,190,0);c.drawPath(a,p);p..strokeWidth=2..color=const Color(0xFF8C2D4B);final b=Path()..moveTo(145,s.height)..cubicTo(145,s.height-60,215,s.height-90,220,s.height-170)..cubicTo(225,s.height-220,210,s.height-255,212,0);c.drawPath(b,p);}@override bool shouldRepaint(covariant CustomPainter old)=>false;}
class Top extends StatelessWidget{const Top({super.key});@override Widget build(BuildContext c)=>Container(height:88,padding:const EdgeInsets.symmetric(horizontal:28),decoration:const BoxDecoration(color:Color(0xFF0B1118),border:Border(bottom:BorderSide(color:Color(0xFF242C36)))),child:Row(children:[const Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Retail ТОВ «ТС ПЛЮС»',style:TextStyle(fontSize:29,fontWeight:FontWeight.w800)),SizedBox(height:3),Text('Логістика. Контроль. Результат.',style:TextStyle(fontSize:14,color:muted))]),const Spacer(),const Icon(Icons.calendar_month_rounded,color:red,size:25),const SizedBox(width:10),const Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.start,children:[Text('14.09.2026',style:TextStyle(fontSize:14,fontWeight:FontWeight.w700)),Text('Понеділок, 16:24',style:TextStyle(fontSize:10,color:muted))]),Container(width:1,height:42,color:border,margin:const EdgeInsets.symmetric(horizontal:22)),Stack(clipBehavior:Clip.none,children:[const Icon(Icons.notifications_rounded,color:Color(0xFFF4D4BE),size:26),Positioned(right:-7,top:-8,child:Container(width:18,height:18,alignment:Alignment.center,decoration:const BoxDecoration(color:Color(0xFFDC3148),shape:BoxShape.circle),child:const Text('3',style:TextStyle(fontSize:9,fontWeight:FontWeight.bold))))]),const SizedBox(width:28),const CircleAvatar(radius:21,backgroundColor:Color(0xFF8A1E39),child:Text('ІБ',style:TextStyle(fontSize:12,fontWeight:FontWeight.w700))),const SizedBox(width:10),const Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Ігор Бойко',style:TextStyle(fontSize:13,fontWeight:FontWeight.w700)),Text('Транспортний відділ',style:TextStyle(fontSize:9,color:muted))]),const SizedBox(width:8),const Icon(Icons.keyboard_arrow_down_rounded,color:muted),const SizedBox(width:16),IconButton(onPressed:()=>Supabase.instance.client.auth.signOut(),icon:const Icon(Icons.logout_rounded,color:Color(0xFFFFDDE2))) ]));}

class Board extends StatelessWidget{const Board({super.key});@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.fromLTRB(18,14,18,14),child:Column(children:[const Hero(),const SizedBox(height:12),const Kpis(),const SizedBox(height:12),const Row(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(flex:39,child:Inbound()),SizedBox(width:12),Expanded(flex:32,child:Hubs()),SizedBox(width:12),Expanded(flex:29,child:Types())]),const SizedBox(height:12),const Routes()]));}
class Hero extends StatelessWidget{const Hero({super.key});@override Widget build(BuildContext c)=>ClipRRect(borderRadius:BorderRadius.circular(17),child:Container(height:179,decoration:BoxDecoration(border:Border.all(color:const Color(0xFF5A2B39)),borderRadius:BorderRadius.circular(17)),child:Stack(fit:StackFit.expand,children:[Image.network(heroUrl,fit:BoxFit.cover,errorBuilder:(_,__,___)=>Container(color:const Color(0xFF17131A))),Container(decoration:const BoxDecoration(gradient:LinearGradient(begin:Alignment.centerLeft,end:Alignment.centerRight,colors:[Color(0xED090E15),Color(0xA50B1017),Color(0x2D0B1017)]))),const Positioned(left:27,top:24,child:Text('P E O P L E   •   P R O C E S S   •   D E L I V E R Y',style:TextStyle(fontSize:12,color:Color(0xFFFF826F),letterSpacing:1.7))),const Positioned(left:27,top:59,child:Text('НАДІЙНА ЛОГІСТИКА',style:TextStyle(fontSize:29,fontWeight:FontWeight.w800))),const Positioned(left:27,top:97,child:Row(children:[Text('ДЛЯ РОЗВИТКУ ',style:TextStyle(fontSize:27)),Text('RETAIL',style:TextStyle(fontSize:27,fontWeight:FontWeight.w800,color:Color(0xFFE14250)))])),const Positioned(left:27,bottom:18,child:Text('Більше, ніж доставка',style:TextStyle(fontSize:14,color:Color(0xFFB6BAC3)))),const Positioned(right:30,top:29,child:Column(crossAxisAlignment:CrossAxisAlignment.end,children:[Text('СКЛАДИ',style:TextStyle(fontSize:12,color:Color(0xFFD1C9CD),letterSpacing:2)),SizedBox(height:7),Text('МАРШРУТИ',style:TextStyle(fontSize:12,color:Color(0xFFD1C9CD),letterSpacing:2)),SizedBox(height:7),Text('КОНСОЛІДАЦІЯ',style:TextStyle(fontSize:12,color:Color(0xFFD1C9CD),letterSpacing:2)),SizedBox(height:7),Text('КОНТРОЛЬ',style:TextStyle(fontSize:12,color:Color(0xFFD1C9CD),letterSpacing:2)),SizedBox(height:7),Text('РЕЗУЛЬТАТ',style:TextStyle(fontSize:12,color:Color(0xFFD1C9CD),letterSpacing:2))]))])));}
class Kpis extends StatelessWidget{const Kpis({super.key});@override Widget build(BuildContext c)=>const Row(children:[Expanded(child:Kpi(Icons.local_shipping_rounded,'5','Вхідних вантажів','сьогодні',Color(0xFFBA284E))),SizedBox(width:12),Expanded(child:Kpi(Icons.inventory_2_rounded,'33','Палети на хабах','до розконсолідації',orange)),SizedBox(width:12),Expanded(child:Kpi(Icons.hub_rounded,'12','Маршрутів','сьогодні',Color(0xFFCC2C55))),SizedBox(width:12),Expanded(child:Kpi(Icons.storefront_rounded,'38','Магазинів WT','в роботі',Color(0xFFBCC2CB))),SizedBox(width:12),Expanded(child:Kpi(Icons.check_circle_rounded,'8','Доставлено','сьогодні',green))]);}
class Kpi extends StatelessWidget{final IconData i;final String n,t,s;final Color c;const Kpi(this.i,this.n,this.t,this.s,this.c,{super.key});@override Widget build(BuildContext x)=>Container(height:104,padding:const EdgeInsets.symmetric(horizontal:18),decoration:BoxDecoration(gradient:LinearGradient(colors:[c.withValues(alpha:.18),panel]),border:Border.all(color:c.withValues(alpha:.55)),borderRadius:BorderRadius.circular(14)),child:Row(children:[Icon(i,color:c,size:34),const SizedBox(width:18),Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.start,children:[Text(n,style:const TextStyle(fontSize:31,fontWeight:FontWeight.w800,height:1)),const SizedBox(height:7),Text(t,style:const TextStyle(fontSize:14,fontWeight:FontWeight.w700)),const SizedBox(height:4),Text(s,style:const TextStyle(fontSize:11,color:muted))]),const Spacer(),const Icon(Icons.chevron_right_rounded,color:Color(0xFF77818E))]));}

class Pane extends StatelessWidget{final Widget child;final double h;const Pane(this.child,this.h,{super.key});@override Widget build(BuildContext c)=>Container(height:h,padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:panel,border:Border.all(color:border),borderRadius:BorderRadius.circular(14)),child:child);}
class TitleRow extends StatelessWidget{final IconData i;final String t;final Color c;final String? a;const TitleRow(this.i,this.t,this.c,{this.a,super.key});@override Widget build(BuildContext x)=>Row(children:[Icon(i,size:22,color:c),const SizedBox(width:10),Text(t,style:const TextStyle(fontSize:15,fontWeight:FontWeight.w800)),const Spacer(),if(a!=null)Text(a!,style:TextStyle(fontSize:11,color:a!.startsWith('+')?Colors.white:red))]);}
class Inbound extends StatelessWidget{const Inbound({super.key});@override Widget build(BuildContext c)=>Pane(Column(children:[const TitleRow(Icons.local_shipping_rounded,'Вхідні вантажі',red,a:'+  Додати'),const SizedBox(height:8),const Head(['№','Звідки','Куди','Палети','Статус'],[1,2,2,1,2]),const Mini(['IN-001','Корпоратура','Розумовського','33'],'Прийнято',green,[1,2,2,1]),const Mini(['IN-002','Острів 1','Розумовського','12'],'В дорозі',blue,[1,2,2,1]),const Mini(['IN-003','Корпоратура','Острів 2','18'],'Очікується',Color(0xFFE49A35),[1,2,2,1]),const Mini(['IN-004','Острів 2','Розумовського','8'],'План',Color(0xFF7C8798),[1,2,2,1]),const Mini(['IN-005','Корпоратура','Острів 1','16'],'В дорозі',blue,[1,2,2,1]),const Spacer(),const Align(alignment:Alignment.centerRight,child:Text('Усі вхідні вантажі  →',style:TextStyle(color:red,fontSize:11)))]),292);}
class Hubs extends StatelessWidget{const Hubs({super.key});@override Widget build(BuildContext c)=>Pane(Column(children:[const TitleRow(Icons.warehouse_rounded,'Консолідація (хаби)',Color(0xFFF2A27C),a:'Детальніше  →'),const SizedBox(height:8),const Head(['Склад','Палети','Статус','Заповнення'],[3,1,2,2]),const HubR('Розумовського 27','33',.60),const HubR('Острів 1','5',.25),const HubR('Острів 2','0',0),const HubR('Львів (партнер)','7',.35),const HubR('Білогородка','4',.20),const Spacer()]),292);}
class Types extends StatelessWidget{const Types({super.key});@override Widget build(BuildContext c)=>Pane(Column(children:[const TitleRow(Icons.hub_rounded,'Типи маршрутів',red),const SizedBox(height:10),const RT(Icons.storefront_rounded,'Retail (сухий)','Мережа WT, стандартна продукція','8',Color(0xFFD1D5DB)),const SizedBox(height:9),const RT(Icons.ac_unit_rounded,'Холодний склад','Fresh / Frozen / Multiref','4',Color(0xFF43A2FF)),const SizedBox(height:9),const RT(Icons.inventory_2_rounded,'Міжскладські','Корпоратура / Острів / інші','3',Color(0xFFC9CDD3)),const Spacer(),const Align(alignment:Alignment.centerRight,child:Text('Створити маршрут  →',style:TextStyle(color:red,fontSize:11)))]),292);}
class Head extends StatelessWidget{final List<String> t;final List<int> f;const Head(this.t,this.f,{super.key});@override Widget build(BuildContext c)=>Container(height:28,padding:const EdgeInsets.symmetric(horizontal:6),decoration:BoxDecoration(color:panel2,borderRadius:BorderRadius.circular(6)),child:Row(children:[for(int x=0;x<t.length;x++)Expanded(flex:f[x],child:Text(t[x],style:const TextStyle(fontSize:9,color:muted)))]));}
class Mini extends StatelessWidget{final List<String> v;final String s;final Color c;final List<int> f;const Mini(this.v,this.s,this.c,this.f,{super.key});@override Widget build(BuildContext x)=>Container(height:39,padding:const EdgeInsets.symmetric(horizontal:6),decoration:const BoxDecoration(border:Border(bottom:BorderSide(color:Color(0xFF202833)))),child:Row(children:[for(int i=0;i<v.length;i++)Expanded(flex:f[i],child:Text(v[i],style:const TextStyle(fontSize:10))),Expanded(flex:2,child:Align(alignment:Alignment.centerLeft,child:Tag(s,c)))]));}
class HubR extends StatelessWidget{final String a,b;final double p;const HubR(this.a,this.b,this.p,{super.key});@override Widget build(BuildContext x)=>Padding(padding:const EdgeInsets.symmetric(vertical:7),child:Row(children:[Expanded(flex:3,child:Text(a,style:const TextStyle(fontSize:11))),Expanded(child:Text(b,style:const TextStyle(fontSize:11,fontWeight:FontWeight.w700))),Expanded(flex:2,child:Container(height:9,decoration:BoxDecoration(color:const Color(0xFF252D38),borderRadius:BorderRadius.circular(10)),child:FractionallySizedBox(widthFactor:p,alignment:Alignment.centerLeft,child:Container(decoration:BoxDecoration(color:orange,borderRadius:BorderRadius.circular(10)))))),const SizedBox(width:10),Expanded(flex:2,child:Text('${(p*100).round()}%',style:const TextStyle(fontSize:11)))]));}
class RT extends StatelessWidget{final IconData i;final String t,s,n;final Color c;const RT(this.i,this.t,this.s,this.n,this.c,{super.key});@override Widget build(BuildContext x)=>Container(height:56,padding:const EdgeInsets.symmetric(horizontal:12),decoration:BoxDecoration(color:const Color(0xFF141B26),borderRadius:BorderRadius.circular(10),border:Border.all(color:const Color(0xFF202936))),child:Row(children:[Icon(i,color:c,size:24),const SizedBox(width:12),Expanded(child:Column(mainAxisAlignment:MainAxisAlignment.center,crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(fontSize:12,fontWeight:FontWeight.w700)),const SizedBox(height:4),Text(s,style:const TextStyle(fontSize:9,color:muted))])),Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text(n,style:const TextStyle(fontSize:20,fontWeight:FontWeight.w800)),const Text('сьогодні',style:TextStyle(fontSize:8,color:muted))]),const SizedBox(width:5),const Icon(Icons.chevron_right_rounded,color:muted,size:18)]));}
class Tag extends StatelessWidget{final String t;final Color c;const Tag(this.t,this.c,{super.key});@override Widget build(BuildContext x)=>Container(padding:const EdgeInsets.symmetric(horizontal:9,vertical:4),decoration:BoxDecoration(color:c.withValues(alpha:.18),borderRadius:BorderRadius.circular(12),border:Border.all(color:c.withValues(alpha:.65))),child:Text(t,style:TextStyle(fontSize:9,color:c,fontWeight:FontWeight.w700)));}

class Routes extends StatelessWidget{const Routes({super.key});@override Widget build(BuildContext c)=>Pane(Column(children:[Row(children:[const Icon(Icons.receipt_long_rounded,color:red,size:22),const SizedBox(width:10),const Text('Сьогоднішні маршрути',style:TextStyle(fontSize:15,fontWeight:FontWeight.w800)),const SizedBox(width:24),const ChipX('Усі','12',true),const SizedBox(width:8),const ChipX('Retail','8',false),const SizedBox(width:8),const ChipX('Холодний','4',false),const SizedBox(width:8),const ChipX('Міжскладські','3',false),const Spacer(),Container(height:40,padding:const EdgeInsets.symmetric(horizontal:17),decoration:BoxDecoration(color:const Color(0xFF971C3B),borderRadius:BorderRadius.circular(9)),child:const Row(children:[Icon(Icons.add,size:20),SizedBox(width:8),Text('Новий маршрут',style:TextStyle(fontSize:12,fontWeight:FontWeight.w600))]))]),const SizedBox(height:11),const RouteHead(),const RR('R-001','Retail','Розумовського → Палладіна → Бажана','5','8','AA 1234 XX','14.09 12:00','В дорозі',blue),const RR('R-002','Retail','Розумовського → Маккейна → Філатова','4','7','AA 5678 XX','14.09 13:00','Скомплектовано',Color(0xFFE49A35)),const RR('F-001','Холодний','Розумовського → Соборності → Здановської','6','9','AA 9012 XX','14.09 14:00','В дорозі',blue),const RR('R-003','Retail','Розумовського → Верхній Вал → Ярославів Вал','4','6','AA 3456 XX','14.09 15:00','Заплановано',Color(0xFF6B7583)),const Spacer(),const Align(alignment:Alignment.centerRight,child:Text('Усі маршрути  →',style:TextStyle(color:red,fontSize:11)))]),276);}
class ChipX extends StatelessWidget{final String t,n;final bool a;const ChipX(this.t,this.n,this.a,{super.key});@override Widget build(BuildContext x)=>Container(height:31,padding:const EdgeInsets.symmetric(horizontal:12),decoration:BoxDecoration(color:a?wine:const Color(0xFF171E29),borderRadius:BorderRadius.circular(8)),child:Row(children:[Text(t,style:const TextStyle(fontSize:10)),const SizedBox(width:8),Container(padding:const EdgeInsets.symmetric(horizontal:6,vertical:2),decoration:BoxDecoration(color:Colors.black.withValues(alpha:.22),borderRadius:BorderRadius.circular(9)),child:Text(n,style:const TextStyle(fontSize:9)))]));}
class RouteHead extends StatelessWidget{const RouteHead({super.key});@override Widget build(BuildContext x)=>Container(height:31,padding:const EdgeInsets.symmetric(horizontal:12),decoration:BoxDecoration(color:panel2,borderRadius:BorderRadius.circular(6)),child:const Row(children:[SizedBox(width:65,child:Text('№',style:TextStyle(fontSize:10,color:muted))),SizedBox(width:100,child:Text('Тип',style:TextStyle(fontSize:10,color:muted))),Expanded(flex:4,child:Text('Маршрут',style:TextStyle(fontSize:10,color:muted))),SizedBox(width:80,child:Text('Магазини',style:TextStyle(fontSize:10,color:muted))),SizedBox(width:80,child:Text('Палети',style:TextStyle(fontSize:10,color:muted))),SizedBox(width:120,child:Text('Авто',style:TextStyle(fontSize:10,color:muted))),SizedBox(width:130,child:Text('План виїзду',style:TextStyle(fontSize:10,color:muted))),SizedBox(width:150,child:Text('Статус',style:TextStyle(fontSize:10,color:muted))),SizedBox(width:30,child:Text('•••',style:TextStyle(fontSize:10,color:muted)))]));}
class RR extends StatelessWidget{final String a,b,c,d,e,f,g,h;final Color col;const RR(this.a,this.b,this.c,this.d,this.e,this.f,this.g,this.h,this.col,{super.key});@override Widget build(BuildContext x)=>Container(height:39,padding:const EdgeInsets.symmetric(horizontal:12),decoration:const BoxDecoration(border:Border(bottom:BorderSide(color:Color(0xFF202833)))),child:Row(children:[SizedBox(width:65,child:Text(a,style:const TextStyle(fontSize:10))),SizedBox(width:100,child:Align(alignment:Alignment.centerLeft,child:Tag(b,b=='Retail'?wine:blue))),Expanded(flex:4,child:Text(c,style:const TextStyle(fontSize:10))),SizedBox(width:80,child:Text(d,style:const TextStyle(fontSize:10))),SizedBox(width:80,child:Text(e,style:const TextStyle(fontSize:10))),SizedBox(width:120,child:Text(f,style:const TextStyle(fontSize:10))),SizedBox(width:130,child:Text(g,style:const TextStyle(fontSize:10))),SizedBox(width:150,child:Align(alignment:Alignment.centerLeft,child:Tag(h,col))),const SizedBox(width:30,child:Text('•••',style:TextStyle(fontSize:10,color:muted)))]));}
