const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.join(__dirname,'../web/retail-cloudflare'),src=n=>fs.readFileSync(path.join(root,n),'utf8');
function storage(seed={}){const m=new Map(Object.entries(seed));return{getItem:k=>m.has(k)?m.get(k):null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)}}
function boot(s){let modal=null,feedback=null;const node=()=>({type:'',id:'',className:'',textContent:'',hidden:false,dataset:{},style:{},onclick:null,onchange:null,setAttribute(){},append(){},appendChild(){},remove(){this.removed=true},querySelector(){return null},querySelectorAll(){return[]}});const control=(value='',text=value)=>({...node(),value,selectedOptions:[{textContent:text}],disabled:false,checked:false,matches:()=>false,closest:()=>null});const controls={date:control('2026-09-16'),from:control('wh-1','Чайки'),carrier:control('c1','STV'),driver:control('d1','Водій'),vehicle:control('v1','AA0001AA'),count:control(),tt:control(),pal:control(),kg:control(),sum:control()};function makeModal(){return{...node(),innerHTML:'',querySelector(sel){const f=sel.match(/^\[data-f=(.+)\]$/);if(f)return controls[f[1]];const k=sel.match(/^\[data-k=(.+)\]$/);if(k)return controls[k[1]];if(sel==='[data-count]')return controls.count;return null}}}const document={body:{append(x){if(x?.id==='retail-feedback')feedback=x;else modal=x},appendChild(x){if(x?.id==='retail-feedback')feedback=x;else modal=x}},getElementById(id){return id==='retail-feedback'?feedback:null},querySelector(sel){return sel==='.rb7'&&modal&&!modal.removed?modal:null},createElement(tag){return tag==='div'?makeModal():node()}};const c={console,localStorage:s,sessionStorage:storage(),structuredClone,document,location:{hash:''},setTimeout:f=>{if(typeof f==='function')f();return 1},clearTimeout(){},Intl,Date,Promise,Error,Map,Set,alert:m=>c.alerts.push(m),alerts:[]};c.window=c;c.window.addEventListener=()=>{};c.window.dispatchEvent=()=>{};c.window.open=()=>({document:{write:x=>{c.printed=x},close(){}},focus(){},print(){c.didPrint=true}});c.RetailDirectories={warehouses:()=>[{id:'wh-1',city:'Чайки',address:'Київська обл.',responsible:'Бойко Ігор Дмитрович'}]};c.RetailCanonicalStores={match:()=>null};c.RetailRoutes={render(){}};vm.createContext(c);for(const f of ['retail-state.js','route-builder-v7.js','route-ttn-generator.js','ttn-sideeffect-guard-v1.js'])vm.runInContext(src(f),c);c.saveRoute=()=>modal.onclick({target:{closest:sel=>sel==='[data-save]'?{}:null}});return c}
const docs=[{id:'1',key:'doc-a',number:'1001',date:'2026-09-16',senderWarehouse:'Чайки',store:'WT Київ 1',storeAddress:'Київ, вул. Тестова, 1',sourceWeight:500,sourceSumNoVat:1000,workflowStatus:'picked',status:'Скомплектовано',lines:[{name:'Товар',qty:10,priceNoVat:100,sourceSumNoVat:1000}]}];
const ticket={number:'PK-001',documentKeys:['doc-a'],store:'WT Київ 1',storeAddress:'Київ, вул. Тестова, 1',actualPallets:'2.5',pickingStatus:'completed',status:'Скомплектовано'};const fleet={carriers:[{id:'c1',name:'STV'}],drivers:[{id:'d1',name:'Водій'}],vehicles:[{id:'v1',name:'MAN',plate:'AA0001AA',emptyWeight:3000}]};
const s=storage({tc_retail_docs_v3:JSON.stringify(docs),tc_retail_tickets_v1:JSON.stringify([ticket]),tc_retail_routes_v1:'[]',tc_retail_loading_register_v1:'[]',tc_retail_ttn_journal_v1:'[]',tc_retail_fleet_v1:JSON.stringify(fleet)});let app=boot(s);
app.RetailRouteBuilderV7.open(['PK-001']);app.saveRoute();let routes=JSON.parse(s.getItem('tc_retail_routes_v1')),savedDocs=JSON.parse(s.getItem('tc_retail_docs_v3'));assert.equal(routes.length,1);assert.equal(routes[0].number,'R-001');assert.equal(savedDocs[0].workflowStatus,'routed');assert.equal(savedDocs[0].status,'У маршруті');
const storeKey='wt київ 1|київ, вул. тестова, 1';const reg={number:'REG_R-001',route:'R-001',date:'2026-09-16',warehouse:'Чайки',carrier:'STV',driver:'Водій',vehicle:'AA0001AA',tickets:['PK-001'],pallets:2.5,weight:500,seals:{[storeKey]:'SEAL-001'}};s.setItem('tc_retail_loading_register_v1',JSON.stringify([reg]));
app=boot(s);app.RetailRouteTTN.generate('R-001');let journal=JSON.parse(s.getItem('tc_retail_ttn_journal_v1'));routes=JSON.parse(s.getItem('tc_retail_routes_v1'));assert.equal(journal.length,1);assert.equal(journal[0].number,'TS_TTN_001');assert.deepEqual(journal[0].docKeys,['doc-a']);assert.equal(journal[0].loadingRegister,'REG_R-001');assert.equal(journal[0].pallets,2.5);assert.equal(journal[0].vat,200);assert.equal(journal[0].totalWithVat,1200);assert.equal(routes[0].status,'ТТН сформовано');assert.equal(routes[0].ttnCount,1);assert.ok(app.printed.includes('SEAL-001'));assert.ok(app.didPrint);
app=boot(s);journal=app.RetailState.read('tc_retail_ttn_journal_v1');routes=app.RetailState.read('tc_retail_routes_v1');assert.equal(journal.length,1,'TTN journal must survive hard reload');assert.equal(routes[0].status,'ТТН сформовано','route TTN status must survive hard reload');app.RetailRouteTTN.generate('R-001');journal=JSON.parse(s.getItem('tc_retail_ttn_journal_v1'));assert.equal(journal.length,1,'reprint must update, not duplicate TTN');assert.equal(journal[0].number,'TS_TTN_001','reprint must preserve TTN identity');
console.log('Retail full picking-route-register-TTN runtime lifecycle acceptance: PASS');
