const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.join(__dirname,'../web/retail-cloudflare'),src=n=>fs.readFileSync(path.join(root,n),'utf8');
function storage(seed={}){const m=new Map(Object.entries(seed));return{getItem:k=>m.has(k)?m.get(k):null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)}}
function boot(s){let modal=null;const control=(value='',text=value)=>({value,selectedOptions:[{textContent:text}],textContent:'',disabled:false,checked:false,matches:()=>false,closest:()=>null});const controls={date:control('2026-09-16'),from:control('wh-1','Чайки, Київська обл.'),carrier:control('c1','STV'),driver:control('d1','Тест Водій'),vehicle:control('v1','AA0001AA'),count:control(),tt:control(),pal:control(),kg:control(),sum:control()};function makeModal(){return{className:'',innerHTML:'',removed:false,remove(){this.removed=true},querySelector(sel){const f=sel.match(/^\[data-f=(.+)\]$/);if(f)return controls[f[1]];const k=sel.match(/^\[data-k=(.+)\]$/);if(k)return controls[k[1]];if(sel==='[data-count]')return controls.count;return null},querySelectorAll(){return[]},onclick:null,onchange:null}}const document={body:{appendChild(x){modal=x}},querySelector(sel){return sel==='.rb7'&&modal&&!modal.removed?modal:null},createElement(){return makeModal()}};const c={console,localStorage:s,sessionStorage:storage(),structuredClone,document,location:{hash:''},setTimeout:f=>{if(typeof f==='function')f();return 1},clearTimeout(){},Intl,Date,Promise,Error,Map,Set,alert:m=>c.alerts.push(m),alerts:[]};c.window=c;c.window.addEventListener=()=>{};c.window.dispatchEvent=()=>{};c.RetailDirectories={warehouses:()=>[{id:'wh-1',city:'Чайки',address:'Київська обл.'}]};c.RetailCanonicalStores={match:()=>null};c.RetailRoutes={render(){c.rendered=true}};vm.createContext(c);vm.runInContext(src('retail-state.js'),c);vm.runInContext(src('route-builder-v7.js'),c);c.saveRoute=()=>{if(!modal)throw Error('route modal not opened');modal.onclick({target:{closest:sel=>sel==='[data-save]'?{}:null}})};return c}
const docs=[{id:'1001',key:'doc-a',number:'1001',date:'2026-09-16',senderWarehouse:'Чайки',store:'WT Київ 1',storeAddress:'Київ, вул. Тестова, 1',sourceWeight:500,sourceSumNoVat:1000,workflowStatus:'picked',status:'Скомплектовано'}];
const ticket={number:'PK-001',documentKeys:['doc-a'],store:'WT Київ 1',storeAddress:'Київ, вул. Тестова, 1',actualPallets:'2.5',pickingStatus:'completed',status:'Скомплектовано'};
const fleet={carriers:[{id:'c1',name:'STV'}],drivers:[{id:'d1',name:'Тест Водій'}],vehicles:[{id:'v1',name:'MAN',plate:'AA0001AA'}]};
const s=storage({tc_retail_docs_v3:JSON.stringify(docs),tc_retail_tickets_v1:JSON.stringify([ticket]),tc_retail_routes_v1:JSON.stringify([]),tc_retail_fleet_v1:JSON.stringify(fleet)});
let app=boot(s);app.RetailRouteBuilderV7.open(['PK-001']);app.saveRoute();let routes=JSON.parse(s.getItem('tc_retail_routes_v1')),savedDocs=JSON.parse(s.getItem('tc_retail_docs_v3'));
assert.equal(routes.length,1,'route builder must persist one route');assert.equal(routes[0].number,'R-001');assert.deepEqual(routes[0].ticketIds,['PK-001']);assert.equal(routes[0].warehouseId,'wh-1');assert.equal(routes[0].carrierId,'c1');assert.equal(routes[0].driverId,'d1');assert.equal(routes[0].vehicleId,'v1');assert.equal(routes[0].vehicle,'AA0001AA');assert.equal(routes[0].status,'Створено');assert.equal(savedDocs[0].route,'R-001');assert.equal(savedDocs[0].workflowStatus,'routed');assert.equal(savedDocs[0].status,'У маршруті');assert.ok(app.rendered,'route workspace must rerender after save');
app=boot(s);routes=app.RetailState.read('tc_retail_routes_v1');savedDocs=app.RetailState.documents();assert.equal(routes.length,1,'route must survive hard reload');assert.equal(savedDocs[0].workflowStatus,'routed','routed document state must survive hard reload');app.RetailRouteBuilderV7.open(['PK-001']);app.saveRoute();assert.equal(JSON.parse(s.getItem('tc_retail_routes_v1')).length,1,'used ticket must not be routed twice');assert.ok(app.alerts.some(x=>String(x).includes('Оберіть хоча б одну ТТ')),'used ticket must be absent from fresh route pool');
console.log('Retail route builder runtime persistence acceptance: PASS');
