const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.join(__dirname,'../web/retail-cloudflare');
const read=n=>fs.readFileSync(path.join(root,n),'utf8');
const pick=read('picking-tickets.js')+read('picking-enhancements.js')+read('picking-group-fix.js')+read('retail-preview-fixes-v2.js');
const completed=read('completed-routing.js'),routes=read('route-builder-v7.js')+read('routes-workspace.js'),ttn=read('route-ttn-generator.js'),guard=read('ttn-sideeffect-guard-v1.js'),fin=read('retail-financial-semantics-v1.js');
const has=(s,re,msg)=>assert(re.test(s),msg);
has(pick,/printStatus/,'picking printStatus lifecycle missing');
has(pick,/pickingStatus/,'pickingStatus lifecycle missing');
has(pick,/actualPallets/,'actual pallets capture missing');
has(pick,/completionResult/,'completion result missing');
has(completed,/actualPallets/,'completed pool must carry actual pallets');
has(routes,/actualPallets/,'route builder/workspace must require actual pallets');
has(routes,/workflowStatus/,'route membership workflow state missing');
has(ttn,/loadingRegister/,'loading register linkage missing');
has(ttn,/seal/,'seal workflow missing');
has(ttn,/storeKey\(p\.store,p\.address\)/,'one TTN per canonical store identity missing');
has(ttn,/\[1,2,3\]\.map\(c=>ttn\(/,'three TTN copies missing');
has(ttn,/TS_TTN_/,'stable TTN numbering prefix missing');
has(guard,/const route=.*RetailState\.read\(R,\[\]\).*reg=.*RetailState\.read\(L,\[\]\)/,'generation must read saved route and loading register');
has(guard,/if\(!reg\)\{alert\('Спочатку сформуйте та збережіть реєстр завантаження\.'/,'generation must block without saved loading register');
has(guard,/const missing=.*reg\.seals/,'generation must validate seals');
has(guard,/if\(missing\.length\)/,'generation must block when seals are missing');
has(fin,/sourceAmountMeaning:'without_vat'/,'Excel financial meaning must be explicit');
has(fin,/sourceTotalWithVat/,'VAT-inclusive source total missing');
console.log('Retail end-to-end operational contract: PASS');
