const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.join(__dirname,'../web/retail-cloudflare'),src=n=>fs.readFileSync(path.join(root,n),'utf8');
function storage(seed={}){const m=new Map(Object.entries(seed));return{getItem:k=>m.has(k)?m.get(k):null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)}}
function boot(s){const doc={body:{append(){}},getElementById(){return null},createElement(){return{dataset:{},style:{},remove(){},querySelector(){return null},querySelectorAll(){return[]}}}};const c={console,localStorage:s,sessionStorage:storage(),structuredClone,document:doc,location:{hash:''},setTimeout:f=>{if(typeof f==='function')f();return 1},clearTimeout(){},Intl,Date,Promise,Error,Map,Set,alert:m=>c.alerts.push(m),alerts:[],editRegisterCalls:[]};c.window=c;c.window.addEventListener=()=>{};c.window.dispatchEvent=()=>{};c.window.open=()=>({document:{write:x=>{c.printed=x},close(){}},focus(){},print(){c.didPrint=true}});c.RetailDirectories={warehouses:()=>[{id:'wh-1',responsible:'Бойко Ігор Дмитрович'}]};c.RetailCanonicalStores={match:()=>null};vm.createContext(c);vm.runInContext(src('retail-state.js'),c);vm.runInContext(src('route-ttn-generator.js'),c);c.RetailRouteTTN.editRegister=no=>c.editRegisterCalls.push(no);vm.runInContext(src('ttn-sideeffect-guard-v1.js'),c);return c}
const docs=[
{id:'1',key:'a1',number:'1001',store:'WT Київ 1',storeAddress:'Київ, вул. Тестова, 1',sourceWeight:300,sourceSumNoVat:1000,workflowStatus:'routed',lines:[{name:'A',qty:10,priceNoVat:100,sourceSumNoVat:1000}]},
{id:'2',key:'a2',number:'1002',store:'WT Київ 1',storeAddress:'Київ, вул. Тестова, 1',sourceWeight:200,sourceSumNoVat:500,workflowStatus:'routed',lines:[{name:'B',qty:5,priceNoVat:100,sourceSumNoVat:500}]},
{id:'3',key:'b1',number:'2001',store:'WT Київ 2',storeAddress:'Київ, вул. Інша, 2',sourceWeight:400,sourceSumNoVat:2000,workflowStatus:'routed',lines:[{name:'C',qty:20,priceNoVat:100,sourceSumNoVat:2000}]}
];
const tickets=[
{number:'PK-001',documentKeys:['a1'],store:'WT Київ 1',storeAddress:'Київ, вул. Тестова, 1',actualPallets:'1',pickingStatus:'completed'},
{number:'PK-002',documentKeys:['a2'],store:'WT Київ 1',storeAddress:'Київ, вул. Тестова, 1',actualPallets:'0.5',pickingStatus:'completed'},
{number:'PK-003',documentKeys:['b1'],store:'WT Київ 2',storeAddress:'Київ, вул. Інша, 2',actualPallets:'2',pickingStatus:'completed'}
];
const route={number:'R-001',ticketIds:['PK-001','PK-002','PK-003'],date:'2026-09-16',warehouse:'Чайки',warehouseId:'wh-1',carrier:'STV',carrierId:'c1',driver:'Водій',driverId:'d1',vehicle:'AA0001AA',vehicleId:'v1',status:'Створено'};
const k1='wt київ 1|київ, вул. тестова, 1',k2='wt київ 2|київ, вул. інша, 2';
const reg={number:'REG_R-001',route:'R-001',date:route.date,warehouse:route.warehouse,carrier:route.carrier,driver:route.driver,vehicle:route.vehicle,tickets:route.ticketIds,pallets:3.5,weight:900,seals:{[k1]:'SEAL-1',[k2]:'SEAL-2'}};
const seed=()=>({tc_retail_docs_v3:JSON.stringify(docs),tc_retail_tickets_v1:JSON.stringify(tickets),tc_retail_routes_v1:JSON.stringify([route]),tc_retail_loading_register_v1:JSON.stringify([reg]),tc_retail_ttn_journal_v1:'[]',tc_retail_fleet_v1:JSON.stringify({vehicles:[{id:'v1',plate:'AA0001AA',emptyWeight:3000}]})});
const s=storage(seed());let app=boot(s);app.RetailRouteTTN.generate('R-001');let j=JSON.parse(s.getItem('tc_retail_ttn_journal_v1')),r=JSON.parse(s.getItem('tc_retail_routes_v1'))[0];
assert.equal(j.length,2,'three tickets for two stores must create exactly two TTNs');assert.deepEqual(j.map(x=>x.number),['TS_TTN_001','TS_TTN_002']);const a=j.find(x=>x.storeKey===k1),b=j.find(x=>x.storeKey===k2);assert.ok(a&&b,'journal must keep one record per store');assert.deepEqual(a.ticketIds,['PK-001','PK-002']);assert.deepEqual(a.docKeys,['a1','a2']);assert.equal(a.pallets,1.5);assert.equal(a.weight,500);assert.equal(a.sumNoVat,1500);assert.equal(a.vat,300);assert.equal(a.totalWithVat,1800);assert.equal(b.pallets,2);assert.equal(b.weight,400);assert.equal(b.totalWithVat,2400);assert.equal(r.ttnCount,2);assert.equal(r.loadingRegister,'REG_R-001');assert.ok(app.printed.includes('SEAL-1')&&app.printed.includes('SEAL-2'),'print package must contain both store seals');
app=boot(s);app.RetailRouteTTN.generate('R-001');j=JSON.parse(s.getItem('tc_retail_ttn_journal_v1'));assert.equal(j.length,2,'repeat generation must not duplicate store TTNs');assert.deepEqual(j.map(x=>x.number),['TS_TTN_001','TS_TTN_002'],'TTN numbers must stay stable after reload/reprint');
const partial={...reg,seals:{[k1]:'SEAL-1'}};s.setItem('tc_retail_loading_register_v1',JSON.stringify([partial]));const beforeJ=s.getItem('tc_retail_ttn_journal_v1'),beforeR=s.getItem('tc_retail_routes_v1');app=boot(s);app.RetailRouteTTN.generate('R-001');assert.ok(app.alerts.some(x=>String(x).includes('Не заповнено: 1')),'guard must identify one missing store seal');assert.deepEqual(app.editRegisterCalls,['R-001']);assert.equal(s.getItem('tc_retail_ttn_journal_v1'),beforeJ);assert.equal(s.getItem('tc_retail_routes_v1'),beforeR);assert.ok(!app.didPrint,'partial seals must block printing');
console.log('Retail multi-store TTN lifecycle runtime acceptance: PASS');
