const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.join(__dirname,'../web/retail-cloudflare'),src=n=>fs.readFileSync(path.join(root,n),'utf8');
function storage(seed={}){const m=new Map(Object.entries(seed));return{getItem:k=>m.has(k)?m.get(k):null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)}}
function boot(s,{guard=true}={}){const doc={body:{append(){}},getElementById(){return null},createElement(){return{dataset:{},style:{},remove(){},querySelector(){return null},querySelectorAll(){return[]}}}};const c={console,localStorage:s,sessionStorage:storage(),structuredClone,document:doc,location:{hash:''},setTimeout:f=>{if(typeof f==='function')f();return 1},clearTimeout(){},Intl,Date,Promise,Error,Map,Set,alert:m=>{c.alerts.push(m)},alerts:[],editRegisterCalls:[]};c.window=c;c.window.addEventListener=()=>{};c.window.dispatchEvent=()=>{};c.window.open=()=>({document:{write:x=>{c.printed=x},close(){}},focus(){},print(){c.didPrint=true}});c.RetailDirectories={warehouses:()=>[{id:'wh-1',responsible:'Бойко Ігор Дмитрович'}]};c.RetailCanonicalStores={match:()=>null};vm.createContext(c);vm.runInContext(src('retail-state.js'),c);vm.runInContext(src('route-ttn-generator.js'),c);const originalEdit=c.RetailRouteTTN.editRegister?.bind(c.RetailRouteTTN);c.RetailRouteTTN.editRegister=no=>{c.editRegisterCalls.push(no);return originalEdit?.(no)};if(guard)vm.runInContext(src('ttn-sideeffect-guard-v1.js'),c);return c}
const docs=[{id:'1001',key:'doc-a',number:'1001',store:'WT Київ 1',storeAddress:'Київ, вул. Тестова, 1',sourceWeight:500,sourceSumNoVat:1000,workflowStatus:'routed',lines:[{name:'Товар A',qty:10,priceNoVat:100,sourceSumNoVat:1000}]}];
const ticket={number:'PK-001',documentKeys:['doc-a'],store:'WT Київ 1',storeAddress:'Київ, вул. Тестова, 1',actualPallets:'2.5',pickingStatus:'completed',status:'Скомплектовано'};
const route={number:'R-001',ticketIds:['PK-001'],date:'2026-09-16',warehouse:'Чайки',warehouseId:'wh-1',carrier:'STV',carrierId:'c1',driver:'Тест Водій',driverId:'d1',vehicle:'AA0001AA',vehicleId:'v1',status:'Створено'};
const key='wt київ 1|київ, вул. тестова, 1';
const reg={number:'REG_R-001',route:'R-001',date:route.date,warehouse:route.warehouse,carrier:route.carrier,driver:route.driver,vehicle:route.vehicle,tickets:['PK-001'],pallets:2.5,weight:500,seals:{[key]:'SEAL-001'},sealTime:'12:30',sealedBy:'Комірник',receivedBy:'Тест Водій'};
const seed=()=>({tc_retail_docs_v3:JSON.stringify(docs),tc_retail_tickets_v1:JSON.stringify([ticket]),tc_retail_routes_v1:JSON.stringify([route]),tc_retail_loading_register_v1:JSON.stringify([reg]),tc_retail_ttn_journal_v1:JSON.stringify([]),tc_retail_fleet_v1:JSON.stringify({vehicles:[{id:'v1',plate:'AA0001AA',emptyWeight:3000}]})});
const s=storage(seed());
let app=boot(s);app.RetailRouteTTN.generate('R-001');
let journal=JSON.parse(s.getItem('tc_retail_ttn_journal_v1')),routes=JSON.parse(s.getItem('tc_retail_routes_v1'));
assert.equal(journal.length,1,'one store must create one TTN journal record');assert.equal(journal[0].number,'TS_TTN_001');assert.deepEqual(journal[0].docKeys,['doc-a']);assert.equal(journal[0].loadingRegister,'REG_R-001');assert.equal(journal[0].pallets,2.5);assert.equal(journal[0].vat,200);assert.equal(journal[0].totalWithVat,1200);assert.equal(routes[0].status,'ТТН сформовано');assert.equal(routes[0].ttnCount,1);assert.ok(app.printed.includes('SEAL-001'),'printed TTN must contain saved seal');assert.ok(app.didPrint,'generation must invoke print');
app=boot(s);journal=app.RetailState.read('tc_retail_ttn_journal_v1');routes=app.RetailState.read('tc_retail_routes_v1');assert.equal(journal.length,1,'TTN journal must survive hard reload');assert.equal(routes[0].loadingRegister,'REG_R-001','route/register link must survive hard reload');app.RetailRouteTTN.generate('R-001');journal=JSON.parse(s.getItem('tc_retail_ttn_journal_v1'));assert.equal(journal.length,1,'repeat generation must update, not duplicate, TTN record');assert.equal(journal[0].number,'TS_TTN_001','repeat generation must preserve TTN number');

// Missing seals: the side-effect guard must stop before generation and leave journal/route untouched.
const beforeJournal=s.getItem('tc_retail_ttn_journal_v1'),beforeRoutes=s.getItem('tc_retail_routes_v1');const broken={...reg,seals:{}};s.setItem('tc_retail_loading_register_v1',JSON.stringify([broken]));app=boot(s);app.RetailRouteTTN.generate('R-001');assert.ok(app.alerts.some(x=>String(x).includes('вкажіть номер пломби')),'guard must reject missing seals');assert.deepEqual(app.editRegisterCalls,['R-001'],'guard must redirect operator to loading register');assert.equal(s.getItem('tc_retail_ttn_journal_v1'),beforeJournal,'missing-seal guard must not mutate journal');assert.equal(s.getItem('tc_retail_routes_v1'),beforeRoutes,'missing-seal guard must not mutate route');assert.ok(!app.didPrint,'missing-seal guard must not print TTN');

// Missing register: guard must stop before the generator can create a virtual register or journal side effects.
const noReg=storage(seed());noReg.setItem('tc_retail_loading_register_v1',JSON.stringify([]));app=boot(noReg);const noRegJournal=noReg.getItem('tc_retail_ttn_journal_v1'),noRegRoutes=noReg.getItem('tc_retail_routes_v1');app.RetailRouteTTN.generate('R-001');assert.ok(app.alerts.some(x=>String(x).includes('Спочатку сформуйте та збережіть реєстр')),'guard must require a saved loading register');assert.deepEqual(app.editRegisterCalls,['R-001'],'missing register must open register editor');assert.equal(noReg.getItem('tc_retail_ttn_journal_v1'),noRegJournal,'missing-register guard must not mutate journal');assert.equal(noReg.getItem('tc_retail_routes_v1'),noRegRoutes,'missing-register guard must not mutate route');assert.ok(!app.didPrint,'missing-register guard must not print TTN');

// Unknown route: guard must fail closed without touching persisted state.
const unknown=storage(seed());app=boot(unknown);const unknownDump={j:unknown.getItem('tc_retail_ttn_journal_v1'),r:unknown.getItem('tc_retail_routes_v1'),l:unknown.getItem('tc_retail_loading_register_v1')};app.RetailRouteTTN.generate('R-404');assert.ok(app.alerts.some(x=>String(x).includes('Маршрут не знайдено')),'guard must reject unknown route');assert.equal(unknown.getItem('tc_retail_ttn_journal_v1'),unknownDump.j);assert.equal(unknown.getItem('tc_retail_routes_v1'),unknownDump.r);assert.equal(unknown.getItem('tc_retail_loading_register_v1'),unknownDump.l);assert.ok(!app.didPrint,'unknown route must not print');

console.log('Retail route TTN runtime persistence acceptance: PASS');
