const fs=require('fs'),path=require('path'),assert=require('assert');
const read=n=>fs.readFileSync(path.join(__dirname,'../web/retail-cloudflare',n),'utf8');
const fin=read('retail-financial-semantics-v1.js'),ttn=read('route-ttn-generator.js'),idx=read('index.html');
const has=(re,msg,s)=>assert(re.test(s),msg);
has(/sourceSumNoVat/,'explicit no-VAT document amount missing',fin);
has(/sourceVat/,'explicit VAT document amount missing',fin);
has(/sourceTotalWithVat/,'explicit VAT-inclusive document amount missing',fin);
has(/priceNoVat/,'unit price without VAT missing',fin);
has(/sumWithVat/,'line VAT-inclusive total missing',fin);
has(/sourceSum:r2\(base\)/,'legacy sourceSum must remain no-VAT for compatibility',fin);
has(/sourceAmountMeaning:'without_vat'/,'Excel source amount meaning must be explicit',fin);
has(/vatRate:\.2/,'VAT rate contract missing',fin);
has(/sourceSumNoVat\?\?d\.sourceSum\?\?d\.amount\?\?d\.sum/,'TTN route amount must prefer explicit no-VAT source amount',ttn);
has(/x\.priceNoVat\?\?x\.price/,'TTN unit price must prefer explicit no-VAT price',ttn);
has(/x\.sourceSumNoVat\?\?x\.amount\?\?x\.sum/,'TTN line total must prefer explicit no-VAT line amount',ttn);
has(/vat=r\(p\.sum\*\.2\)/,'TTN VAT must derive from no-VAT route amount',ttn);
has(/total=r\(p\.sum\*1\.2\)/,'TTN total must derive from no-VAT route amount',ttn);
has(/<b>Сума без ПДВ:<\/b> \$\{money\(p\.sum\)\} грн/,'TTN must label route amount as no-VAT',ttn);
has(/<b>у т\. ч\. ПДВ:<\/b> \$\{money\(vat\)\} грн/,'TTN VAT output missing',ttn);
has(/<b>на загальну суму:<\/b> \$\{money\(total\)\} грн/,'TTN VAT-inclusive total output missing',ttn);
has(/Вартість вантажу з ПДВ, грн/,'approved cargo table must expose VAT-inclusive cargo value',ttn);
has(/Ціна без ПДВ за одиницю, грн/,'approved cargo table must expose no-VAT unit price',ttn);
has(/operations-fix\.js[^<]*<\/script><script src="\.\/retail-financial-semantics-v1\.js/,'financial semantics runtime must load immediately after importer',idx);
console.log('Retail financial semantics contract: PASS');
