const assert=require('node:assert/strict');
module.exports=async({page,context,frame,handler})=>{
 const cdp=await context.newCDPSession(page);
 await cdp.send('WebAuthn.enable');
 const {authenticatorId}=await cdp.send('WebAuthn.addVirtualAuthenticator',{options:{protocol:'ctap2',transport:'internal',hasResidentKey:true,hasUserVerification:true,isUserVerified:true,automaticPresenceSimulation:true}});
 await frame.locator('#v442-nav').getByRole('button',{name:'Меню',exact:true}).click();
 for(const name of ['Профіль','Безпека','Тема','Ідеї та побажання','Користувачі та права','Довідники','Синхронізація даних','Журнал змін','Про застосунок / версія','Вийти'])assert.equal(await frame.locator('.v443-settings').getByRole('button',{name,exact:false}).count(),1);
 assert.equal(await frame.locator('header.top').getByRole('button',{name:'Вийти',exact:true}).isVisible(),false);
 await frame.locator('.v443-settings').getByRole('button',{name:'Безпека',exact:false}).click();
 await frame.locator('#v443-new-pin').fill('1234');await frame.locator('#v443-repeat-pin').fill('1234');await frame.getByRole('button',{name:'Увімкнути PIN',exact:true}).click();
 await frame.getByRole('button',{name:'Змінити PIN',exact:true}).waitFor();
 const stored=await frame.evaluate(()=>({vault:JSON.parse(localStorage.trts_vault),token:localStorage.trts_token,refresh:localStorage.trts_refresh}));
 assert.equal(stored.token,undefined);assert.equal(stored.refresh,undefined);
 assert.ok(stored.vault.cipher&&stored.vault.iv);assert.equal(JSON.stringify(stored.vault).includes('isolated-runtime-fixture'),false);assert.equal(JSON.stringify(stored.vault).includes('1234'),false);
 await frame.getByRole('button',{name:'Увімкнути біометрію',exact:true}).click();
 await frame.getByRole('button',{name:'Вимкнути біометрію',exact:true}).waitFor({timeout:20000});
 await frame.locator('#v443-old-pin').fill('1234');await frame.locator('#v443-new-pin').fill('4321');await frame.locator('#v443-repeat-pin').fill('4321');await frame.getByRole('button',{name:'Змінити PIN',exact:true}).click();
 await frame.getByRole('button',{name:'Увімкнути біометрію',exact:true}).waitFor();
 await frame.getByRole('button',{name:'Увімкнути біометрію',exact:true}).click();await frame.getByRole('button',{name:'Вимкнути біометрію',exact:true}).waitFor();
 await page.reload();await page.locator('#v443-unlock-pin').waitFor();
 assert.equal(await page.locator('#app').isVisible(),false);assert.equal(await page.evaluate(()=>localStorage.trts_token),undefined);
 await page.locator('#v443-unlock-pin').fill('1234');await page.getByRole('button',{name:'Розблокувати',exact:true}).click();
 await page.waitForFunction(()=>document.getElementById('v443-unlock-error')?.textContent.includes('Невірний PIN'));
 await page.locator('#v443-unlock-pin').fill('4321');await page.getByRole('button',{name:'Розблокувати',exact:true}).click();await page.locator('[data-summary=local]').waitFor();
 await page.reload();await page.getByRole('button',{name:'Face ID / Touch ID / захист пристрою',exact:true}).click();await page.locator('[data-summary=local]').waitFor({timeout:20000});
 await page.locator('#v442-nav').getByRole('button',{name:'Меню',exact:true}).click();await page.locator('.v443-settings').getByRole('button',{name:'Тема',exact:true}).click();await page.locator('#v443-theme').selectOption('light');
 assert.equal(await page.locator('html').getAttribute('data-theme'),'light');await page.locator('#v443-theme').selectOption('dark');
 const forbidden=await handler(new Request('https://security.test',{method:'POST',headers:{Origin:'https://evil.example','Content-Type':'application/json'},body:JSON.stringify({action:'enroll',pin:'1234',secret:'x'.repeat(43)})}));
 assert.equal(forbidden.status,403);
 const unauth=await handler(new Request('https://security.test',{method:'POST',headers:{Origin:'https://transport-report-ts-web.pages.dev','Content-Type':'application/json'},body:JSON.stringify({action:'enroll',pin:'1234',secret:'x'.repeat(43)})}));
 assert.equal(unauth.status,400);
 await cdp.send('WebAuthn.removeVirtualAuthenticator',{authenticatorId});
 console.log('PASS quick unlock: AES-GCM session ciphertext only, PIN setup/change/old-PIN rejection, reload lock, real virtual platform credential registration/assertion verified by production Edge handler, themes, admin Menu, denied origin and missing authentication');
};
