const assert=require('node:assert/strict');
module.exports=async({page,pickDate,capture})=>{
 await page.evaluate(async()=>{v441HomeTab('logistics');await v43SetPeriod('today');db.cube_imports=[{id:1,status:'completed',imported_at:'2026-09-01T06:52:14.720Z',details:{start_date:'2026-09-01',end_date:'2026-09-01'}}];await v435Refresh()});
 await page.locator('.v431-fop').waitFor({state:'visible'});
 await page.locator('#v431-courier').waitFor({state:'attached'});
 const writes=await page.evaluate(()=>window.writes.length);
 const financeBefore=await page.evaluate(()=>({facts:JSON.stringify(D.facts),entries:JSON.stringify(db.fleet_cost_entries),rates:JSON.stringify(db.transport_monthly_rates),inter:JSON.stringify(db.stv_interbranch_months),costs:D.routes.map(r=>TRTS_OPS.metrics(r).cost)}));
 assert.equal(await page.locator('.v441-home-tabs [role=tab]').count(),2);
 assert.equal(await page.locator('#v441-logistics-panel .v431-block').count(),7);
 assert.equal(await page.locator('[data-section="stv"] .v44-inter-subblock').count(),0);
 assert.doesNotMatch(await page.locator('[data-section="stv"]').innerText(),/Міжфілійна доставка/);
 assert.equal(await page.locator('#v441-import-time time').getAttribute('datetime'),'2026-09-01T06:52:14.720Z');
 assert.match(await page.locator('#v441-import-time').innerText(),/01\.09\.2026/);
 await capture('v441-logistics-home');
 await page.getByRole('tab',{name:/Витрати та тарифи/}).click();
 assert.equal(await page.locator('#v441-logistics-panel').isVisible(),false);
 assert.equal(await page.locator('#v441-finance-panel button').count(),4);
 await capture('v441-finance-home');
 for(const [label,content] of [['Власний парк','#v44-period-month'],['Тариф SAV','#v44-rate-form'],['Тариф STV','#v44-rate-form'],['STV міжфілійна доставка','#v44-inter-month']]){
  await page.locator('#v441-finance-panel').getByRole('button',{name:new RegExp(label)}).click();
  await page.locator(content).waitFor({state:'visible'});
  assert.equal(await page.locator('.v441-cost-tabs button').count(),4);
  assert.equal(await page.locator('.v441-cost-tabs [aria-current=page]').count(),1);
  await page.getByRole('button',{name:'‹ Витрати та тарифи',exact:true}).click();
  await page.locator('#v441-finance-panel').waitFor({state:'visible'});
 }
 assert.deepEqual(await page.evaluate(()=>({facts:JSON.stringify(D.facts),entries:JSON.stringify(db.fleet_cost_entries),rates:JSON.stringify(db.transport_monthly_rates),inter:JSON.stringify(db.stv_interbranch_months),costs:D.routes.map(r=>TRTS_OPS.metrics(r).cost)})),financeBefore);
 assert.equal(await page.evaluate(()=>window.writes.length),writes,'Navigation must not change any financial record');
 await page.getByRole('tab',{name:/Логістичний блок/}).click();
 await page.getByRole('tab',{name:/Логістичний блок/}).press('ArrowRight');
 assert.equal(await page.getByRole('tab',{name:/Витрати та тарифи/}).getAttribute('aria-selected'),'true');
 await page.getByRole('tab',{name:/Витрати та тарифи/}).press('Home');
 assert.equal(await page.getByRole('tab',{name:/Логістичний блок/}).getAttribute('aria-selected'),'true');
 await page.locator('#v43-period').getByRole('button',{name:'Дата',exact:true}).click();
 await pickDate('v441-date','2026-01-01');
 await page.locator('#v441-date-form').getByRole('button',{name:'Показати',exact:true}).click();
 await page.waitForSelector('.v43-loading',{state:'hidden'});
 assert.deepEqual(await page.evaluate(()=>v435ReportPeriod()),{from:'2026-01-01',to:'2026-01-01'});
 assert.equal(await page.locator('#v435-period-range').innerText(),'01.01.2026');
 await page.locator('#v43-period').getByRole('button',{name:'Оновити дані',exact:true}).click();
 await page.locator('#v43-modal').getByRole('button',{name:'Період',exact:true}).click();
 await pickDate('v441-refresh-from','2026-01-02');await pickDate('v441-refresh-to','2026-01-01');
 await page.locator('#v441-refresh-submit').click();
 assert.match(await page.locator('#v441-refresh-error').innerText(),/пізнішою/);
 await pickDate('v441-refresh-from','2026-01-01');await pickDate('v441-refresh-to','2026-01-02');
 await capture('v441-data-refresh');
 const previousTime=await page.locator('#v441-loaded-time time').getAttribute('datetime');
 await page.evaluate(()=>window.failRead='source_documents');await page.locator('#v441-refresh-submit').click();
 await page.waitForFunction(()=>document.querySelector('#v441-refresh-error').textContent.includes('Тестова помилка'));
 assert.equal(await page.locator('#v441-loaded-time time').getAttribute('datetime'),previousTime,'Failure must not advance last success');
 assert.equal(await page.locator('#v441-refresh-from').inputValue(),'2026-01-01');
 await page.locator('#v441-refresh-submit').click();await page.waitForFunction(()=>!document.body.classList.contains('trts-modal-open'));
 assert.deepEqual(await page.evaluate(()=>v435ReportPeriod()),{from:'2026-01-01',to:'2026-01-02'});
 assert.notEqual(await page.locator('#v441-loaded-time time').getAttribute('datetime'),previousTime);
 assert.equal(await page.locator('#v441-import-time time').getAttribute('datetime'),'2026-09-01T06:52:14.720Z','Rereading never fabricates an Excel import time');
 await page.locator('#v43-period').getByRole('button',{name:'Оновити дані',exact:true}).click();
 await page.locator('#v43-modal').getByRole('button',{name:'Одна дата',exact:true}).click();await pickDate('v441-refresh-from','2026-01-02');
 await page.locator('#v441-refresh-submit').click();await page.waitForFunction(()=>!document.body.classList.contains('trts-modal-open'));
 assert.deepEqual(await page.evaluate(()=>v435ReportPeriod()),{from:'2026-01-02',to:'2026-01-02'});
 assert.equal(await page.locator('#v441-date-form').isVisible(),true);
 await page.evaluate(async()=>{window.failRead='cube_imports';await v435Refresh()});assert.match(await page.locator('#v441-import-time').innerText(),/час недоступний/);
 await page.evaluate(async()=>{db.cube_imports=[];await v43SetPeriod('today')});assert.match(await page.locator('#v441-import-time').innerText(),/немає підтвердженого імпорту/);
 for(const width of [320,390,760]){await page.setViewportSize({width,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No horizontal overflow at '+width);await page.getByRole('tab',{name:/Витрати та тарифи/}).click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Finance grid overflow at '+width);await page.getByRole('tab',{name:/Логістичний блок/}).click()}
 await page.setViewportSize({width:390,height:740});
 assert.equal(await page.evaluate(()=>window.writes.length),writes,'Date and refresh controls are read-only');
 console.log('PASS v44.1 shell: two sections, all subblocks, relocated STV, single date, refresh range/retry/status, exact import time, no financial mutations, mobile layout');
};
