(()=>{
const esc=typeof E==='function'?E:s=>String(s??'');
const fmt=n=>new Intl.NumberFormat('uk-UA',{maximumFractionDigits:3}).format(Number(n)||0);
const money=n=>new Intl.NumberFormat('uk-UA',{maximumFractionDigits:0}).format(Number(n)||0)+' грн';
const dm=s=>{const a=String(s||'').split('-');return a.length===3?`${a[2]}.${a[1]}`:s};
const getRoute=id=>(D.routes||[]).find(r=>Number(r.id)===Number(id));
const getFact=id=>(D.facts||[]).find(f=>Number(f.route_id)===Number(id))||{};
const pts=id=>(D.points||[]).filter(p=>Number(p.route_id)===Number(id));
const docs=r=>{const m=new Map();for(const d of (D.docs||[]).filter(x=>String(x.route_delivery_id)===String(r.route_delivery_id))){const k=`${d.sale_code||d.operation_code||d.id}|${d.address_id||''}|${d.customer_id||''}`;if(!m.has(k))m.set(k,d)}return [...m.values()]};
const nums=r=>{const p=pts(r.id),ds=docs(r);return{tt:p.length||Number(r.total_points)||0,docs:ds.length||Number(r.total_documents)||0,pal:p.length?p.reduce((s,x)=>s+(+x.pallets||0),0):Number(r.total_pallets)||0,sales:ds.length?ds.reduce((s,x)=>s+(+x.order_amount||0),0):Number(r.total_order_amount)||0}};
const isSpecial=f=>/^(sav|stv)$/i.test(String(f.carrier_name||'').trim());
const carrier=f=>String(f.carrier_name||'').trim();
const datesSelected=new Set();
let dateFilterMounted=false;

const st=document.createElement('style');st.textContent=`
:root{--log-accent:#5f7cff;--log-accent2:#41c7b5;--log-glow:#6f8cff22}
html[data-tr-theme="dark"]{--bg:#0b0f15;--card:#121821;--soft:#18212c;--line:#263241;--ink:#f3f6fa;--muted:#8e9aab;--accent:#6f8cff}
html[data-tr-theme="dark"] body{background:radial-gradient(circle at 15% -15%,#1a2942 0,transparent 31%),radial-gradient(circle at 90% 5%,#12312f 0,transparent 24%),linear-gradient(180deg,#0b0f15 0,#0d1219 48%,#090d12 100%)!important;background-attachment:fixed!important}
html[data-tr-theme="dark"] .top{background:rgba(10,15,22,.86)!important;border-bottom:1px solid #ffffff0d!important;backdrop-filter:blur(22px)!important;box-shadow:0 14px 40px #0005!important}
html[data-tr-theme="light"] body{background:radial-gradient(circle at 10% -15%,#dce5ff 0,transparent 32%),radial-gradient(circle at 92% 0,#dff8f3 0,transparent 25%),linear-gradient(180deg,#f7f9fc,#eef2f7)!important;background-attachment:fixed!important}
.pro-route:before{background:linear-gradient(180deg,var(--log-accent),var(--log-accent2))!important}.pro-save{background:linear-gradient(135deg,var(--log-accent),#4966de)!important}.pro-badge.warn{background:#2a2335!important;color:#c7b9ff!important}.pro-badge.ok{background:#18342f!important;color:#8ee0cd!important}.pro-badge.carrier{background:#1d2734!important;color:#dce6f5!important}
.log-toolbar{display:grid;gap:9px;margin:12px 0 15px}.log-filter-btn{width:100%;min-height:46px;border:1px solid var(--line);border-radius:15px;background:var(--card);color:var(--ink);padding:11px 13px;font-weight:900;display:flex;justify-content:space-between;align-items:center}.log-date-panel{display:none;border:1px solid var(--line);background:var(--card);border-radius:17px;padding:10px;box-shadow:0 20px 50px #0004}.log-date-panel.open{display:block}.log-date-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}.log-date-chip{display:flex;align-items:center;justify-content:center;gap:6px;border:1px solid var(--line);border-radius:11px;padding:9px 6px;font-size:10px;font-weight:900;background:var(--soft)}.log-date-chip input{accent-color:var(--log-accent)}.log-date-actions{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:9px}.log-date-actions button{border:0;border-radius:11px;padding:10px;font-weight:900}.log-clear{background:var(--soft);color:var(--ink)}.log-done{background:var(--log-accent);color:white}
.log-section-title{display:flex;align-items:center;justify-content:space-between;margin:18px 2px 9px}.log-section-title h3{margin:0;font-size:13px;color:var(--muted);text-transform:uppercase;letter-spacing:.08em}.route-date-chip{font-size:10px;font-weight:900;color:var(--muted)}
.log-carrier-empty{background:var(--soft);color:var(--muted)}.special-strip{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.special-pill{border-radius:999px;padding:6px 9px;font-size:9px;font-weight:950;background:#1b2e3d;color:#a8d8ff}.special-pill.missing{background:#352a1c;color:#ffd795}
.sav-head{display:grid;gap:9px}.sav-info{display:grid;grid-template-columns:1fr 1fr;gap:8px}.sav-card{border:1px solid var(--line);background:var(--card);border-radius:18px;padding:14px;margin-top:9px}.sav-card.missing{border-color:#6f5934}.sav-card-top{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.sav-card h4{margin:0;font-size:14px}.sav-address{font-size:10px;color:var(--muted);line-height:1.45;margin-top:4px}.sav-zone{font-size:11px;font-weight:950;padding:6px 8px;border-radius:999px;background:#16312d;color:#87dfcb;white-space:nowrap}.sav-zone.missing{background:#362b1c;color:#ffd38d}.sav-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:7px;margin-top:10px}.sav-metric{border-radius:11px;background:var(--soft);padding:9px}.sav-metric span{display:block;font-size:8px;color:var(--muted);font-weight:850}.sav-metric b{display:block;margin-top:3px;font-size:11px}.sav-total{margin-top:11px;padding:12px;border-radius:14px;background:linear-gradient(135deg,#17293a,#18352f);display:flex;justify-content:space-between;align-items:center}.sav-total span{font-size:10px;color:#a9b5c4}.sav-total b{font-size:17px}.carrier-chooser{display:grid;grid-template-columns:1fr auto;gap:7px;margin-top:12px}.carrier-chooser select{width:100%;border:1px solid var(--line);border-radius:13px;background:var(--card);color:var(--ink);padding:11px}.carrier-chooser button{border:0;border-radius:13px;padding:0 13px;background:var(--log-accent);color:white;font-weight:950}
@media(max-width:430px){.log-date-grid{grid-template-columns:repeat(2,1fr)}.sav-info,.sav-grid{grid-template-columns:1fr 1fr}}
`;
document.head.appendChild(st);

function allDates(){return [...new Set((D.routes||[]).map(r=>r.route_date).filter(Boolean))].sort()}
function mountDateFilter(){const host=document.querySelector('.filters');if(!host)return;let box=document.getElementById('logDateFilter29');if(box)return;box=document.createElement('div');box.id='logDateFilter29';box.className='log-toolbar';host.appendChild(box);renderDateFilter()}
function renderDateFilter(){const box=document.getElementById('logDateFilter29');if(!box)return;const ds=allDates();box.innerHTML=`<button class="log-filter-btn" id="logDatesBtn"><span>${datesSelected.size?`Обрано дат: ${datesSelected.size}`:'Дати для заповнення'}</span><span>⌄</span></button><div class="log-date-panel" id="logDatesPanel"><div class="log-date-grid">${ds.map(d=>`<label class="log-date-chip"><input type="checkbox" value="${d}" ${datesSelected.has(d)?'checked':''}><span>${dm(d)}</span></label>`).join('')||'<div class="note">У завантаженому періоді немає дат</div>'}</div><div class="log-date-actions"><button class="log-clear" id="logDatesClear">Всі дати</button><button class="log-done" id="logDatesDone">Готово</button></div></div>`;const p=box.querySelector('#logDatesPanel');box.querySelector('#logDatesBtn').onclick=()=>p.classList.toggle('open');box.querySelector('#logDatesClear').onclick=()=>{datesSelected.clear();renderDateFilter();logistics()};box.querySelector('#logDatesDone').onclick=()=>{datesSelected.clear();box.querySelectorAll('input[type=checkbox]:checked').forEach(x=>datesSelected.add(x.value));p.classList.remove('open');renderDateFilter();logistics()}}

function visibleRoutes(){return (D.routes||[]).filter(r=>!datesSelected.size||datesSelected.has(r.route_date))}
function card(r){const f=getFact(r.id),n=nums(r),c=carrier(f),special=isSpecial(f),cp=(D.costPoints||[]).filter(x=>Number(x.route_id)===Number(r.id)),missing=special&&cp.some(x=>x.zone==null);return `<div class="route-card-v19 pro-route" data-route-id="${r.id}" data-warehouse="${esc(r.warehouse||'Без складу')}"><input class="route-select pro-check" type="checkbox" data-group-route="${r.id}"><div class="pro-hero"><div><div class="pro-title">Маршрут ${esc(r.route_delivery_id||r.id)}</div><div class="pro-sub">${esc(r.expeditor_name||'—')}<br><span class="pro-wh">${esc(r.warehouse||'—')}</span></div></div><div class="pro-badges"><span class="route-date-chip">${dm(r.route_date)}</span><span class="pro-badge ${c?'carrier':'log-carrier-empty'}">${esc(c||'Перевізник не заданий')}</span></div></div><div class="pro-route-grid"><div class="pro-stat"><span>ТТ / адреси</span><b>${n.tt}</b></div><div class="pro-stat"><span>Документи</span><b>${n.docs}</b></div><div class="pro-stat"><span>Палети</span><b>${fmt(n.pal)}</b></div><div class="pro-stat"><span>Сума</span><b>${money(n.sales)}</b></div></div>${special?`<div class="special-strip"><span class="special-pill">${esc(c)}</span><span class="special-pill">Тариф по ТТ</span>${missing?'<span class="special-pill missing">Є ТТ без зони</span>':''}</div>`:`<div class="pro-op"><div class="pro-stat"><span>Хвиля</span><b>${esc(f.wave||'—')}</b></div><div class="pro-stat"><span>Водій</span><b>${esc(f.driver_name||'—')}</b></div><div class="pro-stat"><span>Авто</span><b>${esc(f.vehicle_number||'—')}</b></div><div class="pro-stat"><span>Тариф</span><b>${f.tariff==null?'—':money(f.tariff)}</b></div></div>`}<div class="pro-open"><span>Відкрити маршрут</span><b>›</b></div></div>`}

logistics=function(){const rs=visibleRoutes(),by={};for(const r of rs){const k=r.warehouse||'Без складу';(by[k]??=[]).push(r)}view.innerHTML=`<div class="head"><div><h2 style="margin-bottom:4px">Логістика</h2><div class="note">Заповнення маршрутів і контроль тарифів</div></div><span class="tag">${rs.length}</span></div>`+Object.entries(by).map(([wh,rows])=>`<div class="warehouse-group"><div class="warehouse-head"><div><h3>${esc(wh)}</h3><div class="group-note">${rows.length} маршрутів · ${rows.reduce((s,r)=>s+nums(r).tt,0)} ТТ</div></div></div>${rows.sort((a,b)=>String(a.route_date).localeCompare(String(b.route_date))).map(card).join('')}</div>`).join('');mountDateFilter();setTimeout(()=>{if(typeof mountMultiWarehouse==='function')try{mountMultiWarehouse()}catch{}},0)};

function carrierOptions(selected){const arr=(D.carriers||[]);return '<option value="">— Обрати перевізника —</option>'+arr.map(x=>`<option value="${esc(x.name)}" ${x.name===selected?'selected':''}>${esc(x.name)}</option>`).join('')}
async function setCarrier(id){const v=document.getElementById('manualCarrier29')?.value||'';if(!v)return alert('Оберіть перевізника');const f=getFact(id);await api('/rest/v1/route_facts?on_conflict=route_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify([{route_id:id,carrier_name:v,wave:f.wave||null,driver_name:f.driver_name||null,vehicle_number:f.vehicle_number||null,tariff:f.tariff??null,tariff_group_id:f.tariff_group_id||null,tariff_unknown:false}])});await loadAll();routeCard(id)}
window.setCarrier29=setCarrier;

async function renderSavStv(id){const host=document.getElementById('savStvBody29');if(!host)return;try{const rows=await api(`/rest/v1/transport_point_costs_v1?select=*&route_id=eq.${id}&order=route_point_id`);if(!rows.length){host.innerHTML='<div class="sav-card missing"><b>Тарифні дані ще не знайдено</b><div class="note" style="margin-top:5px">Оновіть дані після призначення перевізника.</div></div>';return}const total=rows.reduce((s,x)=>s+(+x.effective_cost||0),0),missing=rows.filter(x=>x.zone==null).length;host.innerHTML=`<div class="sav-info"><div class="pro-stat"><span>ТТ</span><b>${rows.length}</b></div><div class="pro-stat"><span>Без зони</span><b>${missing}</b></div></div>${rows.map((x,i)=>`<div class="sav-card ${x.zone==null?'missing':''}"><div class="sav-card-top"><div><h4>${i+1}. ${esc(x.customer_name||'Торгова точка')}</h4><div class="sav-address">${esc(x.delivery_address||'—')}</div></div><span class="sav-zone ${x.zone==null?'missing':''}">${x.zone==null?'Зону не знайдено':'Зона '+esc(x.zone)}</span></div><div class="sav-grid"><div class="sav-metric"><span>Філія покриття</span><b>${esc(x.tariff_branch||'—')}</b></div><div class="sav-metric"><span>Тариф за ТТ</span><b>${x.tt_fixed==null?'—':money(x.tt_fixed)}</b></div><div class="sav-metric"><span>Палети</span><b>${fmt(x.pallets)}</b></div><div class="sav-metric"><span>Тариф палети</span><b>${x.pallet_tariff==null?'—':money(x.pallet_tariff)}</b></div></div><div class="sav-total"><span>Вартість ТТ</span><b>${x.effective_cost==null?'Не розраховано':money(x.effective_cost)}</b></div></div>`).join('')}<div class="sav-total"><span>Разом по маршруту</span><b>${money(total)}</b></div>`}catch(e){host.innerHTML=`<div class="sav-card missing">Помилка тарифних даних: ${esc(e.message)}</div>`}}

const oldRouteCard29=routeCard;
routeCard=function(id){const r=getRoute(id);if(!r)return oldRouteCard29(id);const f=getFact(id),c=carrier(f),special=isSpecial(f),n=nums(r);if(!c){view.innerHTML=`<button class="btn back" onclick="logistics()">← Маршрути</button><div class="pro-section section"><div class="pro-title">Маршрут ${esc(r.route_delivery_id||r.id)}</div><div class="pro-sub">${dm(r.route_date)} · ${esc(r.warehouse||'—')}<br>${esc(r.expeditor_name||'—')}</div><div class="pro-route-grid" style="margin-top:12px"><div class="pro-stat"><span>ТТ</span><b>${n.tt}</b></div><div class="pro-stat"><span>Палети</span><b>${fmt(n.pal)}</b></div></div><h3 style="margin:15px 0 6px">Призначити перевізника</h3><div class="note">Автопідстановку вимкнено. Перевізника задаєш вручну.</div><div class="carrier-chooser"><select id="manualCarrier29">${carrierOptions('')}</select><button onclick="setCarrier29(${id})">Зберегти</button></div></div>`;return}
if(special){view.innerHTML=`<button class="btn back" onclick="logistics()">← Маршрути</button><div class="pro-section section sav-head"><div class="pro-hero"><div><div class="pro-title">Маршрут ${esc(r.route_delivery_id||r.id)}</div><div class="pro-sub">${dm(r.route_date)} · ${esc(r.warehouse||'—')}<br>${esc(r.expeditor_name||'—')}</div></div><span class="pro-badge carrier">${esc(c)}</span></div><div class="note">Для ${esc(c)} показуємо тільки тарифну логіку по торгових точках.</div><div id="savStvBody29"></div></div>`;renderSavStv(id);return}
oldRouteCard29(id);
};

const oldGo29=go;go=function(...args){const out=oldGo29(...args);setTimeout(()=>{if(page==='logistics')mountDateFilter()},0);return out};
})();