(()=>{
const P=n=>new Intl.NumberFormat('uk-UA',{minimumFractionDigits:0,maximumFractionDigits:3}).format(Number(n)||0);
const css=`
.data-controls{display:flex;gap:8px;flex-wrap:wrap;align-items:center;width:100%}.data-controls select,.data-controls input{padding:10px 11px;border:1px solid var(--line);border-radius:11px;background:#fff;min-height:42px}.data-controls select{min-width:150px}.period-title{font-size:11px;color:var(--muted);font-weight:800}.warehouse-group{margin-top:18px}.warehouse-head{display:flex;justify-content:space-between;gap:10px;align-items:center;margin-bottom:9px}.warehouse-head h3{margin:0}.date-group{margin-top:16px}.date-label{font-size:13px;font-weight:900;margin-bottom:8px}.route-card-v19{max-width:820px;margin:0 auto 9px;background:#fff;border:1px solid var(--line);border-radius:17px;padding:14px;box-shadow:0 5px 18px #00000009;cursor:pointer}.route-card-v19 .route-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px;margin-top:11px}.mini-stat{background:#f7f8fa;border-radius:10px;padding:8px;min-width:0}.mini-stat span{display:block;font-size:9px;color:var(--muted);font-weight:800}.mini-stat b{display:block;font-size:12px;margin-top:3px;word-break:break-word}.address-list{display:grid;gap:9px;margin-top:12px}.address-card{background:#fff;border:1px solid var(--line);border-radius:16px;padding:13px}.address-name{font-size:15px;font-weight:900}.address-text{font-size:12px;color:var(--muted);line-height:1.4;margin-top:4px}.doc-stack{display:grid;gap:7px;margin-top:10px}.doc-mini{background:#f7f8fa;border-radius:12px;padding:10px}.doc-mini-top{display:flex;justify-content:space-between;gap:10px}.doc-mini-top b{font-size:13px}.doc-mini-meta{font-size:10px;color:var(--muted);margin-top:5px;line-height:1.45}.fact-editor{max-width:820px;margin:12px auto;background:#fff;border:1px solid var(--line);border-radius:17px;padding:14px}.fact-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.fact-field label{display:block;font-size:10px;font-weight:800;color:var(--muted);margin-bottom:4px}.fact-row{display:flex;gap:6px}.fact-row select,.fact-row input{width:100%;min-width:0;padding:10px;border:1px solid var(--line);border-radius:10px;background:#fff}.add-mini{flex:0 0 42px;border:1px solid var(--line);background:#fff;border-radius:10px;font-weight:900;cursor:pointer}.fact-actions{display:flex;gap:8px;margin-top:11px}.route-detail-head{max-width:820px;margin:0 auto}.empty-note{padding:13px;border:1px dashed var(--line);border-radius:13px;color:var(--muted);font-size:12px}.group-note{font-size:11px;color:var(--muted);margin-top:4px}
@media(max-width:650px){.data-controls>*{flex:1 1 140px}.data-controls .btn{flex:0 0 auto}.route-card-v19{padding:13px}.route-card-v19 .route-summary{grid-template-columns:1fr 1fr}.fact-grid{grid-template-columns:1fr}.warehouse-head{align-items:flex-start}.doc-mini-top{align-items:flex-start}}
`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);

const state={period:'today',from:null,to:null,warehouse:'all',all:null};
const today=()=>{const d=new Date(),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),dd=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${dd}`};
const shift=(iso,n)=>{const d=new Date(iso+'T12:00:00');d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
const monday=iso=>{const d=new Date(iso+'T12:00:00'),x=(d.getDay()+6)%7;d.setDate(d.getDate()-x);return d.toISOString().slice(0,10)};
const dmy=iso=>{const a=String(iso||'').split('-');return a.length===3?`${a[2]}.${a[1]}`:String(iso||'')};
const chunks=(a,n=120)=>{const out=[];for(let i=0;i<a.length;i+=n)out.push(a.slice(i,i+n));return out};
async function manyByIn(pathPrefix,field,vals){if(!vals.length)return[];let out=[];for(const c of chunks(vals)){const q=encodeURIComponent('('+c.map(v=>typeof v==='number'?v:'"'+String(v).replaceAll('"','')+'"').join(',')+')');out.push(...await api(pathPrefix+field+'=in.'+q))}return out}
function ensureControls(){const f=document.querySelector('.filters');if(!f)return;f.innerHTML=`<div class="data-controls"><select id="periodSel"><option value="today">Сьогодні</option><option value="yesterday">Вчора</option><option value="week">Поточний тиждень</option><option value="calendar">Календар</option></select><input id="date" type="date"><select id="warehouseSel"><option value="all">Всі склади</option></select><button class="btn" id="reloadBtn">Оновити</button><span id="dataTag" class="tag"></span></div>`;periodSel.value=state.period;date.value=state.from||today();periodSel.onchange=()=>{state.period=periodSel.value;if(state.period==='calendar')date.focus();loadAll()};date.onchange=()=>{state.period='calendar';periodSel.value='calendar';loadAll()};warehouseSel.onchange=()=>{state.warehouse=warehouseSel.value;applyWarehouse();go(page)};reloadBtn.onclick=()=>loadAll()}
function resolveRange(){const t=today();if(state.period==='yesterday')return[shift(t,-1),shift(t,-1)];if(state.period==='week'){const m=monday(t);return[m,shift(m,6)]}if(state.period==='calendar'){const d=document.getElementById('date')?.value||t;return[d,d]}return[t,t]}
function uniqDocs(docs){const m=new Map();for(const d of docs){const key=String(d.sale_code||d.operation_code||d.id)+'|'+String(d.address_id||'')+'|'+String(d.customer_id||'');const cur=m.get(key);if(!cur||(+d.order_amount||0)>(+cur.order_amount||0))m.set(key,d)}return [...m.values()]}
function routeDocs(r){return uniqDocs((state.all?.docs||D.docs||[]).filter(d=>String(d.route_delivery_id)===String(r.route_delivery_id)))}
function routeSales(r){return routeDocs(r).reduce((s,d)=>s+(+d.order_amount||0),0)}
function locForPoint(p){return (state.all?.locations||D.locations||[]).find(l=>String(l.id)===String(p.location_id))}
function addressKeyFromDoc(d){return String(d.address_id||'addr:'+String(d.delivery_address||'').trim().toLowerCase()+'|'+String(d.customer_id||''))}
function addressGroups(r){const points=(state.all?.points||D.points||[]).filter(p=>p.route_id===r.id),docs=routeDocs(r),map=new Map();
 for(const p of points){const l=locForPoint(p),key=String(l?.address_id||'loc:'+p.location_id);map.set(key,{key,point:p,location:l,docs:[],name:p.customer_name||l?.customer_name||'—',address:l?.delivery_address||'',employee:'',business:''})}
 for(const d of docs){const dk=addressKeyFromDoc(d);let g=map.get(dk);if(!g&&d.address_id){g=[...map.values()].find(x=>String(x.location?.address_id||'')===String(d.address_id))}if(!g){g=[...map.values()].find(x=>x.point?.customer_id&&String(x.point.customer_id)===String(d.customer_id)&&(!x.address||x.address===d.delivery_address))}if(!g){g={key:dk,point:null,location:null,docs:[],name:d.customer_name||'—',address:d.delivery_address||'',employee:'',business:''};map.set(dk,g)}g.docs.push(d);g.address=g.address||d.delivery_address||'';g.name=g.name==='—'?(d.customer_name||'—'):g.name}
 for(const g of map.values()){g.docs=uniqDocs(g.docs);g.employee=[...new Set(g.docs.map(x=>x.employee_id).filter(Boolean))].join(', ');g.business=[...new Set(g.docs.map(x=>business(x.business_unit)).filter(Boolean))].join(', ')}return [...map.values()]}
function routeTT(r){return addressGroups(r).length}
function routePal(r){return (state.all?.points||D.points||[]).filter(p=>p.route_id===r.id).reduce((s,p)=>s+(+p.pallets||0),0)}
function selectedFacts(){return state.all?.facts||D.facts||[]}
function factFor(id){return selectedFacts().find(f=>f.route_id===id)||{}}
function carrierFor(r){const f=factFor(r.id);if(f.carrier_name)return f.carrier_name;return (state.all?.autoCarriers||[]).find(a=>a.expeditor_name===r.expeditor_name)?.auto_carrier||''}
function defaultFor(r){return (state.all?.defaults||[]).find(x=>x.expeditor_name===r.expeditor_name)||{}}
function listOptions(arr,value,labelFn=x=>x.name){return `<option value="">— Обрати —</option>`+arr.map(x=>`<option value="${E(String(value(x)))}">${E(String(labelFn(x)))}</option>`).join('')}
function setSelect(id,val){const el=document.getElementById(id);if(el&&val!=null)el.value=String(val)}
function renderWarehouseOptions(){const el=document.getElementById('warehouseSel');if(!el||!state.all)return;const ws=[...new Set(state.all.routes.map(r=>r.warehouse||'Без складу'))].sort((a,b)=>a.localeCompare(b,'uk'));el.innerHTML='<option value="all">Всі склади</option>'+ws.map(w=>`<option value="${E(w)}">${E(w)}</option>`).join('');if(!ws.includes(state.warehouse))state.warehouse='all';el.value=state.warehouse}
function applyWarehouse(){if(!state.all)return;const ids=new Set(state.all.routes.filter(r=>state.warehouse==='all'||(r.warehouse||'Без складу')===state.warehouse).map(r=>r.id));D={...state.all,routes:state.all.routes.filter(r=>ids.has(r.id)),points:state.all.points.filter(x=>ids.has(x.route_id)),facts:state.all.facts.filter(x=>ids.has(x.route_id)),alloc:state.all.alloc.filter(x=>ids.has(state.all.points.find(p=>p.id===x.route_point_id)?.route_id)),docs:state.all.docs.filter(d=>D.routes.some(r=>String(r.route_delivery_id)===String(d.route_delivery_id))),costPoints:state.all.costPoints.filter(x=>ids.has(x.route_id))}}

loadAll=async function(){try{ensureControls();const [from,to]=resolveRange();state.from=from;state.to=to;date.value=state.period==='calendar'?from:from;dataTag.textContent=`Реальні дані · ${dmy(from)}${from!==to?'–'+dmy(to):''}`;
 const [routes,manual,autoCarriers,waves,drivers,vehicles,carriers,defaults]=await Promise.all([
  api(`/rest/v1/routes?select=id,route_date,route_delivery_id,expeditor_name,warehouse,total_points,total_documents,total_weight,total_pallets,total_order_amount&route_date=gte.${from}&route_date=lte.${to}&order=route_date,warehouse,route_delivery_id`),
  api(`/rest/v1/manual_transport_entries?select=*&entry_date=gte.${from}&entry_date=lte.${to}&order=entry_date,created_at.desc`),
  api('/rest/v1/expeditor_auto_carrier?select=expeditor_name,auto_carrier&active=eq.true'),
  api('/rest/v1/transport_waves?select=id,name,uses_vt&active=eq.true&order=name'),
  api('/rest/v1/transport_drivers?select=id,full_name&active=eq.true&order=full_name'),
  api('/rest/v1/transport_vehicles?select=id,brand,plate_number&active=eq.true&order=plate_number'),
  api('/rest/v1/transport_carriers?select=id,name,carrier_type&active=eq.true&order=name'),
  api('/rest/v1/expeditor_defaults?select=expeditor_name,driver_id,vehicle_id')
 ]);
 const ids=routes.map(x=>x.id),deliveries=routes.map(x=>x.route_delivery_id).filter(Boolean);let points=[],facts=[],costPoints=[],docs=[],alloc=[],locations=[];
 if(ids.length){points=await manyByIn('/rest/v1/route_points?select=id,route_id,location_id,customer_id,customer_name,documents_count,weight,pallets,bottles,places,order_amount,point_delivery_cost&','route_id',ids);facts=await manyByIn('/rest/v1/route_facts?select=*&','route_id',ids);costPoints=await manyByIn('/rest/v1/transport_point_costs_v1?select=route_id,route_point_id,carrier,tariff_branch,district,zone,pallets,tt_fixed,pallet_tariff,calculated_cost,effective_cost&','route_id',ids);const pids=points.map(x=>x.id);if(pids.length)alloc=await manyByIn('/rest/v1/route_business_allocations?select=*&','route_point_id',pids);const lids=[...new Set(points.map(x=>x.location_id).filter(Boolean))];if(lids.length)locations=await manyByIn('/rest/v1/locations?select=id,address_id,customer_id,customer_name,delivery_address,settlement,district,region&','id',lids);if(deliveries.length)docs=await manyByIn('/rest/v1/source_documents?select=id,document_date,route_delivery_id,operation_code,sale_code,address_id,customer_id,employee_id,business_unit,customer_name,delivery_address,warehouse,weight,order_amount,pallets&','route_delivery_id',deliveries)}
 state.all={routes,points,facts,alloc,manual,docs,costPoints,autoCarriers,weekRoutes:routes,locations,waves,drivers,vehicles,carriers,defaults};renderWarehouseOptions();applyWarehouse();go(page)
 }catch(e){view.innerHTML='<div class="card box err">Помилка завантаження: '+E(e.message)+'</div>'}}

logistics=function(){const byDate={};D.routes.forEach(r=>{(byDate[r.route_date]??=[]).push(r)});const html=Object.entries(byDate).map(([dt,rr])=>{const byWh={};rr.forEach(r=>(byWh[r.warehouse||'Без складу']??=[]).push(r));return `<div class="date-group"><div class="date-label">${dmy(dt)}</div>${Object.entries(byWh).map(([wh,rs])=>`<div class="warehouse-group"><div class="warehouse-head"><div><h3>${E(wh)}</h3><div class="group-note">${rs.length} маршрутів · ${rs.reduce((s,r)=>s+routeTT(r),0)} ТТ</div></div></div>${rs.map(r=>{const f=factFor(r.id),c=carrierFor(r);return `<div class="route-card-v19" onclick="routeCard(${r.id})"><div class="route-top"><div><div class="route-id">Маршрут ${E(r.route_delivery_id||r.id)}</div><div class="note">${E(r.expeditor_name||'—')}</div></div><span class="tag">${E(c||'Перевізник не вказаний')}</span></div><div class="route-summary"><div class="mini-stat"><span>ТТ / адреси</span><b>${routeTT(r)}</b></div><div class="mini-stat"><span>Документи</span><b>${routeDocs(r).length}</b></div><div class="mini-stat"><span>Палети</span><b>${P(routePal(r))}</b></div><div class="mini-stat"><span>Сума</span><b>${M(routeSales(r))}</b></div><div class="mini-stat"><span>Хвиля</span><b>${E(f.wave||'—')}</b></div><div class="mini-stat"><span>Водій</span><b>${E(f.driver_name||'—')}</b></div></div></div>`}).join('')}</div>`).join('')}</div>`}).join('');view.innerHTML=`<div class="head"><div><h2>Маршрути</h2><div class="note">Маршрут → адреси ТТ → документи продажу</div></div><span class="tag">${D.routes.length} маршрутів</span></div>${html||'<div class="card box">Немає маршрутів за вибраний період</div>'}`}

routeCard=function(id){const r=D.routes.find(x=>x.id===id);if(!r)return;const f=factFor(id),defs=defaultFor(r),groups=addressGroups(r),c=carrierFor(r),driverDefault=(state.all.drivers||[]).find(x=>x.id===defs.driver_id)?.full_name||'',vehicleDefault=(state.all.vehicles||[]).find(x=>x.id===defs.vehicle_id)?.plate_number||'';
 const addrHtml=groups.map((g,i)=>`<div class="address-card"><div class="address-name">${i+1}. ${E(g.name||'ТТ')}</div><div class="address-text">${E(g.address||'Адреса не вказана')}</div>${g.business?`<div class="tt-business">${E(g.business)}</div>`:''}<div class="route-summary" style="display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:9px"><div class="mini-stat"><span>Документи</span><b>${g.docs.length}</b></div><div class="mini-stat"><span>Палети</span><b>${P(g.point?.pallets||0)}</b></div><div class="mini-stat"><span>Сума</span><b>${M(g.docs.reduce((s,d)=>s+(+d.order_amount||0),0))}</b></div></div><div class="doc-stack">${g.docs.map(d=>`<div class="doc-mini"><div class="doc-mini-top"><b>№ ${E(d.sale_code||d.operation_code||'—')}</b><b>${M(d.order_amount)}</b></div><div class="doc-mini-meta">${E(d.document_date||'—')} · ${E(business(d.business_unit)||'—')} · EmployeeID ${E(d.employee_id||'—')}</div></div>`).join('')||'<div class="empty-note">Документів не знайдено</div>'}</div></div>`).join('');
 view.innerHTML=`<button class="btn back" onclick="logistics()">← Маршрути</button><div class="route-detail-head"><div class="route-card-v19" style="cursor:default"><div class="label">Маршрут</div><h2 style="margin:5px 0">${E(r.route_delivery_id||r.id)}</h2><div class="note">${E(r.route_date)} · ${E(r.warehouse||'—')} · ${E(r.expeditor_name||'—')}</div><div class="route-summary"><div class="mini-stat"><span>ТТ / адреси</span><b>${groups.length}</b></div><div class="mini-stat"><span>Документи</span><b>${routeDocs(r).length}</b></div><div class="mini-stat"><span>Палети</span><b>${P(routePal(r))}</b></div><div class="mini-stat"><span>Сума</span><b>${M(routeSales(r))}</b></div></div></div></div>
 <div class="fact-editor"><h3 style="margin-top:0">Факт маршруту</h3><div class="fact-grid">
 <div class="fact-field"><label>Хвиля</label><div class="fact-row"><select id="rfWave">${listOptions(state.all.waves,x=>x.name)}</select><button class="add-mini" onclick="addLookup('wave',${id})">+</button></div></div>
 <div class="fact-field"><label>Водій</label><div class="fact-row"><select id="rfDriver">${listOptions(state.all.drivers,x=>x.full_name,x=>x.full_name)}</select><button class="add-mini" onclick="addLookup('driver',${id})">+</button></div></div>
 <div class="fact-field"><label>Авто</label><div class="fact-row"><select id="rfVehicle">${listOptions(state.all.vehicles,x=>x.plate_number,x=>(x.plate_number+(x.brand?' · '+x.brand:'')))}</select><button class="add-mini" onclick="addLookup('vehicle',${id})">+</button></div></div>
 <div class="fact-field"><label>Перевізник</label><div class="fact-row"><select id="rfCarrier">${listOptions(state.all.carriers,x=>x.name,x=>x.name)}</select><button class="add-mini" onclick="addLookup('carrier',${id})">+</button></div></div>
 </div><div class="fact-actions"><button class="btn" onclick="saveRouteFact(${id})">Зберегти маршрут</button></div></div>
 <div class="route-detail-head"><h3>Торгові точки · ${groups.length}</h3><div class="address-list">${addrHtml||'<div class="empty-note">Адрес не знайдено</div>'}</div></div>`;
 setSelect('rfWave',f.wave||'');setSelect('rfDriver',f.driver_name||driverDefault);setSelect('rfVehicle',f.vehicle_number||vehicleDefault);setSelect('rfCarrier',f.carrier_name||c||'')}

saveRouteFact=async function(id){try{const body={route_id:id,wave:rfWave.value||null,driver_name:rfDriver.value||null,vehicle_number:rfVehicle.value||null,carrier_name:rfCarrier.value||null,updated_at:new Date().toISOString()};await api('/rest/v1/route_facts?on_conflict=route_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(body)});await loadAll();routeCard(id)}catch(e){alert('Не збережено: '+e.message)}};
addLookup=async function(type,id){try{if(type==='wave'){const name=prompt('Назва нової хвилі');if(!name)return;await api('/rest/v1/transport_waves',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({name:name.trim(),active:true})})}else if(type==='driver'){const full_name=prompt('ПІБ нового водія');if(!full_name)return;await api('/rest/v1/transport_drivers',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({full_name:full_name.trim(),active:true})})}else if(type==='vehicle'){const plate_number=prompt('Державний номер авто');if(!plate_number)return;const brand=prompt('Марка авто (необов’язково)')||'';await api('/rest/v1/transport_vehicles',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({plate_number:plate_number.trim(),brand:brand.trim(),active:true})})}else{const name=prompt('Назва нового перевізника');if(!name)return;await api('/rest/v1/transport_carriers',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({name:name.trim(),carrier_type:'route',active:true})})}await loadAll();routeCard(id)}catch(e){alert('Не додано: '+e.message)}};

ensureControls();
})();
