(()=>{
const selectedWarehouses=new Set();
const css=document.createElement('style');css.textContent=`
.multi-wh-wrap{position:relative;width:100%}.multi-wh-btn{width:100%;min-height:46px;border:1px solid var(--line);border-radius:16px;background:var(--card);color:var(--ink);padding:11px 14px;text-align:left;font-weight:800;display:flex;justify-content:space-between;gap:10px;align-items:center}.multi-wh-panel{position:absolute;left:0;right:0;top:calc(100% + 7px);z-index:60;background:var(--card);border:1px solid var(--line);border-radius:18px;padding:10px;box-shadow:0 18px 45px #0005;display:none;max-height:320px;overflow:auto}.multi-wh-panel.open{display:block}.multi-wh-item{display:flex;align-items:center;gap:10px;padding:10px;border-radius:12px}.multi-wh-item:hover{background:var(--soft)}.multi-wh-item input{width:19px;height:19px;accent-color:var(--accent)}.multi-wh-actions{display:flex;gap:8px;position:sticky;bottom:0;background:var(--card);padding-top:9px}.multi-wh-actions button{flex:1;border:0;border-radius:11px;padding:10px;font-weight:900}.multi-wh-done{background:var(--accent);color:#fff}.multi-wh-all{background:var(--soft);color:var(--ink)}
html[data-tr-theme="dark"] .multi-wh-btn,html[data-tr-theme="dark"] .multi-wh-panel{background:#151a22!important;color:#f5f2ee!important;border-color:#303642!important}.route-card-v19{cursor:pointer!important}
`;
document.head.appendChild(css);

function routeIdFromCard(card){const attr=card.getAttribute('onclick')||'';const m=attr.match(/routeCard\((\d+)\)/);if(m)return Number(m[1]);const t=card.querySelector('.route-id')?.textContent||'';const d=t.match(/(\d{8,})/);if(!d)return null;const r=(D.routes||[]).find(x=>String(x.route_delivery_id)===d[1]);return r?Number(r.id):null}
function bindRouteClicks(){document.querySelectorAll('.route-card-v19').forEach(card=>{const id=routeIdFromCard(card);if(!id)return;card.dataset.routeId=String(id);card.onclick=null;if(card.dataset.bound26)return;card.dataset.bound26='1';card.addEventListener('click',e=>{if(e.target.closest('.route-select')||e.target.closest('input')||e.target.closest('button')||e.target.closest('select'))return;routeCard(id)})})}

function currentWarehouses(){return [...new Set((D.routes||[]).map(r=>r.warehouse||'Без складу'))].sort((a,b)=>a.localeCompare(b,'uk'))}
function applyWarehouseFilter(){const cards=document.querySelectorAll('.route-card-v19');cards.forEach(card=>{const id=Number(card.dataset.routeId||routeIdFromCard(card));const r=(D.routes||[]).find(x=>Number(x.id)===id);const visible=!selectedWarehouses.size||selectedWarehouses.has(r?.warehouse||'Без складу');card.style.display=visible?'':'none'});document.querySelectorAll('.warehouse-group').forEach(group=>{const visible=[...group.querySelectorAll('.route-card-v19')].some(c=>c.style.display!=='none');group.style.display=visible?'':'none'});const b=document.getElementById('multiWhBtn');if(b)b.firstChild.textContent=selectedWarehouses.size?`Склади: ${selectedWarehouses.size}`:'Всі склади'}
function mountMultiWarehouse(){const old=document.getElementById('w20')||document.getElementById('warehouseSel');if(!old||document.getElementById('multiWhWrap'))return;const ws=currentWarehouses();selectedWarehouses.clear();const wrap=document.createElement('div');wrap.className='multi-wh-wrap';wrap.id='multiWhWrap';wrap.innerHTML=`<button type="button" id="multiWhBtn" class="multi-wh-btn"><span>Всі склади</span><span>⌄</span></button><div id="multiWhPanel" class="multi-wh-panel">${ws.map(w=>`<label class="multi-wh-item"><input type="checkbox" value="${E(w)}"><span>${E(w)}</span></label>`).join('')}<div class="multi-wh-actions"><button type="button" class="multi-wh-all" id="multiWhAll">Всі</button><button type="button" class="multi-wh-done" id="multiWhDone">Готово</button></div></div>`;old.replaceWith(wrap);const panel=wrap.querySelector('#multiWhPanel');wrap.querySelector('#multiWhBtn').onclick=()=>panel.classList.toggle('open');wrap.querySelector('#multiWhAll').onclick=()=>{selectedWarehouses.clear();wrap.querySelectorAll('input[type=checkbox]').forEach(x=>x.checked=false);applyWarehouseFilter()};wrap.querySelector('#multiWhDone').onclick=()=>{selectedWarehouses.clear();wrap.querySelectorAll('input[type=checkbox]:checked').forEach(x=>selectedWarehouses.add(x.value));panel.classList.remove('open');applyWarehouseFilter()};document.addEventListener('click',e=>{if(!wrap.contains(e.target))panel.classList.remove('open')},{once:false})}

const oldLogistics26=logistics;
logistics=function(){const out=oldLogistics26();setTimeout(()=>{bindRouteClicks();mountMultiWarehouse();applyWarehouseFilter()},0);return out};
const oldGo26=go;
go=function(...args){const out=oldGo26(...args);setTimeout(()=>{if(page==='logistics'){bindRouteClicks();mountMultiWarehouse();applyWarehouseFilter()}},0);return out};
setTimeout(()=>{if(page==='logistics'){bindRouteClicks();mountMultiWarehouse();applyWarehouseFilter()}},0);
})();