(()=>{
const esc=typeof E==='function'?E:s=>String(s??'');
const fmt=n=>new Intl.NumberFormat('uk-UA',{maximumFractionDigits:3}).format(Number(n)||0);
const money=n=>new Intl.NumberFormat('uk-UA',{maximumFractionDigits:0}).format(Number(n)||0)+' грн';
const css=document.createElement('style');css.textContent=`
.branch-entry{margin:14px 0;border:1px solid var(--line);border-radius:20px;background:var(--card);overflow:hidden}.branch-entry-head{padding:15px;display:flex;justify-content:space-between;align-items:center;gap:10px;cursor:pointer}.branch-entry-head h3{margin:0;font-size:15px}.branch-entry-head .note{margin-top:3px}.branch-entry-toggle{width:34px;height:34px;border:0;border-radius:11px;background:var(--soft);color:var(--ink);font-size:20px;font-weight:900}.branch-entry-body{display:none;padding:0 15px 15px}.branch-entry.open .branch-entry-body{display:block}.branch-form{display:grid;grid-template-columns:1fr 1fr;gap:9px}.branch-field label{display:block;font-size:9px;font-weight:850;color:var(--muted);margin-bottom:5px}.branch-field input,.branch-field select{width:100%;border:1px solid var(--line);border-radius:12px;background:var(--soft);color:var(--ink);padding:11px}.branch-field.full{grid-column:1/-1}.branch-save{grid-column:1/-1;border:0;border-radius:13px;padding:12px;background:#4f72ff;color:#fff;font-weight:950}.branch-list{display:grid;gap:7px;margin-top:12px}.branch-row{display:grid;grid-template-columns:1fr auto;gap:8px;border-top:1px solid var(--line);padding-top:9px}.branch-row b{font-size:11px}.branch-row span{font-size:9px;color:var(--muted)}.branch-cost{font-size:12px!important;color:var(--ink)!important;font-weight:950}@media(max-width:430px){.branch-form{grid-template-columns:1fr}.branch-field.full,.branch-save{grid-column:auto}}
`;document.head.appendChild(css);
function currentDate(){return document.getElementById('d20')?.value||document.getElementById('date')?.value||new Date().toISOString().slice(0,10)}
function carrierOptions31(){return '<option value="">— Обрати —</option>'+((D.carriers||[]).map(x=>`<option value="${esc(x.name)}">${esc(x.name)}</option>`).join(''))}
function renderBranchBlock(){if(page!=='logistics')return;const old=document.getElementById('branchEntry31');if(old)old.remove();const host=view.querySelector('.head');if(!host)return;const entries=(D.manual||[]).filter(x=>x.entry_type==='branch_replenishment');const box=document.createElement('div');box.id='branchEntry31';box.className='branch-entry';box.innerHTML=`<div class="branch-entry-head"><div><h3>Доставка на філії</h3><div class="note">Ручне внесення поповнення філій та витрат</div></div><button class="branch-entry-toggle">+</button></div><div class="branch-entry-body"><div class="branch-form"><div class="branch-field"><label>Дата</label><input id="brDate31" type="date" value="${currentDate()}"></div><div class="branch-field"><label>Склад відправлення</label><input id="brSender31" placeholder="Склад"></div><div class="branch-field"><label>Філія отримувач</label><input id="brReceiver31" placeholder="Філія"></div><div class="branch-field"><label>Перевізник</label><select id="brCarrier31">${carrierOptions31()}</select></div><div class="branch-field"><label>Відправлень</label><input id="brShip31" type="number" min="0" step="1" inputmode="numeric"></div><div class="branch-field"><label>Палети</label><input id="brPal31" type="number" min="0" step="0.001" inputmode="decimal"></div><div class="branch-field"><label>Витрати, грн</label><input id="brCost31" type="number" min="0" step="0.01" inputmode="decimal"></div><div class="branch-field full"><label>Коментар</label><input id="brComment31" placeholder="За потреби"></div><button class="branch-save" id="brSave31">Зберегти доставку на філію</button></div><div class="branch-list">${entries.map(x=>`<div class="branch-row"><div><b>${esc(x.sender_warehouse||'—')} → ${esc(x.receiver_branch||'—')}</b><br><span>${esc(x.entry_date||'')} · ${esc(x.carrier_name||'—')} · ${fmt(x.pallets)} пал.</span></div><span class="branch-cost">${money(x.expense_amount)}</span></div>`).join('')}</div></div>`;host.after(box);box.querySelector('.branch-entry-head').onclick=e=>{if(e.target.closest('select,input'))return;box.classList.toggle('open');box.querySelector('.branch-entry-toggle').textContent=box.classList.contains('open')?'−':'+'};box.querySelector('#brSave31').onclick=saveBranch31}
async function saveBranch31(){try{const row={entry_date:brDate31.value||currentDate(),entry_type:'branch_replenishment',sender_warehouse:brSender31.value.trim()||null,receiver_branch:brReceiver31.value.trim()||null,carrier_name:brCarrier31.value||null,shipments_count:Number(brShip31.value)||0,points_count:0,pallets:Number(brPal31.value)||0,sales_amount:0,expense_amount:Number(brCost31.value)||0,comment:brComment31.value.trim()||null};if(!row.sender_warehouse||!row.receiver_branch)return alert('Вкажіть склад відправлення та філію отримувача');await api('/rest/v1/manual_transport_entries',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(row)});await loadAll();logistics()}catch(e){alert('Не вдалося зберегти: '+e.message)}}
const oldLog31=logistics;logistics=function(){const r=oldLog31();setTimeout(renderBranchBlock,0);return r};setTimeout(renderBranchBlock,100);
})();