(()=>{
const css=`
.route-list{display:grid;gap:10px}.route-card{background:#fff;border:1px solid var(--line);border-radius:17px;padding:14px;box-shadow:0 5px 18px #00000009}.route-top{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.route-id{font-size:17px;font-weight:900}.route-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:12px}.route-stat{background:#f7f8fa;border-radius:11px;padding:9px}.route-stat span{display:block;font-size:10px;color:var(--muted);font-weight:700;margin-bottom:3px}.route-stat b{font-size:13px}.cost-blocks{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin-top:13px}.cost-card{background:#fff;border:1px solid var(--line);border-radius:17px;padding:14px;cursor:pointer;min-height:145px}.cost-card h3{margin:0 0 10px;font-size:15px}.cost-main{font-size:23px;font-weight:900}.cost-meta{margin-top:9px;font-size:11px;color:var(--muted);line-height:1.55}.week-strip{display:grid;grid-template-columns:repeat(5,1fr);gap:7px;margin-top:10px}.day-card{background:#fff;border:1px solid var(--line);border-radius:13px;padding:10px}.day-card b{display:block;font-size:16px;margin-top:4px}.day-card span{font-size:10px;color:var(--muted)}.cost-card.stv,.cost-card.sav{border-top:4px solid var(--accent)}
@media(max-width:950px){.cost-blocks{grid-template-columns:1fr 1fr}.week-strip{grid-template-columns:1fr 1fr}.route-grid{grid-template-columns:1fr 1fr}.tablecard{overflow:visible}.mobile-hide{display:none!important}}
@media(max-width:520px){.cost-blocks{grid-template-columns:1fr}.week-strip{grid-template-columns:1fr}.route-grid{grid-template-columns:1fr 1fr}.route-card{padding:13px}.cost-card{min-height:auto}}
`;
let st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
D.costPoints=[];D.autoCarriers=[];D.weekRoutes=[];
const oldApi=api;
function monday(d){let x=new Date(d+'T12:00:00'),day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);return x.toISOString().slice(0,10)}
function plusDays(d,n){let x=new Date(d+'T12:00:00');x.setDate(x.getDate()+n);return x.toISOString().slice(0,10)}
function dmy(d){let [y,m,dd]=d.split('-');return dd+'.'+m}
function carrierForRoute(r){let a=D.autoCarriers.find(x=>x.expeditor_name===r.expeditor_name);if(a)return a.auto_carrier;let f=D.facts.find(x=>x.route_id===r.id);return f?.carrier_name||''}
function routeCalculatedCost(routeId){return D.costPoints.filter(x=>x.route_id===routeId).reduce((s,x)=>s+(+x.effective_cost||0),0)}
function carrierStats(carrier){let pp=D.costPoints.filter(x=>x.carrier===carrier),routeIds=[...new Set(pp.map(x=>x.route_id))];return{cost:pp.reduce((s,x)=>s+(+x.effective_cost||0),0),tt:pp.length,pal:pp.reduce((s,x)=>s+(+x.pallets||0),0),routes:routeIds.length,missing:pp.filter(x=>x.effective_cost==null).length}}
function fopStats(){let rr=D.routes.filter(r=>{let c=carrierForRoute(r);return /фоп|діден|різун|скіби|скіб/i.test(c)}),ids=new Set(rr.map(x=>x.id)),ff=D.facts.filter(x=>ids.has(x.route_id));return{routes:rr.length,tt:D.points.filter(x=>ids.has(x.route_id)).length,pal:D.points.filter(x=>ids.has(x.route_id)).reduce((s,x)=>s+(+x.pallets||0),0),cost:ff.reduce((s,x)=>s+(+x.tariff||0),0)}}
function costBox(title,s,type,cls=''){return `<div class="cost-card ${cls}" onclick="costDetail('${type}')"><h3>${title}</h3><div class="cost-main">${M(s.cost||0)}</div><div class="cost-meta">${s.routes||0} маршрутів · ${s.tt||0} ТТ<br>${N(s.pal||0)} палет${s.missing?`<br><span class="err">${s.missing} ТТ без визначеної зони</span>`:''}</div></div>`}
loadAll=async function(){try{
 let d=date.value,ws=monday(d),we=plusDays(ws,6);dataTag.textContent='Реальні дані · тиждень '+dmy(ws)+'–'+dmy(we);
 let [routes,manual,autoCarriers,weekRoutes]=await Promise.all([
  oldApi('/rest/v1/routes?select=id,route_date,route_delivery_id,expeditor_name,warehouse,total_points,total_documents,total_weight,total_pallets,total_order_amount&route_date=eq.'+d),
  oldApi('/rest/v1/manual_transport_entries?select=*&entry_date=eq.'+d+'&order=created_at.desc'),
  oldApi('/rest/v1/expeditor_auto_carrier?select=expeditor_name,auto_carrier&active=eq.true'),
  oldApi('/rest/v1/routes?select=id,route_date,total_points,total_pallets,total_order_amount&route_date=gte.'+ws+'&route_date=lte.'+we+'&order=route_date')
 ]),ids=routes.map(x=>x.id),points=[],facts=[],alloc=[],docs=[],costPoints=[];
 if(ids.length){let q=encodeURIComponent('('+ids.join(',')+')');[points,facts,costPoints]=await Promise.all([
  oldApi('/rest/v1/route_points?select=id,route_id,location_id,customer_id,customer_name,documents_count,weight,pallets,bottles,places,order_amount,point_delivery_cost&route_id=in.'+q),
  oldApi('/rest/v1/route_facts?select=*&route_id=in.'+q),
  oldApi('/rest/v1/transport_point_costs_v1?select=route_id,route_point_id,carrier,tariff_branch,district,zone,pallets,tt_fixed,pallet_tariff,calculated_cost,effective_cost&route_id=in.'+q)
 ]);
 let pids=points.map(x=>x.id);if(pids.length)alloc=await oldApi('/rest/v1/route_business_allocations?select=*&route_point_id=in.'+encodeURIComponent('('+pids.join(',')+')'));
 let deliveries=routes.map(x=>x.route_delivery_id).filter(Boolean);if(deliveries.length)docs=await oldApi('/rest/v1/source_documents?select=id,document_date,route_delivery_id,operation_code,sale_code,address_id,customer_id,employee_id,business_unit,customer_name,delivery_address,warehouse,bottles,places,weight,order_amount,pallets&route_delivery_id=in.'+encodeURIComponent('('+deliveries.map(x=>'"'+String(x).replaceAll('"','')+'"').join(',')+')'))}
 D={routes,points,facts,alloc,manual,docs,costPoints,autoCarriers,weekRoutes};go(page)
}catch(e){view.innerHTML='<div class="card box err">Помилка завантаження: '+E(e.message)+'</div>'}}

home=function(){let s=sums(),stv=carrierStats('STV'),sav=carrierStats('SAV'),fop=fopStats(),courRows=D.manual.filter(x=>x.entry_type==='courier'),repRows=D.manual.filter(x=>x.entry_type==='branch_replenishment'),cour={cost:courRows.reduce((a,x)=>a+(+x.expense_amount||0),0),routes:courRows.length,tt:courRows.reduce((a,x)=>a+(+x.points_count||0),0),pal:courRows.reduce((a,x)=>a+(+x.pallets||0),0)},rep={cost:repRows.reduce((a,x)=>a+(+x.expense_amount||0),0),routes:repRows.length,tt:repRows.reduce((a,x)=>a+(+x.points_count||0),0),pal:repRows.reduce((a,x)=>a+(+x.pallets||0),0)};
 let calcCost=fop.cost+stv.cost+sav.cost+cour.cost+rep.cost;
 let byDay={};D.weekRoutes.forEach(r=>{let z=byDay[r.route_date]||(byDay[r.route_date]={routes:0,tt:0,pal:0,sales:0});z.routes++;z.tt+=+r.total_points||0;z.pal+=+r.total_pallets||0;z.sales+=+r.total_order_amount||0});
 let days=Object.entries(byDay).map(([d,x])=>`<div class="day-card"><span>${dmy(d)}</span><b>${x.tt} ТТ</b><span>${x.routes} маршрутів · ${N(x.pal)} пал.</span></div>`).join('');
 view.innerHTML=`<div class="head"><div><h2>Україна · ${dmy(date.value)}</h2><div class="note">Факт ТТ, об’єми та транспортні витрати</div></div><span class="tag">${D.routes.length} маршрутів</span></div>
 <div class="kpis">${K('ТТ',N(s.tt),'showTT()')}${K('Палети',N(s.pal))}${K('Продажі',M(s.sales))}${K('Витрати',M(calcCost),'showCosts()')}${K('Логістика',s.sales?(calcCost/s.sales*100).toFixed(2)+'%':'—')}${K('1 ТТ',s.tt?M(calcCost/s.tt):'—')}</div>
 <div class="section"><h3>Транспортні витрати</h3><div class="cost-blocks">${costBox('ФОП',fop,'fop')}${costBox('SAV',sav,'sav','sav')}${costBox('STV',stv,'stv','stv')}${costBox('Кур’єрка',cour,'courier')}${costBox('Поповнення філій',rep,'branch')}</div></div>
 <div class="section"><div class="card box"><div class="head"><div><h3 style="margin:0">Поточний тиждень</h3><div class="note">Дані, які вже є в базі</div></div><b>${dmy(monday(date.value))}–${dmy(plusDays(monday(date.value),6))}</b></div><div class="week-strip">${days||'<span class="note">Немає даних</span>'}</div></div></div>`}

logistics=function(){let cards=D.routes.map(r=>{let f=D.facts.find(x=>x.route_id===r.id)||{},pp=D.points.filter(x=>x.route_id===r.id),c=carrierForRoute(r),isZone=/^(STV|SAV)$/.test(c),cost=isZone?routeCalculatedCost(r.id):(+f.tariff||0),missing=isZone?D.costPoints.filter(x=>x.route_id===r.id&&x.effective_cost==null).length:0;return `<div class="route-card click" onclick="routeCard(${r.id})"><div class="route-top"><div><div class="route-id">Маршрут ${E(r.route_delivery_id||r.id)}</div><div class="note">${E(r.expeditor_name||'—')}</div></div><span class="tag">${E(c||'Не визначено')}</span></div><div class="note" style="margin-top:8px">${E(r.warehouse||'—')}</div><div class="route-grid"><div class="route-stat"><span>ТТ</span><b>${pp.length}</b></div><div class="route-stat"><span>Палети</span><b>${N(pp.reduce((s,x)=>s+(+x.pallets||0),0))}</b></div><div class="route-stat"><span>Хвиля</span><b>${E(f.wave||'—')}</b></div><div class="route-stat"><span>Виїзд</span><b>${E(f.departure_time||'—')}</b></div><div class="route-stat"><span>Тариф / вартість</span><b>${M(cost)}</b></div><div class="route-stat"><span>Статус тарифу</span><b class="${missing?'err':'good'}">${missing?missing+' ТТ без зони':'OK'}</b></div></div></div>`}).join('');view.innerHTML=`<div class="head"><div><h2>Маршрути</h2><div class="note">Без горизонтального прокручування · натисни маршрут для деталей</div></div><span class="tag">${D.routes.length}</span></div><div class="route-list">${cards||'<div class="card box">Немає маршрутів</div>'}</div>`}

costDetail=function(type){let title=type.toUpperCase();if(type==='stv'||type==='sav'){let carrier=type.toUpperCase(),rows=D.costPoints.filter(x=>x.carrier===carrier),by={};rows.forEach(x=>{let z=by[x.route_id]||(by[x.route_id]={tt:0,pal:0,cost:0,missing:0});z.tt++;z.pal+=+x.pallets||0;if(x.effective_cost==null)z.missing++;else z.cost+=+x.effective_cost||0});let html=Object.entries(by).map(([rid,x])=>{let r=D.routes.find(q=>q.id==rid);return `<div class="route-card" onclick="routeCard(${rid})"><div class="route-top"><b>${E(r?.route_delivery_id||rid)}</b><b>${M(x.cost)}</b></div><div class="cost-meta">${x.tt} ТТ · ${N(x.pal)} палет ${x.missing?`· <span class="err">${x.missing} без зони</span>`:''}</div></div>`}).join('');view.innerHTML=`<div class="head"><div><h2>${carrier}</h2><div class="note">Розрахунок: фікс за ТТ + палети × тариф зони. ТТ згруповані до маршруту.</div></div><button class="btn back" onclick="home()">Назад</button></div><div class="route-list">${html||'<div class="card box">Немає даних</div>'}</div>`;return}
 if(type==='fop'){let rr=D.routes.filter(r=>/фоп|діден|різун|скіби|скіб/i.test(carrierForRoute(r)));view.innerHTML=`<div class="head"><h2>ФОП</h2><button class="btn back" onclick="home()">Назад</button></div><div class="route-list">${rr.map(r=>`<div class="route-card" onclick="routeCard(${r.id})"><b>${E(r.route_delivery_id||r.id)}</b><div class="note">${E(carrierForRoute(r)||'—')} · ${E(r.expeditor_name||'—')}</div></div>`).join('')||'<div class="card box">Немає внесених тарифів ФОП за дату</div>'}</div>`;return}
 let rows=D.manual.filter(x=>type==='courier'?x.entry_type==='courier':x.entry_type==='branch_replenishment');view.innerHTML=`<div class="head"><h2>${type==='courier'?'Кур’єрка':'Поповнення філій'}</h2><button class="btn back" onclick="home()">Назад</button></div><div class="route-list">${rows.map(x=>`<div class="route-card"><div class="route-top"><b>${E(x.carrier_name||x.receiver_branch||'Запис')}</b><b>${M(x.expense_amount||0)}</b></div><div class="cost-meta">${N(x.pallets||0)} палет · ${E(x.comment||'')}</div></div>`).join('')||'<div class="card box">Немає записів за дату</div>'}</div>`}
})();