(()=>{
 'use strict';
 const O=TRTS_OPS,A=TRTS_ANALYTICS,App=TRTS_APP,S=TRTS_SECURITY,E=O.E,$=s=>document.querySelector(s),T=v=>String(v??'').trim(),N=v=>Number(v)||0;
 const standard=r=>['fop','bakery','courier'].includes(O.sectionKey(r)),routes=()=>O.dat().routes||[],route=id=>routes().find(r=>String(r.id)===String(id));
 const dl=fields=>'<dl class="v444-metrics">'+fields.map(([k,v])=>'<div><dt>'+E(k)+'</dt><dd>'+E(v)+'</dd></div>').join('')+'</dl>';
 function routeMetrics(r){if(!standard(r))return'';const m=O.metrics(r),cost=O.sectionKey(r)==='courier'?v439CourierRouteCost(r):m.cost;return dl([['К-ть ТТ',O.F(m.tt)],['Палети',O.F(m.pals,3)],['Загальна сума документів',O.M2(m.sales)],['Витрати',O.M2(cost)],['Вартість 1 ТТ',m.tt?O.M2(cost/m.tt):'—'],['% логістики',m.sales?O.P(cost/m.sales*100):'—']])}
 function pointMetrics(r,p){if(!standard(r))return'';const m=O.pointCost(r,p);return dl([['К-ть накладних',O.F(v436InvoiceCount(r,p))],['Палети',O.F(m.pals,3)],['Сума документів ТТ',O.M2(m.sum)],['Витрати',O.M2(m.cost)],['Вартість 1 ТТ',O.M2(m.cost)],['% логістики',O.P(m.log)]])}
 function replenMetrics(x){const cost=TRTS_COSTS.own(x.carrier_name)?0:N(x.tariff);return dl([['К-ть палет',O.F(x.pallets,3)],['Витрати',O.M2(cost)],['Вартість 1 палети',N(x.pallets)?O.M2(cost/N(x.pallets)):'—']])}
 function replenTotal(rows){return replenMetrics({pallets:rows.reduce((s,x)=>s+N(x.pallets),0),tariff:rows.reduce((s,x)=>s+(TRTS_COSTS.own(x.carrier_name)?0:N(x.tariff)),0)})}
 function notice(){if(localStorage.trts_update_notice!==TRTS_BUILD||localStorage.trts_update_ack===TRTS_BUILD)return;let box=$('#v444-notice');if(box)return;box=document.createElement('dialog');box.id='v444-notice';box.className='v444-dialog';box.innerHTML='<h2>Оновлення завершено</h2><p>Застосунок оновлено до версії '+E(TRTS_BUILD)+'</p><button id="v444-ack" type="button">Зрозуміло</button>';document.body.append(box);box.addEventListener('cancel',e=>e.preventDefault());box.querySelector('button').onclick=()=>{localStorage.trts_update_ack=TRTS_BUILD;localStorage.removeItem('trts_update_notice');box.close();box.remove()};box.showModal()}
 let updating=false;
 async function update(){if(updating)return;updating=true;const b=$('#trts-update');if(b)b.disabled=true;
  try{const url=new URL('./',location.href);url.searchParams.set('release',Date.now());const res=await fetch(url,{cache:'no-store',signal:AbortSignal.timeout(20000)});if(!res.ok)throw Error();const html=await res.text(),doc=new DOMParser().parseFromString(html,'text/html'),build=doc.querySelector('meta[name="trts-build"]')?.content;if(!build)throw Error();
   // Download the new same-origin scripts before invalidating a session.
   if('v'+build!==TRTS_BUILD){await Promise.all([...doc.querySelectorAll('script[src],link[rel="stylesheet"]')].map(async el=>{const u=new URL(el.getAttribute('src')||el.getAttribute('href'),url);if(u.origin!==location.origin)return;const r=await fetch(u,{cache:'reload',signal:AbortSignal.timeout(20000)});if(!r.ok)throw Error();await r.arrayBuffer()}));}
   if('caches'in window)await Promise.all((await caches.keys()).filter(k=>/trts|transport/i.test(k)).map(k=>caches.delete(k)));
   if(navigator.serviceWorker)await Promise.all((await navigator.serviceWorker.getRegistrations()).map(r=>r.unregister()));
   // The newly loaded boot script compares actual versions and clears old credentials before app code runs.
   if('v'+build!==TRTS_BUILD)await window.logout({redirect:url.href});else location.replace(url.href);
  }catch{let msg=$('#v444-update-status');if(!msg){msg=document.createElement('p');msg.id='v444-update-status';msg.setAttribute('role','status');b?.before(msg)}msg.textContent='Не вдалося завантажити оновлення. Перевірте зв’язок і спробуйте ще раз.';updating=false;if(b)b.disabled=false}
 }
 document.addEventListener('click',e=>{if(e.target.closest('#trts-update')){e.preventDefault();e.stopImmediatePropagation();update()}},true);
 const lower=v=>T(v).toLocaleLowerCase('uk-UA');let results=[],issues=[],searchTimer;
 function searchIndex(q){q=lower(q);if(!q)return[];const out=[];for(const r of routes()){const f=O.facts(r);if([r.route_delivery_id,r.id,r.expeditor_name,f.wave].some(x=>lower(x).includes(q)))out.push({rid:r.id,label:'Маршрут '+(r.route_delivery_id||r.id),sub:r.expeditor_name});for(const p of O.points(r))for(const [i,inv] of O.invoiceGroups(O.pointDocs(r,p)).entries())if(lower(inv.no).includes(q))out.push({rid:r.id,pid:p.id,invoice:i,label:'Накладна № '+inv.no,sub:p.customer_name+' · '+r.route_delivery_id})}return out}
 function search(){clearTimeout(searchTimer);searchTimer=setTimeout(()=>{results=searchIndex($('#v444-query')?.value);const list=$('#v444-results');if(!list)return;list.innerHTML=results.slice(0,100).map((x,i)=>'<button type="button" onclick="v444Result('+i+')"><b>'+E(x.label)+'</b><small>'+E(x.sub)+'</small></button>').join('')||'<p>Збігів у вибраному періоді немає</p>';if(results.length>100)list.insertAdjacentHTML('beforeend','<p>Перші 100 результатів. Уточніть пошук.</p>')},150)}
 function searchOpen(){O.modal('Швидкий пошук','<label>Накладна / ID маршруту / експедитор / хвиля<input id="v444-query" type="search" autocomplete="off" oninput="v444Search()"></label><p>Пошук у всіх блоках за вибраний глобальний період.</p><div id="v444-results" class="v444-results"></div>','<button onclick="v43CloseModal()">Закрити</button>');$('#v444-query')?.focus()}
 async function openItem(x){if(!x)return;v43CloseModal();App.selectRoutes();const source=O.dat().routes;await TRTS_COURIER.load();if(App.current()!=='routes'||source!==O.dat().routes)return;if(x.pid){v43OpenRoute(x.rid);v43OpenTT(x.rid,x.pid);if(x.invoice!==undefined){const card=$('[data-invoice-index="'+x.invoice+'"]');if(card){card.tabIndex=-1;card.classList.add('v444-found');card.scrollIntoView({block:'center'});card.focus({preventScroll:true})}}}else v43OpenRoute(x.rid)}
 function thresholds(){try{return{costTT:500,log:10,growth:30,...JSON.parse(localStorage.trts_attention_thresholds||'{}')}}catch{return{costTT:500,log:10,growth:30}}}
 function detect(cache){const th=thresholds(),out=[],add=(type,r,p,detail)=>out.push({type,rid:r.id,pid:p?.id,label:(p?p.customer_name+' · ':'')+(r.route_delivery_id||r.id),sub:detail||r.expeditor_name});for(const r of routes()){const key=O.sectionKey(r),f=O.facts(r);if(key==='other'){add('База · нерозпізнані',r);continue}if(key==='pickup')continue;
   if(['sav','stv'].includes(key)){for(const p of O.points(r)){const q=TRTS_FINANCE.quote(r,p);if(!q?.branch||!Number.isInteger(Number(q.zone))||Number(q.zone)<1||Number(q.zone)>5)add('SAV/STV без зони',r,p,q?.errors?.join('; '))}}
   if(standard(r)){const carrier=key==='courier'?v439CourierDefault(r):T(f.carrier_name);if(!carrier)add('Без перевізника',r);if(key==='courier'){for(const p of O.points(r))if(!TRTS_COSTS.own(v439CourierPointCarrier(r,p))&&O.pointCost(r,p).cost<=0)add('Без тарифу',r,p)}else if(!TRTS_COSTS.own(carrier)&&(f.tariff_unknown||O.metrics(r).cost<=0))add('Без тарифу',r)}
   for(const p of O.points(r)){if(TRTS_FINANCE.quote(r,p)?.errors.length)continue;const m=O.pointCost(r,p);if(m.cost>th.costTT)add('Висока вартість 1 ТТ',r,p,O.M2(m.cost));if(m.log>th.log)add('Високий % логістики',r,p,O.P(m.log))}
  }
  if(cache?.previous){const before=new Map();for(const x of cache.previous.lines){const k=JSON.stringify([x.section,x.expeditor]);before.set(k,(before.get(k)||0)+A.cents(x.cost))}const now=new Map();for(const x of cache.current.lines){const k=JSON.stringify([x.section,x.expeditor]);now.set(k,(now.get(k)||0)+A.cents(x.cost))}for(const [k,cost] of now){const old=before.get(k);if(old>0&&(cost-old)/old*100>th.growth){const [section,expeditor]=JSON.parse(k);for(const r of routes().filter(r=>O.sectionKey(r)===section&&r.expeditor_name===expeditor))add('Різке зростання витрат',r,null,'Експедитор: +'+O.F((cost-old)/old*100,1)+'% до попереднього періоду')}}}
  return out;
 }
 function attention(cache){issues=detect(cache);const groups=[...new Set(issues.map(x=>x.type))],th=thresholds();return'<section class="v444-attention"><h3>Потребує уваги · '+issues.length+'</h3><div class="v444-results">'+groups.map((name,i)=>'<button onclick="v444Issue('+i+')"><b>'+E(name)+'</b><small>'+issues.filter(x=>x.type===name).length+' сигналів ›</small></button>').join('')+'</div>'+(!issues.length?'<p>Відхилень за заданими порогами не виявлено.</p>':'')+'<details><summary>Пороги сигналів</summary><form onsubmit="event.preventDefault();v444Thresholds()">'+[['costTT','Вартість 1 ТТ, грн'],['log','Логістика, %'],['growth','Ріст витрат, %']].map(([k,l])=>'<label>'+l+'<input id="v444-th-'+k+'" type="number" min="0.01" step="0.01" required value="'+th[k]+'"></label>').join('')+'<button>Застосувати</button></form><p>Лише підсвічування. ТОВ ТС ПЛЮС із тарифом 0 не є помилкою. Ріст порівнюється за блоком та експедитором.</p></details></section>'}
 let issueItems=[];
 function issue(index){const name=[...new Set(issues.map(x=>x.type))][index];issueItems=issues.filter(x=>x.type===name);O.modal(name,'<div class="v444-results">'+issueItems.map((x,i)=>'<button onclick="v444IssueItem('+i+')"><b>'+E(x.label)+'</b><small>'+E(x.sub)+'</small></button>').join('')+'</div>','<button onclick="v43CloseModal()">Закрити</button>')}
 const directions={local:'Локальна доставка',courier:'Кур’єрська доставка',replen:'Поповнення філій',sav:'SAV',stv:'STV'};let exportData=null,exportBusy=false;
 async function exportScreen(){if(!S.isAdmin())return;const p=v435ReportPeriod();O.screenLayout(true);O.view().innerHTML='<div class="v43-screen v443-settings"><button onclick="v443Settings()">‹ Меню</button><h2>Експорт даних → Excel</h2><form id="v444-export" onsubmit="event.preventDefault();v444Export()"><label>Початок періоду'+TRTS_UI.dateField('v444-from',p.from)+'</label><label>Кінець періоду'+TRTS_UI.dateField('v444-to',p.to)+'</label><button type="button" onclick="v444ExportLoad()">Завантажити період</button><label>Напрямок<select id="v444-direction" onchange="v444ExportFilters()">'+Object.entries(directions).map(([k,l])=>'<option value="'+k+'">'+l+'</option>').join('')+'</select></label><div id="v444-export-filters"></div><button id="v444-export-submit" disabled>Сформувати Excel</button><p id="v444-export-status" role="status"></p></form></div>';await exportLoad()}
 async function exportLoad(){if(exportBusy||!S.isAdmin())return;const from=$('#v444-from').value,to=$('#v444-to').value;if(!TRTS_UI.validDate(from)||!TRTS_UI.validDate(to)||from>to){$('#v444-export-status').textContent='Перевірте період';return}exportBusy=true;exportData=null;$('#v444-export-submit').disabled=true;$('#v444-export-status').textContent='Завантаження…';try{await S.identify();if(!S.isAdmin())throw Error('Доступ заборонений');const snapshot=await O.readSnapshot(from,to),[finance,courier]=await Promise.all([TRTS_FINANCE.prepare(from,to,snapshot.meta.rules),TRTS_COURIER.readSnapshot(snapshot.data,from,to)]);const report=O.withSnapshot(snapshot,()=>TRTS_FINANCE.withSnapshot(finance,()=>TRTS_COURIER.withSnapshot(courier,()=>App.buildReport())));if(!$('#v444-export'))return;exportData={...report,from,to};exportFilters();$('#v444-export-status').textContent='Дані готові. Розрахунки відповідають аналітиці.';$('#v444-export-submit').disabled=false}catch(e){if($('#v444-export-status'))$('#v444-export-status').textContent='Не вдалося сформувати дані: '+e.message}finally{exportBusy=false}}
 function exportRows(){if(!exportData)return[];const d=$('#v444-direction').value;return d==='replen'?exportData.replen:exportData.lines.filter(x=>d==='local'?x.kind==='local':d==='courier'?x.kind==='courier':x.section===d)}
 function exportFilters(){if(!exportData||!$('#v444-export-filters'))return;const rows=exportRows(),replen=$('#v444-direction').value==='replen';$('#v444-export-filters').innerHTML=[['branch','Філія покриття'],['business','Бізнес'],['carrier','Перевізник'],['zone','Зона']].map(([key,label])=>'<label>'+label+'<select id="v444-filter-'+key+'" '+(replen&&['business','zone'].includes(key)?'disabled':'')+'><option value="">'+(replen&&['business','zone'].includes(key)?'Не застосовується':'Усі')+'</option>'+[...new Set(rows.map(x=>T(x[key])).filter(Boolean))].sort().map(v=>'<option value="'+E(v)+'">'+E(v)+'</option>').join('')+'</select></label>').join('')}
 async function exportFile(){if(exportBusy||!S.isAdmin()||!exportData)return;exportBusy=true;try{await S.identify();if(!S.isAdmin())throw Error('Доступ заборонений');if($('#v444-from').value!==exportData.from||$('#v444-to').value!==exportData.to)throw Error('Спочатку завантажте обраний період');const rows=exportRows().filter(x=>['branch','business','carrier','zone'].every(k=>!$('#v444-filter-'+k).value||T(x[k])===$('#v444-filter-'+k).value)),replen=$('#v444-direction').value==='replen',groups=new Map();for(const x of rows){const key=JSON.stringify([x.date,x.routeId,x.pointId,x.branch,x.business,x.carrier,x.zone]);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(x)}const headers=['Дата','Маршрут','Експедитор','ТТ / запис','Філія покриття','Бізнес','Перевізник','Зона',...(replen?['Палети','Витрати','Вартість 1 палети']:['К-ть ТТ','Палети','Продажі','Витрати','Вартість 1 ТТ','% логістики']),'Стан розрахунку'];const data=[headers];for(const group of groups.values()){const x=group[0],m=A.total(group);data.push([x.date,x.routeName||'',x.expeditor||'',x.pointName||x.pointId,x.branch,x.business||'',x.carrier||'',x.zone||'',...(replen?[m.pallets,m.cost,m.pallets?m.cost/m.pallets:'']:[m.tt,m.pallets,m.sales,m.cost,m.costTT??'',m.log??'']),m.missing?'Неповні тарифні дані':''])}const bytes=TRTS_XLSX.workbook(data),url=URL.createObjectURL(new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'})),a=document.createElement('a');a.href=url;a.download='Transport-'+exportData.from+'-'+exportData.to+'.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#v444-export-status').textContent='Excel сформовано · '+(data.length-1)+' рядків'}catch(e){if($('#v444-export-status'))$('#v444-export-status').textContent=e.message}finally{exportBusy=false}}
 window.v444Search=search;window.v444Result=i=>openItem(results[i]);window.v444Issue=issue;window.v444IssueItem=i=>openItem(issueItems[i]);window.v444Export=exportFile;window.v444ExportLoad=exportLoad;window.v444ExportFilters=exportFilters;
 window.v444Thresholds=()=>{const next={};for(const k of ['costTT','log','growth']){next[k]=N($('#v444-th-'+k).value);if(next[k]<=0)return}localStorage.trts_attention_thresholds=JSON.stringify(next);TRTS_DASHBOARD.show()};
 window.TRTS_RELEASE={notice,routeMetrics,pointMetrics,replenMetrics,replenTotal,attention,detect,searchIndex,exportScreen};
 const bar=document.createElement('button');bar.id='v444-search';bar.type='button';bar.textContent='⌕ Пошук';bar.setAttribute('aria-label','Глобальний пошук');bar.title='Глобальний пошук';bar.onclick=searchOpen;document.querySelector('#app header.top')?.append(bar);
})();
