// Minimal OOXML workbook, UTF-8 strings and numeric cells. No formula execution or external dependencies.
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.TRTS_XLSX=api})(typeof window==='undefined'?globalThis:window,()=>{
 const enc=new TextEncoder(),xml=v=>String(v??'').replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g,'').replace(/[<>&"']/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]));
 const crc=bytes=>{let c=0xffffffff;for(const b of bytes){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0};
 const col=n=>{let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s};
 function zip(files){const parts=[],central=[];let offset=0;const header=n=>new Uint8Array(n),u16=(b,o,n)=>new DataView(b.buffer).setUint16(o,n,true),u32=(b,o,n)=>new DataView(b.buffer).setUint32(o,n,true);
  for(const [name,text] of Object.entries(files)){const n=enc.encode(name),data=enc.encode(text),sum=crc(data),h=header(30);u32(h,0,0x04034b50);u16(h,4,20);u16(h,6,0x800);u32(h,14,sum);u32(h,18,data.length);u32(h,22,data.length);u16(h,26,n.length);parts.push(h,n,data);const c=header(46);u32(c,0,0x02014b50);u16(c,4,20);u16(c,6,20);u16(c,8,0x800);u32(c,16,sum);u32(c,20,data.length);u32(c,24,data.length);u16(c,28,n.length);u32(c,42,offset);central.push(c,n);offset+=h.length+n.length+data.length}
  const length=central.reduce((s,x)=>s+x.length,0),end=header(22);u32(end,0,0x06054b50);u16(end,8,Object.keys(files).length);u16(end,10,Object.keys(files).length);u32(end,12,length);u32(end,16,offset);parts.push(...central,end);const out=header(parts.reduce((s,x)=>s+x.length,0));let i=0;for(const p of parts){out.set(p,i);i+=p.length}return out;
 }
 function workbook(rows){const ns='http://schemas.openxmlformats.org/spreadsheetml/2006/main';return zip({
  '[Content_Types].xml':'<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>',
  '_rels/.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>',
  'xl/workbook.xml':'<workbook xmlns="'+ns+'" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Транспортні витрати" sheetId="1" r:id="rId1"/></sheets></workbook>',
  'xl/_rels/workbook.xml.rels':'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/></Relationships>',
  'xl/worksheets/sheet1.xml':'<worksheet xmlns="'+ns+'"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><sheetData>'+rows.map((row,i)=>'<row r="'+(i+1)+'">'+row.map((v,j)=>'<c r="'+col(j)+(i+1)+'"'+(typeof v==='number'&&Number.isFinite(v)?'><v>'+v+'</v>':' t="inlineStr"><is><t xml:space="preserve">'+xml(v)+'</t></is>')+'</c>').join('')+'</row>').join('')+'</sheetData><autoFilter ref="A1:'+col(Math.max(0,(rows[0]?.length||1)-1))+Math.max(1,rows.length)+'"/></worksheet>'
 })}
 return{workbook};
});
